### PR TITLE
CPU: A32: Fix Vabs_V & Vneg_V (S8, S16, S32 & F32); add Tests.

### PR DESCRIPTION
**Pull request by LDj3SNuD**
Vabs_V & Vneg_V bug: The pre-existing decoder in use did not take into account the different size position in the opcode.
Vneg_V bug: The fast path of the F variant used scalar masks; moreover the slow path of the F variant was not reachable with FastFP off.
Improved opcodes table entries (FP16 blacklisting).

Tests performed successfully in both debug and release mode (with FastFP off/on).

Bugs found in MK8D, I have no idea if it can solve some graphic problems; any feedback is welcome (the same goes for other potential titles).

### CODE REVIEW

**Comment by gdkchan** [comment]
Fixes graphical issues on Blaster Master Zero, might also fix other 32-bit games with similar issues.
Before:
image
After:
image
Amazing work, nice to see those titles finally working properly.

**Comment by jduncanator** [comment]
This needs a CPU PPTC version number bump

**Comment by LDj3SNuD** [comment]
Done.

**Comment by legend800** [comment]
No change in MK8 black coins/items/screens (not sure if it was intended to fix):
2020-07-16 23_53_13-Ryujinx 1 0 4949 - Mario Kart 8 Deluxe v1 0 0 (0100152000022000) (32-bit)

**Comment by riperiperi** [comment]
It wasn't meant to fix MK8, that is a GPU issue.

**Pull request merged**
