### PR TITLE
Remove file error popup

### PR DESCRIPTION
**Pull request by bobhope9848**
Address #2191 
Added file size check to now only load in files more than zero bytes in length.

### CODE REVIEW

**Comment by gdkchan** [comment]
I think we need a general solution for invalid/corrupt files, rather than just ignoring empty files.

**Comment by bobhope9848** [comment]
> I think we need a general solution for invalid/corrupt files, rather than just ignoring empty files.

Alright how about upon loading games into the application for the first time we create a hash of the loaded game files and then report which files are corrupted? Or maybe you're looking for just a generic read the header of the file and see if it contains game data?

**Comment by gdkchan** [comment]
It already handles the corrupt and empty files. As far I can tell, the annoyance the user wants addressed is the dialog box every time the emulator opens and loads the game list. In this case the solution is simply removing the dialog box. My opinion is that it should only be shown only the first time (after you add the games directory and the list loads for the first time). After that, it's not very useful to have the same error message again and again. Anyway, I wouldn't be against just removing it entirely, it is not very useful.

**Comment by bobhope9848** [comment]
> It already handles the corrupt and empty files. As far I can tell, the annoyance the user wants addressed is the dialog box every time the emulator opens and loads the game list. In this case the solution is simply removing the dialog box. My opinion is that it should only be shown only the first time (after you add the games directory and the list loads for the first time). After that, it's not very useful to have the same error message again and again. Anyway, I wouldn't be against just removing it entirely, it is not very useful.

I think I might just go ahead and remove the message entirely. I'll work on both solutions just in case but it sounds like it doesn't really have a purpose anymore.

**Comment by bobhope9848** [comment]
Alright removed the popup from happening and reverted my previous change. Still writes the error to log so I think this is a good solution should the user want to investigate why their files aren't showing up. LMKWYT

**Review by AcK77 — APPROVED** [review]

**Review by riperiperi — APPROVED** [review]
LGTM

**Pull request merged**
