### PR TITLE
Fix checking for the wrong metadata files for applications launched with a different program index

### LINKED ISSUE #7044: [Regression] Mario 3D All Stars not applying updates when launching games after 1.1.1350
### Description of the issue

Super mario 3D all stars no longer applies updates to the sub games

### Reproduction steps

apply an update and load sunshine

### Log file

1.1.1349: [Ryujinx_1.1.1349_2024-07-17_17-52-32.log](https://github.com/user-attachments/files/16273174/Ryujinx_1.1.1349_2024-07-17_17-52-32.log)
1.1350: [Ryujinx_1.1.1350_2024-07-17_17-42-09.tar.gz](https://github.com/user-attachments/files/16273183/Ryujinx_1.1.1350_2024-07-17_17-42-09.tar.gz)

### OS

EndeavourOS

### Ryujinx version

1.1.1350

### Game version

1.0.0/1.1.0

### CPU

AMD Ryzen 9 7900X3D

### GPU

AMD RX 6600 XT/NVIDIA 3060

### RAM

64gb

### List of applied mods

_No response_

### Additional context?

the build ids are the same on 1350 but are different on 1349 meaning the update isn't applied correctly
<details close>
<summary>1.1.1350</summary>
<br>

1.1.0:
```00:00:00.387 |I| ModLoader LoadCheats: Build ids found for application 010049900F546002:
    31A2773EA6928FFE3D32B17B3AD08F54826DA39F000000000000000000000000
    ED0D7ACE84EEC7807225034AD8A30CFD313E422D000000000000000000000000
    3B1090649CA17EE83E29F43600B63BE5BF582597000000000000000000000000
    404D5FF34137BBA3D49EC583EDA5E8FF130C5CE9000000000000000000000000
    BAE7AE46F3ED2B27870C17C6B07BDF30F77F9655000000000000000000000000
    CDB385C299FDBA2786299EA08A86CA25B2699CB0000000000000000000000000
```
1.0.0
```00:00:00.233 |I| ModLoader LoadCheats: Build ids found for application 010049900F546002:
    31A2773EA6928FFE3D32B17B3AD08F54826DA39F000000000000000000000000
    ED0D7ACE84EEC7807225034AD8A30CFD313E422D000000000000000000000000
    3B1090649CA17EE83E29F43600B63BE5BF582597000000000000000000000000
    404D5FF34137BBA3D49EC583EDA5E8FF130C5CE9000000000000000000000000
    BAE7AE46F3ED2B27870C17C6B07BDF30F77F9655000000000000000000000000
    CDB385C299FDBA2786299EA08A86CA25B2699CB0000000000000000000000000
``` 

</details>

<details close>
<summary>1.1.1349</summary>
<br>

1.1.0:
```00:00:00.357 |I| ModLoader LoadCheats: Build ids found for application 010049900F546002:
    31A2773EA6928FFE3D32B17B3AD08F54826DA39F000000000000000000000000
    B21E3733E11D6FCF1A8D57CE51BEF4A5001CCF66000000000000000000000000
    3B1090649CA17EE83E29F43600B63BE5BF582597000000000000000000000000
    404D5FF34137BBA3D49EC583EDA5E8FF130C5CE9000000000000000000000000
    BAE7AE46F3ED2B27870C17C6B07BDF30F77F9655000000000000000000000000
    CDB385C299FDBA2786299EA08A86CA25B2699CB0000000000000000000000000
```    
1.0.0:
```00:00:00.207 |I| ModLoader LoadCheats: Build ids found for application 010049900F546002:
    31A2773EA6928FFE3D32B17B3AD08F54826DA39F000000000000000000000000
    ED0D7ACE84EEC7807225034AD8A30CFD313E422D000000000000000000000000
    3B1090649CA17EE83E29F43600B63BE5BF582597000000000000000000000000
    404D5FF34137BBA3D49EC583EDA5E8FF130C5CE9000000000000000000000000
    BAE7AE46F3ED2B27870C17C6B07BDF30F77F9655000000000000000000000000
    CDB385C299FDBA2786299EA08A86CA25B2699CB0000000000000000000000000
```

</details>

### PR DESCRIPTION
**Pull request by TSRBerry**
Thanks to @Littl3Guy for finding this issue and @piplup55 for testing this with me!

This PR fixes another regression from #6515 that caused Ryujinx to not apply updates for games that get launched with different program indices (like the games in Super Mario 3D All-Stars).

(Ryujinx also wasn't applying DLCs for these games, but that wasn't caused by #6515.)

The issue here was that we were looking for the `updates.json` (and `dlc.json`) in a directory with the exact same application id (which also contains the program index) as the name, which doesn't exist. Updates (and DLCs) are only managed for the base game, but still apply to the different program indices, so we need to remove the index from the application id before we check for `updates.json` (or `dlc.json`).

---

Fixes #7044

### CODE REVIEW

**Review by riperiperi — APPROVED** [review]
Nice catch!

**Comment by carlosgamer23** [comment]
As you know some games support 6gb ram and others only 4g, it would be nice if each game could have its individual configuration. For example, when I want to play Pokémon Legends Arceus, I need to disable the 6gb ram hack and several other settings that I left in the emulator for it to work in other games. Could you also add the 8gb ram hack you have in Sudachi no Ryujinx?

With their own settings, the games would suffer less from bugs, in addition to being possible to adjust the graphics individually in each of them.

**Review by AcK77 — APPROVED** [review]

**Comment by TSRBerry** [comment]
I thought about this again and figured I need to check if we have the same issue with `dlc.json`, although the code for it wasn't changed in #6515. I found the same issue there as well and pushed a commit to fix that.

I also applied these changes to the GUIs, but that shouldn't functionally matter, since the applications that are currently seen by the GUIs will always have a program index of 0 (see commit message of 315c4d11406a8eb49856ff170bab9c6a83004ac0).

Since I added new changes, I requested reviews again.

**Review by riperiperi — APPROVED** [review]

**Review by gdkchan — APPROVED** [review]
lgtm, thanks.

**Pull request merged**
