### PR TITLE
pctl: Implement EndFreeCommunication

### LINKED ISSUE #2420: pctl IParentalControlService: 1017 (EndFreeCommunication) is not implemented
pctl IParentalControlService: 1017 (EndFreeCommunication) is not implemented [10.0.0+]

[Switchbrew](https://switchbrew.org/wiki/Parental_Control_services#IParentalControlService)

### Service description
```
N/A
```

### Required by: 
Ryujinx/Ryujinx-Games-List#3111
https://github.com/Ryujinx/Ryujinx-Games-List/issues/3763
https://github.com/Ryujinx/Ryujinx-Games-List/issues/3933

### PR DESCRIPTION
**Pull request by AcK77**
This PR Implement `EndFreeCommunication` (checked by RE). Nothing more.

Closes #2420

### CODE REVIEW

**Comment by GamerzHell9137** [comment]
Amoogus is being stuck at this so its not yet playable
```00:00:41.670 |I| HLE.OsThread.16 ServiceAm .ctor: Applet 'Error' created.
00:00:41.674 |I| HLE.OsThread.16 ServiceAm : ErrorApplet version: 0x00000000```
![image](https://user-images.githubusercontent.com/2002038/186533917-350ae8e5-6f37-4a26-906c-0498b5004b2e.png)

**Review by Thog — APPROVED** [review]

**Comment by LukeWarnut** [comment]
Fixes Game Builder Garage crashing when attempting to share or receive a game online or locally.
image

**Comment by GamerzHell9137** [comment]
Fixes Among Us crashing when choosing Online Mode

**Comment by ActualMandM** [comment]
Fixes Splatoon 3: Splatfest World Premiere crashing after pressing ZL + ZR.

https://user-images.githubusercontent.com/15317421/186585440-c26e6a9c-589b-44cc-b6f6-8e53e2c0d476.mp4

**Pull request merged**
