### PR TITLE
Game List Caching and General Avalonia Responsiveness

### PR DESCRIPTION
**Pull request by patrick-hovsepian**
### Intent
Create an options to bypass loading applications directly from their game file on startup by relying on existing metadata entries in the Ryujinx program paths. This is related to issue #3285  and builds off of the PR #5093 

The UI implications for these changes have only been implemented in Avalonia. The GTK windows have been unaffected. As a result, enabling this option is only visible in Avalonia alongside some of the side effects (like refresh cancel). 

There are also enhancements made to UI responsiveness.
- Application Library refresh happens on a background thread and no longer blocks the UI
- Favoriting an applications no longer causes the entire application view to be reloaded, now it only reloads the changed entry (not perfect but a start) I'd also like to do something similar for other metadata changes like play time
- Introduces a new button to cancel library refreshes
- Minimum window with adjusted to allow for smaller windows
- Favorites icon was slightly enlarged for better visibility
---

### Implementation
A majority of the changes took place in the `ApplicationLibrary`. One goal was to simplify the logic flow and make it easier to read and trace. This largely involved breaking up existing functionality into their own methods. I did want to break up the reading of various file types but decided against it. I tried to normalize the metadata reads taking place on various file formats as much as possible.

We write back everything in the `ApplicationData` struct except for the control header. This means that when using cache load, save directories aren't detected and the option is effectively disable in the UI until a manual library reload happens. This has no bearing on game launch. I imagine we can/should populate this on start if the control header is missing but that can be a future enhancement. 

The existing metadata entry created per game was updated to include the additional info we read from the game files, including the app icon which is by far the largest structure we store. I considered compression but left as-is for now. The icon data is base64 string encoded on writes. This update set of metadata is written back to our local entry and on startup, entries are read from there rather than the game files. 

---

### UI View
New Setting
image
---

All Games Loaded
image
---

Game Loading in Progress
image

image
---

Partial List Loaded (Refresh Canceled)
image

---

### Potential Future Enhancements
- An option to reload a specific game from disk
- Cache additional info like save data locations, mods, updates, etc
- Custom app icons per game

### CODE REVIEW

**Comment by riperiperi** [comment]
This definitely improves Ava responsiveness a lot, on master when loading games from my network drive the UI stays solid white for a while.

I got this crash when using the cache option in settings (which defaulted off? is that intentional?)
```
00:00:02.974 |W| .NET ThreadPool Worker Application TryLoadApplicationsFromGamesCache: Outdated cached metadata file found for: 010000000000002f
00:00:03.017 |E| .NET ThreadPool Worker Application : Unhandled exception caught: System.IO.FileNotFoundException: Could not find file 'C:\Users\riperiperi\AppData\Roaming\Ryujinx\games\010000000000003b\gui\metadata.json'.
File name: 'C:\Users\riperiperi\AppData\Roaming\Ryujinx\games\010000000000003b\gui\metadata.json'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String, FileMode, FileAccess, FileShare, FileOptions)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String, FileMode, FileAccess, FileShare, FileOptions, Int64, Nullable`1 )
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String, FileMode, FileAccess, FileShare, FileOptions, Int64, Nullable`1)
   at System.IO.Strategies.SyncWindowsFileStreamStrategy..ctor(String, FileMode, FileAccess, FileShare, FileOptions, Int64, Nullable`1)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String, FileMode, FileAccess, FileShare, FileOptions, Int64, Nullable`1)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream, String, FileMode, FileAccess, FileShare, Int32, FileOptions, Int64, Nullable`1)
   at System.IO.FileStream..ctor(String, FileMode, FileAccess, FileShare, Int32, FileOptions, Int64)
   at System.IO.FileStream..ctor(String, FileMode, FileAccess, FileShare, Int32, FileOptions)
   at System.IO.FileStream..ctor(String, FileMode, FileAccess, FileShare, Int32, Boolean)
   at System.IO.FileStream..ctor(String, FileMode, FileAccess, FileShare)
   at System.IO.File.OpenRead(String)
   at Ryujinx.Common.Utilities.JsonHelper.DeserializeFromFile[T](String filePath, JsonTypeInfo`1 typeInfo)
   at Ryujinx.Ui.App.Common.ApplicationLibrary.LoadAndSaveMetaData(String titleId, Action`1 modifyFunction)
   at Ryujinx.Ui.App.Common.ApplicationLibrary.TryLoadApplicationsFromGamesCache()
   at Ryujinx.Ui.App.Common.ApplicationLibrary.LoadApplications(List`1 appDirs, Language desiredTitleLanguage, Boolean readFromDisk)
   at Ryujinx.Ava.UI.Windows.MainWindow.ReloadGameList(Boolean readFromDisk) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Ava\UI\Windows\MainWindow.axaml.cs:line 505
   at Ryujinx.Ava.UI.Windows.MainWindow.LoadApplications(Boolean readFromDisk) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Ava\UI\Windows\MainWindow.axaml.cs:line 493
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
```

**Comment by MutantAura** [comment]
`Ryujinx\games\010000000000003b` is the JIT sysmodule afaik. Which possibly explains why it doesn't have any associated metadata for the GUI.

**Comment by patrick-hovsepian** [comment]
Good to know about the JIT folder, error handling should've been tighter to begin with. I'll take a look once #4956 is merged since it's going to conflict anyway.

**Comment by patrick-hovsepian** [comment]
> (which defaulted off? is that intentional?)

Yeah, only because my thought was, if the user added games to a directory then launched an updated version of Ryujinx they wouldn't see it until they did a manual refresh. I do like the idea of it being the default so can make that change if desired. I also made a change to stop that crash.

**Comment by riperiperi** [comment]
When I load from the cache now, all my NCAs are missing. I think every format that appears without caching should appear with caching too.

**Comment by riperiperi** [comment]
It ends up stuck like this:
image

Clicking the X causes it to reload the list and find 33 games. There are nca-only dumps of games and a few extracted exefs within the folder.

**Comment by IsaacMarovitz** [comment]
Portions of this PR have been superseded by #5332 and #5516

**Pull request closed without merging**
