### PR TITLE
Rebind textures if format changes or they're buffer textures

### PR DESCRIPTION
**Pull request by riperiperi**
Fixes a regression from #3399 in the Mario Party Superstars spotlight minigame where an image would not rebind when its binding format was changed. Some other games may be affected.

Should also obsolete #3442, as this fixes it in a different way. Check the games that were meant to be fixed by that.

### CODE REVIEW

**Comment by GamerzHell9137** [comment]
Doen't fix Densha De Go 
https://github.com/Ryujinx/Ryujinx/issues/3435

**Comment by riperiperi** [comment]
> Doen't fix Densha De Go that was caused by the PR #3435

Neither did the other PR.

**Comment by GamerzHell9137** [comment]
> > Doen't fix Densha De Go that was caused by the PR #3435
> 
> Neither did the other PR. I don't think this particular oversight would be causing that issue.

Ohh, my bad. There's no known games that would get fixed by the other PR, it was just thought it would fix Densha which is why I tested.

**Comment by gdkchan** [comment]
The issue I was trying to fix is a weird black vertex explosion on OpenGL that was happening for only 1 frame or so on Shin Megami Tensei V. I tested both this and my PR on it again, and I still get it on both. I'm not sure of what else to test as I'm not aware of any other issue that might be caused by the bindings change.

**Review by gdkchan — APPROVED** [review]
lgtm, thanks.

**Review by Thog — APPROVED** [review]

**Pull request merged**
