### PR TITLE
PPTC meets ExeFS Patching.

### PR DESCRIPTION
**Pull request by LDj3SNuD**
Changelog:
- PPTC now supports Mods;
- PPTC already supported Cheats;
In both cases all mods or cheats of any complexity should work, but they should not change the external execution flow (between functions), otherwise functions could be profiled which should not or cannot be translated; I am not aware of such applications in practice.
- Refactoring of PtcProfiler.cs (the internal structure of the .info files now follows that of the .cache files; use of Hash128 instead of MD5; etc.) and Follow-up of Ptc.cs;
- *As a result of the aforementioned refactoring of PtcProfiler.cs, but also as a result of https://github.com/Ryujinx/Ryujinx/pull/2190, users' .info files will be invalidated*.

### CODE REVIEW

**Comment by Doctorwho1909** [comment]
it works fine but it has side effects being slower PPTC translation times and slower in game load times

**Comment by mhvuze** [comment]
I have been testing this with various ExeFS patches on the Monster Hunter Rise Demo over the last few days and haven't encountered any downsides or perceptible changes in regards to game load times. Worked excellent on my end.

I have also played through half of Super Mario Odyssey with this PR merged and ExeFS patches put into place. I initially suspected it caused longer in game load times but after double checking with the current Ryujinx master build, this couldn't be verified. No other occurrences otherwise.

**Review by wdekaron — APPROVED** [review]

**Comment by HiHiKazumaDesu** [comment]
I was unable to merge this PR with 1.0.6817, there seems to be a conflict with one of the most recent changes done to Master, other than that it does work  like a charm :D

**Comment by Alkaid-Benetnash** [comment]
Hi LDj3SNuD,
I rebase this pr on top of the #2168, which has already been merged.  The rebase is available on [my fork](https://github.com/Alkaid-Benetnash/Ryujinx/commit/257c57be538629569f676a2a92a0d705872a89a2).

I have tested this rebase plus #2138 on MHR with 1080p and 60fps mods.
The game is still bootable and playable but the mod seems not working as expected.
The mods are applied successfully:
```
00:00:01.746 |I| ModLoader ApplyProgramPatches: Matching IPSwitch patch '1.1.2.pchtxt' in '1080p' bid=69B97948A0CFFC019063C9046880347436E99A32
00:00:01.747 |I| ModLoader Parse: IPSwitch:    # MONSTER HUNTER RISE [0100B04011742000] v1.1.2 - 1080p
00:00:01.748 |I| ModLoader Parse: IPSwitch:    print_values 0x557af8 <= 09F0A7D2
00:00:01.748 |I| ModLoader Parse: IPSwitch:    print_values 0x557afc <= 0900C0F2
00:00:01.748 |I| ModLoader Parse: IPSwitch:    print_values 0x557b00 <= 09F0E7F2
00:00:01.749 |I| ModLoader ApplyProgramPatches: Matching IPSwitch patch '1.1.2.pchtxt' in '60fps' bid=69B97948A0CFFC019063C9046880347436E99A32
00:00:01.749 |I| ModLoader Parse: IPSwitch:    # MONSTER HUNTER RISE [0100B04011742000] v1.1.2 - 60fps
00:00:01.749 |I| ModLoader Parse: IPSwitch:    print_values 0x30cfe80 <= 094EA852
00:00:01.749 |I| ModLoader Parse: IPSwitch:    print_values 0x30cfe98 <= 29008052
00:00:01.754 |I| ModLoader Patch: Patching address offset 5579f8 <= 09 F0 A7 D2 len=4
00:00:01.754 |I| ModLoader Patch: Patching address offset 5579fc <= 09 00 C0 F2 len=4
00:00:01.754 |I| ModLoader Patch: Patching address offset 557a00 <= 09 F0 E7 F2 len=4
00:00:01.754 |I| ModLoader Patch: Patching address offset 30cfd80 <= 09 4E A8 52 len=4
00:00:01.754 |I| ModLoader Patch: Patching address offset 30cfd98 <= 29 00 80 52 len=4
```

Patched code also successfully invalidates the unpatched version:
```
00:00:17.210 |I| HLE.GuestThread.15 Ptc LoadTranslations: Invalidated translated function (address: 0x000000000855B9F0)
00:00:17.210 |I| HLE.GuestThread.15 Ptc LoadTranslations: Invalidated translated function (address: 0x000000000B0D3CDC)
00:00:17.227 |I| HLE.GuestThread.15 Ptc LoadTranslations: Invalidated translated function (address: 0x000000000B0D3C80)
```

However, most of the scenes (except for the booting/loading screen) are still under 30fps, which is the same performance as just "master + pr-2138" but worse than "LDN2.2 + the same mods". The 1080p mod seems working though.

Any suggestions about what am I missing here? Thanks!

**Comment by AcK77** [comment]
@Alkaid-Benetnash we currently don’t give support to custom build because that could lead to unexpected results, there is provided build by CI, if the PR needs a rebase, ask the dev gently and wait for it, do some chimera without knowing what you do isn’t recommended. Best Regards.

**Review by Thog — APPROVED** [review]

**Review by riperiperi — APPROVED** [review]
Very nice work on this! Apologies for the late review again.

**Pull request merged**
