### PR TITLE
chore: Update tests dependencies

### PR DESCRIPTION
**Pull request by marysaka**
As title say.

### CODE REVIEW

**Comment by TSRBerry** [comment]
rebased

**Comment by TSRBerry** [comment]
The only thing I've been able to figure out is that after updating the dependency `OpenThread` will fail with two different errors. Using 3.17.0 this method never fails and the test completes successfully.

The error messages logged below were created like this: [PartialUnmapState.cs](https://github.com/TSRBerry/Ryujinx/blob/fix/update-test-deps/Ryujinx.Common/Memory/PartialUnmaps/PartialUnmapState.cs#L145)

<details>
  <summary>CI run: OpenThread() error messages</summary>
  
  ```
  PartialUnmapState OpenThread failed for id '1': 87 - The parameter is incorrect.
  PartialUnmapState OpenThread failed for id '2': 87 - The parameter is incorrect.
  PartialUnmapState OpenThread failed for id '3': 87 - The parameter is incorrect.
  PartialUnmapState OpenThread failed for id '4': 87 - The parameter is incorrect.
  PartialUnmapState OpenThread failed for id '5': 87 - The parameter is incorrect.
  PartialUnmapState OpenThread failed for id '6': 87 - The parameter is incorrect.
  PartialUnmapState OpenThread failed for id '7': 87 - The parameter is incorrect.
  PartialUnmapState OpenThread failed for id '8': 87 - The parameter is incorrect.
  PartialUnmapState OpenThread failed for id '9': 87 - The parameter is incorrect.
  PartialUnmapState OpenThread failed for id '10': 87 - The parameter is incorrect.
  PartialUnmapState OpenThread failed for id '11': 87 - The parameter is incorrect.
  PartialUnmapState OpenThread failed for id '12': 5 - Access is denied.
  PartialUnmapState OpenThread failed for id '13': 5 - Access is denied.
  PartialUnmapState OpenThread failed for id '300': 5 - Access is denied.
  PartialUnmapState OpenThread failed for id '15': 5 - Access is denied.
  PartialUnmapState OpenThread failed for id '16': 5 - Access is denied.
  PartialUnmapState OpenThread failed for id '17': 5 - Access is denied.
  PartialUnmapState OpenThread failed for id '18': 5 - Access is denied.
  PartialUnmapState OpenThread failed for id '19': 5 - Access is denied.
  PartialUnmapState OpenThread failed for id '20': 5 - Access is denied.
    Failed PartialUnmap(True) [455 ms]
    Error Message:
       Expected: 1
    But was:  0

    Stack Trace:
       at Ryujinx.Tests.Memory.PartialUnmaps.PartialUnmap(Boolean readOnly) in D:\a\Ryujinx\Ryujinx\Ryujinx.Tests\Memory\PartialUnmaps.cs:line 159

  1)    at Ryujinx.Tests.Memory.PartialUnmaps.PartialUnmap(Boolean readOnly) in D:\a\Ryujinx\Ryujinx\Ryujinx.Tests\Memory\PartialUnmaps.cs:line 159


    Failed PartialUnmap(False) [194 ms]
    Error Message:
       Expected: 1
    But was:  0

    Stack Trace:
       at Ryujinx.Tests.Memory.PartialUnmaps.PartialUnmap(Boolean readOnly) in D:\a\Ryujinx\Ryujinx\Ryujinx.Tests\Memory\PartialUnmaps.cs:line 159
     at InvokeStub_PartialUnmaps.PartialUnmap(Object, Object, IntPtr*)

  1)    at Ryujinx.Tests.Memory.PartialUnmaps.PartialUnmap(Boolean readOnly) in D:\a\Ryujinx\Ryujinx\Ryujinx.Tests\Memory\PartialUnmaps.cs:line 159
     at InvokeStub_PartialUnmaps.PartialUnmap(Object, Object, IntPtr*)
  ```
</details>

**Comment by TSRBerry** [comment]
The following versions of NUnit3TestAdapter aren't able to pass the PartialUnmap tests on Windows:
- 4.3.1
- 4.3.0
- 4.2.0
- ...

**Comment by merryhime** [comment]
If this is desireable, a one-line way of getting rid of the CA1416 warning is 
```cs
Debug.Assert(OperatingSystem.IsWindows());
```

**Comment by TSRBerry** [comment]
> If this is desireable, a one-line way of getting rid of the CA1416 warning is
> 
> ```cs
> Debug.Assert(OperatingSystem.IsWindows());
> ```

I thought I already fixed them, but seems like I only did it on my fork. I originally disabled the warning for this method, but I think I like your solution better!

**Comment by TSRBerry** [comment]
Oddly enough this doesn't fix the warning within the thread. Guess I'll stick with the pragmas

**Review by TSRBerry — APPROVED** [review]
Updating to 4.1.0 ist good enough for now :D

**Review by AcK77 — APPROVED** [review]

**Pull request merged**
