### PR TITLE
Make structs readonly when applicable

### PR DESCRIPTION
**Pull request by SukharevAndrey**
It should reduce the amount of needless defensive copies without any regressions.

Some structs have also been made record structs to reduce the amount of trivial boilerplate equality code.

### CODE REVIEW

**Review by gdkchan — APPROVED** [review]
lgtm, thanks.

**Review by marysaka — APPROVED** [review]

**Comment by SukharevAndrey** [comment]
> Needs a rebase.

Done

**Review by gdkchan — APPROVED** [review]
lgtm, thanks.

**Review by TSRBerry — COMMENTED** [review]
Rider says there a 2 more structs that could be made readonly: 
1. `Ryujinx.Graphics.Vulkan/BitMap.cs`
2. `Ryujinx.Memory/Tracking/BitMap.cs`

Could you add these too?

Other than that, I couldn't find any issues, so I'll approve too when these two are added!

**Comment by SukharevAndrey** [comment]
> Rider says there a 2 more structs that could be made readonly:
> 
> 1. `Ryujinx.Graphics.Vulkan/BitMap.cs`
> 2. `Ryujinx.Memory/Tracking/BitMap.cs`
> 
> Could you add these too?
> 
> Other than that, I couldn't find any issues, so I'll approve too when these two are added!

Done

**Pull request merged**
