### PR TITLE
Source generated json serializers

### PR DESCRIPTION
**Pull request by SukharevAndrey**
Fixed version of #4094

### CODE REVIEW

**Comment by gdkchan** [comment]
I tested it here, and it still fails to load the configuration json from a previous version
> Failed to load config! Loading the default config instead.

**Comment by TSRBerry** [comment]
Could you share your config file? It loads fine for me.

**Comment by TSRBerry** [comment]
Nvm, found them! Now it works correctly.

**Review by marysaka — APPROVED** [review]
Seems fine to me, will need another rebase

**Pull request merged**
