### PR TITLE
Salieri: Shader Cache

### LINKED ISSUE #1542: Implement a Disk Shader Cache
## Feature Request

Implement a Disk Shader Cache (Not in RAM)

#### Overview:
A Disk Shader Cache will greatly improve performance and decrease or eliminate the stutters after several runs. 

#### Smaller Details: 
I´m not a dev, so I can´t tell you guys how to do it.

#### Nature of Request:  
- Addition

### Why would this feature be useful?
Will greatly improve performance and decrease or eliminate stutter. May also fix audio stutter caused by shaders compilation.

### PR DESCRIPTION
**Pull request by Thog**
Here come Salieri, my implementation of a disk shader cache!

"I'm sure you know why I named it that."
"It doesn't really mean anything."

This implementation collects shaders at runtime and cache them to be later compiled when starting a game.

Fix #1542.

97930245-37372880-1d6b-11eb-889c-5ae943880110

### CODE REVIEW

**Review by AcK77 — APPROVED** [review]
Lgtm! Amazing work as usual!

**Review by riperiperi — APPROVED** [review]
Very nice work! Obviously reviewed in private, no beating around the bush, but it looks as good here as it did there. :P

**Comment by MelonSpeedruns** [comment]
LGTM you badass

**Review by gdkchan — APPROVED** [review]
Approving as I already reviewed in private, lgtm.

**Pull request merged**
