### PR TITLE
Move Ryujinx projects to a new src directory

### PR DESCRIPTION
**Pull request by TSRBerry**
This PR contains only the move related commits which were previously also part of #4670. 

All Ryujinx projects including the solution file were moved into a new `src` directory, since @gdkchan wanted to do that for a while now.

I'm actually not quite sure if the solution file should stay in the repository root, since most IDEs will treat the directory with the solution file as the root directory. This would make accessing `.github` or `distribution` harder than before.

---

Make sure you **aren't** squash merging this PR!

### CODE REVIEW

**Comment by gdkchan** [comment]
> I'm actually not quite sure if the solution file should stay in the repository root, since most IDEs will treat the directory with the solution file as the root directory. This would make accessing `.github` or `distribution` harder than before.

FWIW other projects have the solution file at the root. I think it's fine if it makes things easier.

**Review by gdkchan — APPROVED** [review]
Thanks, I just hope that the rebase will really go smoothly.

**Comment by TSRBerry** [comment]
Kept the solution file (and related files which need to stay at the solution root) in the repository root and moved everything else.

Just requested the review again, since I also needed to adjust the github workflows again.

**Review by marysaka — APPROVED** [review]

**Review by gdkchan — APPROVED** [review]
lgtm, thanks.

**Pull request merged**
