### PR TITLE
Open a PR to trigger a build of master

### PR DESCRIPTION
**Pull request by Thealexbarney**
AppVeyor is currently down

(And "JI-NX" -> "JINX" needed to be fixed anyway)

### CODE REVIEW

**Comment by Thealexbarney** [comment]
Doesn't seem to be working. What uploads the builds to nightly.link? Searching the repo brought up nothing

**Comment by Thealexbarney** [comment]
There we go. Had to change something other than the readme

**Comment by CapitaineJSparrow** [comment]
From @EmulationFanatic 

⚠️ AppVeyor is currently down, which means Ryujinx downloads will be down as well. 

In the meantime, please download Ryujinx from here. These builds are equal to 1.0.7181.
Windows: https://nightly.link/Ryujinx/Ryujinx/actions/artifacts/147994505.zip
Linux: https://nightly.link/Ryujinx/Ryujinx/actions/artifacts/147994503.zip

No need to open a PR to get the latest master

**Comment by MetrosexualGarbodor** [comment]
Those links are from this PR.

**Pull request closed without merging**
