### PR TITLE
Initial support for FS Patching

### PR DESCRIPTION
**Pull request by mageven**
Currently implements IPS/IPSwitch patching on NSO load filtered by Build IDs (aka exefs patching). 
IPS based on Atmosphere's implementation. 
IPSwitch, my own, from the readme description and some samples.
The framework should be generic enough for more creative uses in the future.

This PR is currently Draft as the storage location for patches has to be decided.

~~Depends on #856 (`mem`)~~ (Merged now)

### Notes for testers
For now, create a directory named `nsopatches` in your Ryujinx userdir and place all your patches in it.
Patches can be placed in the root or in any hierarchy of directories inside.

#### IPSwitch
Files must have `.pchtxt` extension and have an `@nsobid-` header as the first line.

#### IPS
The file names should be like so-

`<nso_build_id>[.anything_you_want].ips`

Examples:

```
5786...859F.ips
5786...859F.myfix.ips
9ABCDE....123.resolution.ips
9ABCDE....123.2.ips
...
```

If everything's correct, you should be seeing Info logs like the following-

```
Found matching IPS patch for bid=... - <path>.ips
Found matching IPS patch for bid=... - <path>.ips
...
Patching address 0x8007000 +0ab0f0 <= 1F 20 03 D5 len=4
Patching address 0x8007000 +0ab1b0 <= 1F 20 03 D5 len=4
...
```

### CODE REVIEW

**Comment by ReaperOfSouls1909** [comment]
[Ryujinx_2020-04-25_13-41-19.log](https://github.com/Ryujinx/Ryujinx/files/4533534/Ryujinx_2020-04-25_13-41-19.log)
[Smash_Ultimate_30FPS_.zip](https://github.com/Ryujinx/Ryujinx/files/4533535/Smash_Ultimate_30FPS_.zip)
[Boot_Straight_to_menu.zip](https://github.com/Ryujinx/Ryujinx/files/4533536/Boot_Straight_to_menu.zip)


crashes when loading both mods they were made for yuzu so not sure if it needs to be redone

**Comment by ReaperOfSouls1909** [comment]
Another fatal Error 
image when you don't make the nsopatches you get the issue in the log the folder needs to be created when the emulator is opened

**Comment by mageven** [comment]
Rebased to latest master.

> crashes when loading both mods they were made for yuzu so not sure if it needs to be redone

Hm, not sure what the problem is. The patching is working. Looks like we'll have to discuss with the mod authors on discord. Likely a difference in emulation.

> when you don't make the nsopatches you get the issue in the log the folder needs to be created when the emulator is opened

This is intended for now as the final location isn't decided. I wanted testers to know they are creating a directory for testing.

**Comment by ReaperOfSouls1909** [comment]
the final location should be where it is but patches should be like this titleid/Modname/ that way we don't get lost or have a huge mess also theboy181 made those mods message him on discord

**Comment by ReaperOfSouls1909** [comment]
```00:00:04.068 | Application Glib_UnhandledException: Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.OutOfMemoryException: Insufficient memory to continue the execution of the program.
   at System.Text.StringBuilder.ExpandByABlock(Int32 minBlockCharCount)
   at System.Text.StringBuilder.Append(Char* value, Int32 valueCount)
   at System.Text.StringBuilder.Append(Char[] value, Int32 startIndex, Int32 charCount)
   at System.IO.StreamReader.ReadLine()
   at Ryujinx.HLE.Loaders.ExePatchers.IPSwitchPatcher..ctor(StreamReader reader) in C:\projects\do-not-ask-for-support-in-ryujinx-server\Ryujinx.HLE\Loaders\ExePatchers\IPSwitchPatcher.cs:line 18
   at Ryujinx.HLE.Loaders.ExePatchers.PatchUtils.CollectNsoPatches(String dirPath, List`1 buildIds) in C:\projects\do-not-ask-for-support-in-ryujinx-server\Ryujinx.HLE\Loaders\ExePatchers\PatchUtils.cs:line 56
   at Ryujinx.HLE.HOS.Horizon.LoadExeFs(IFileSystem codeFs, Npdm& metaData) in C:\projects\do-not-ask-for-support-in-ryujinx-server\Ryujinx.HLE\HOS\Horizon.cs:line 626
   at Ryujinx.HLE.HOS.Horizon.LoadNca(Nca mainNca, Nca patchNca, Nca controlNca) in C:\projects\do-not-ask-for-support-in-ryujinx-server\Ryujinx.HLE\HOS\Horizon.cs:line 555
   at Ryujinx.HLE.HOS.Horizon.LoadNsp(String nspFile) in C:\projects\do-not-ask-for-support-in-ryujinx-server\Ryujinx.HLE\HOS\Horizon.cs:line 452
   at Ryujinx.HLE.Switch.LoadNsp(String nspFile) in C:\projects\do-not-ask-for-support-in-ryujinx-server\Ryujinx.HLE\Switch.cs:line 111
   at Ryujinx.Ui.MainWindow.LoadApplication(String path) in C:\projects\do-not-ask-for-support-in-ryujinx-server\Ryujinx\Ui\MainWindow.cs:line 391
   at Ryujinx.Ui.MainWindow.Row_Activated(Object sender, RowActivatedArgs args) in C:\projects\do-not-ask-for-support-in-ryujinx-server\Ryujinx\Ui\MainWindow.cs:line 708
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.Invoke(ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)

``` more testing using this mod here 
[Disable-Dynamic-Resoluiton.zip](https://github.com/Ryujinx/Ryujinx/files/4590048/Disable-Dynamic-Resoluiton.zip)
it's for lm3 it works on the switch

**Comment by mageven** [comment]
> the final location should be where it is but patches should be like this titleid/Modname/ that way we don't get lost or have a huge mess also theboy181 made those mods message him on discord

You can actually use that structure right now and it'll work because the system looks at all matching files in the root directory recursively. The filtering with build id's will automatically take care of picking the right patches. Will have a chat with theboy181 when I get some time.

<br/><br/>

> ```
>  ---> System.OutOfMemoryException: Insufficient memory to continue the execution of the program.
> <snip>
>```
> more testing using this mod here
> it's for lm3 it works on the switch

The zip you attached is malformed. It is a patch text file which is 6MB packed (which is itself a red flag) and it extracts to ~6.3GB (of mostly zeros). No wonder you got an OutOfMemoryException.

I'll look into implementing a bounded `ReadLine` later. Surprised .NET library doesn't provide one.

**Comment by mageven** [comment]
@ReaperOfSouls1909 Fixed the bug that was causing most errors. Most patches should start working now. The emulator will still crash with malformed 6GB patches though.

**Comment by mageven** [comment]
Closing this in favor of #1249 as the scope of modding has changed.

**Pull request closed without merging**
