### PR TITLE
Remove GTK

### PR DESCRIPTION
**Pull request by IsaacMarovitz**
Screenshot 2024-03-04 at 23 28 42

### CODE REVIEW

**Comment by piplup55** [comment]
Why remove gtk, i love gtk gtk is my life force on linux please think about keeping it and making it the default ui i beg it's all i have going for now please this pony mod

**Comment by Treetrain1** [comment]
Is there a reason to remove GTK support?

**Comment by SomeoneIsWorking** [comment]
> Is there a reason to remove GTK support?

I'm not a contributor but I think I can list two. 
Anyone feel free to correct me if I'm wrong with any of these.
- Issues with GTK (I mean on this project, not GTK in general) get swept under the rug with "Ava is going to replace GTK anyway"
- Everything being done has to be considered for both frameworks
- Everything has to be maintained for both frameworks

**Comment by sakuka47** [comment]
What are the advantages of keeping gtk? That's the real question.

**Comment by yavko** [comment]
> What are the advantages of keeping gtk? That's the real question.

Native Wayland support

**Comment by IsaacMarovitz** [comment]
> Native Wayland support

GTK does not support Wayland properly either.

**Comment by yavko** [comment]
> > Native Wayland support
> 
> GTK does not support Wayland properly either.

How does it not

**Comment by TSRBerry** [comment]
I told you before that these are things maintainers care about and you shouldn't waste your time on them. When we decide to remove GTK completely, we'll take care of that.

**Pull request closed without merging**
