### PR TITLE
ffmpeg: Attempt to fix RootPath on some linux distributions

### LINKED ISSUE #2284: ffmpeg cant find its libraries on PopOS 20.10
### What's the issue you encountered?

even after https://github.com/Ryujinx/Ryujinx/commit/1769510a280ab33cb7b31a1f3e17fdb09f5b87cf, ffmpeg crashes on popos 20.10 not being able to find its libraries in `/lib`
looking more into it, setting the ffmpeg.RootPath to `/usr/lib/x86_64-linux-gnu/` in the `/Ryujinx/Program.cs` file fixes the issue on PopOS
big thanks to @EmulationFanatic for testing on PopOS 20.10

### How can the issue be reproduced?

run any ryujinx version after 1.0.6857 on PopOS 20.10

### PR DESCRIPTION
**Pull request by AcK77**
This should fixes #2284 where the lib folder set in RootPath isn't the same between some linux distributions.
Since I don't use linux I can't really test it so feedbacks are really appreciate.

### CODE REVIEW

**Comment by Niwu34** [comment]
Bildschirmfoto von 2021-05-19 23-52-11
works :DD

**Comment by SeraUQ** [comment]
confirmed it fixes the ffmpeg issue on NixOS
great job in figuring it out :+1:

**Comment by edisionnano** [comment]
Can confirm it works on glorious Arch
ack

**Comment by EmulationFanatic** [comment]
Works great on Pop OS!

**Review by gdkchan — APPROVED** [review]
I'm not a fan of solutions that needs to spawn a process and parse its output as they are fragile and slow by nature, but I also don't know a better way to handle all the possible different paths where the user may have this installed on linux, so approving. I guess another possible solution would be just shiping FFMpeg ourselves for linux aswell.

**Comment by SeraUQ** [comment]
works as expected on NixOS in both cases of ffmpeg being installed in the system and not :ok_hand:

**Comment by narutorun-19** [comment]
It fixed the ffmpeg issue on Ubuntu 20.04. Thanks a lot~

**Review by Thog — APPROVED** [review]

**Pull request merged**
