### PR TITLE
Silence several build warnings

### PR DESCRIPTION
**Pull request by gdkchan**
Silences several warnings + minor code cleanup.

### CODE REVIEW

**Comment by jduncanator** [comment]
Personally, I'd prefer silencing CS0649 globally, rather than littering the code with pragma statements. We can just silence it in Release builds, so that it does not clutter build logs, whilst keeping the warnings in debug builds (in case they are useful to developers).

**Comment by gdkchan** [comment]
I think the warning is useful in some cases (for example, I just found that SubsamplingX/Y is never initialized thanks to them), so I think its valuable to keep them in some cases. I guess keeping them in debug only might be a good compromise.

**Comment by jduncanator** [comment]
So guessing we're not addressing my feedback then @AcK77? Thought the decision was to silence these globally in release mode?

**Comment by gdkchan** [comment]
Imo it was better to merge that as-is. I was just following what was already being done in other places (like the GPU project, introduced on #919). If we are going to just disable them globally, I think that would be better done as a separately anyway, since that also requires removing all pragmas that were already on the code.

**Pull request merged**
