### PR TITLE
Add Linux Unicorn patch + desc.

### PR DESCRIPTION
**Pull request by mgielda**
As per the Discord conversation, adding some info on compiling Unicorn with the necessary patch on Linux.

### CODE REVIEW

**Comment by jduncanator** [comment]
Hmmm... This raises some interesting points. I've never noticed that QEMU (and then by extension Unicorn and the .NET wrapper) are all GPLv2 licensed. We will likely have to remove the Unicorn-based tests, as GPL is not compatible with the MIT license (only the other way around).

**Comment by mgielda** [comment]
I am not a lawyer of course, but from my point of view you are using Unicorn only to test against, it is not delivering any of the Ryujinx features as you have a separate simulator. Of course separating the Unicorn tests out and potentially licensing them under GPL might be a good idea just to keep things clean. This stackexchange item:

https://opensource.stackexchange.com/questions/7503/implications-of-using-gpl-licenced-code-only-during-testing

seems to support this view.

So if keeping the Unicorn tests separate is something you are able to do without a bug overhead, it's probably a good idea.

**Comment by jduncanator** [comment]
> I am not a lawyer of course, but from my point of view you are using Unicorn only to test against, it is not delivering any of the Ryujinx features as you have a separate simulator. Of course separating the Unicorn tests out and potentially licensing them under GPL might be a good idea just to keep things clean. This stackexchange item:
> 
> https://opensource.stackexchange.com/questions/7503/implications-of-using-gpl-licenced-code-only-during-testing
> 
> seems to support this view.
> 
> So if keeping the Unicorn tests separate is something you are able to do without a big overhead, it's probably a good idea.

I agree with your point of view as well. The plan is to move the CPU JIT and it's tests out of the main Ryujinx project anyway, so I don't have any issues merging this as is for now, and addressing that in the future.

Thanks for your work!

**Review by Thog — APPROVED** [review]

**Review by AcK77 — APPROVED** [review]

**Review by gdkchan — APPROVED** [review]
lgtm, but we should probably try to upstream those changes.

**Pull request merged**
