### PR TITLE
GPU: Scale counter results before addition

### PR DESCRIPTION
**Pull request by riperiperi**
Counter results were being scaled on ReportCounter, which meant that the _total_ value of the counter was being scaled. Not only could this result in very large numbers and weird overflows if the game doesn't clear the counter, but it also caused the result to change drastically.

This PR changes scaling to be done when the value is added to the counter on the backend. This should evaluate the scale at the same time as before, on report counter, but avoiding the issue with scaling the total.

I've also included a fix for the 64-bit result partially being written. Drivers tend to write the low half first, then the high half. Now, we retry if the high half is 0xFFFFFFFF. This fixes counter results reading as 0 randomly (game was interpreting 0xFFFFFFFF00000000 as 32-bit uint), which turned into a very large value when rescaled, as the low half was no longer 0. This might fix some random chance issues with counter results. It would be nice to write the availability as a separate value _after_ the result copy, but I don't think any of our current counter results will be negative, so this should be fine for now.

Fixes scaling in WarioWare: Get It Together, at least in the demo, where it seems to compare old/new counters and broke down when scaling was enabled. Verified to still work in Splatoon 3 with scaling on/off in opengl/vulkan.

### CODE REVIEW

**Comment by GamerzHell9137** [comment]
Fixes Wreckfest upscaling too 
image

With the merge of this https://github.com/Ryujinx/Ryujinx/issues/4463 can be closed.

**Comment by gdkchan** [comment]
Doesn't it need to end the query and start a new one if the resolution scale of the render target changes, to divide the accumulated count by the correct scale?

**Comment by riperiperi** [comment]
Yes, but it didn't do that before.

**Review by gdkchan — APPROVED** [review]
Looks reasonable, but would be nice if it handled scale changes between render targets since its doing it on the backend now.

**Review by marysaka — APPROVED** [review]

**Pull request merged**
