### PR TITLE
Update Joy-Con Images

### PR DESCRIPTION
**Pull request by Ayato-Kirishima**
This updates the Joy-Con images to show the SL and SR buttons on the Joy-Con Pair configuration more clearly.

Before: 
Unbenant

After:unknown1

Single Joy Con:
Left:
Screenshot_20210201_033855

Right:
Screenshot_20210201_033923

### CODE REVIEW

**Comment by EmulationFanatic** [comment]
My personal preference would be to remove the side-view on the Joycon Pair image, since those buttons are not used nor mappable while Joycon Pair is the active controller type.

**Comment by Ayato-Kirishima** [comment]
> My personal preference would be to remove the side-view on the Joycon Pair image, since those buttons are not used nor mappable while Joycon Pair is the active controller type.

Tbh I left it in there for Aesthetic purposes but I’ll take what you said into account and will probably update it tomorrow if there isn’t any objections from others

**Comment by edisionnano** [comment]
I'd suggest that you use https://commons.wikimedia.org/wiki/File:Nintendo_Switch_Joy-Con_illustration.svg (with a slimmer font for the face buttons ABXY) since they are more distinguishable. For dual Joycon Pair you can use the top view above the Joycons.

**Comment by EmulationFanatic** [comment]
> I'd suggest that you use https://commons.wikimedia.org/wiki/File:Nintendo_Switch_Joy-Con_illustration.svg (with a slimmer font for the face buttons ABXY) since they are more distinguishable. For dual Joycon Pair you can use the top view above the Joycons.

If you do this, you'll need to credit the original illustrator and include a link to the Creative Commons Attribution-Share Alike 4.0 International license, also indicating if you made any changes.
https://creativecommons.org/licenses/by-sa/4.0/legalcode

**Comment by Ayato-Kirishima** [comment]
@EmulationFanatic @edisionnano I’ll see about what I want to do, personally I’d rather use a hand drawn one rather than a premade one but that’s just personal preference on my part, but I will be making some edits today!

**Review by Thog — APPROVED** [review]

**Comment by Ayato-Kirishima** [comment]
Will update it today and fix a lot of issues people had with the joycons and pro controller

**Comment by Ayato-Kirishima** [comment]
closing for now, will re-open with a new one Soon

**Pull request closed without merging**
