### PR TITLE
Fix french translation

### PR DESCRIPTION
**Pull request by PHILEC**
This PR is intended to improved the french localization as some part are not grammatically correct.
This work have been made regarding the current english localization, so it might appear the english need to be updated too if some information are wrong.

PS: This is my first PR in Github and in an OSS project so I am open to feedback :)

### CODE REVIEW

**Comment by agatemosu** [comment]
Use [crowdin](https://crowdin.com/project/ryujinx]

**Comment by PHILEC** [comment]
I have made my contribution on crowdin. Thank you for pointing this out to me.

It appear that the french translations need to be updated as some of the current ones are wrong in some places. And some entries are missing in the current master. Also some entries uses differents arguments to print than the english version.

What is the next step in order to benefits from the proposals currently avalaible on crowdin (including the ones I have made if some reviewers are ok with those) ? Is there anything that rely on me now ?
Do I need to delete this PR as it seems not relevant since I have made my contribution on crowdin ?

**Comment by sakuka47** [comment]
Hi, if you need help, I'm available, I'm Belgian

**Comment by jojodunet** [comment]
> I have made my contribution on crowdin. Thank you for pointing this out to me.
> 
> It appear that the french translations need to be updated as some of the current ones are wrong in some places. And some entries are missing in the current master. Also some entries uses differents arguments to print than the english version.
> 
> What is the next step in order to benefits from the proposals currently avalaible on crowdin (including the ones I have made if some reviewers are ok with those) ? Is there anything that rely on me now ? Do I need to delete this PR as it seems not relevant since I have made my contribution on crowdin ?

Maybe you could take cues from the recent update mentioned [here](https://github.com/Ryujinx/Ryujinx/pull/4758) to grasp the next step, ensuring that the corrections made in Crowdin are incorporated into the master build?

**Comment by jojodunet** [comment]
> I have made my contribution on crowdin. Thank you for pointing this out to me.
> 
> It appear that the french translations need to be updated as some of the current ones are wrong in some places. And some entries are missing in the current master. Also some entries uses differents arguments to print than the english version.
> 
> What is the next step in order to benefits from the proposals currently avalaible on crowdin (including the ones I have made if some reviewers are ok with those) ? Is there anything that rely on me now ? Do I need to delete this PR as it seems not relevant since I have made my contribution on crowdin ?

Perhaps you could draw inspiration from the previous update mentioned [here](https://github.com/Ryujinx/Ryujinx/pull/4758) to understand the next step, in order to ensure that the corrections made in Crowdin are integrated into the master build?

**Comment by PHILEC** [comment]
@sakuka47 & @jojodunet please review my translation https://crowdin.com/project/ryujinx 
You can use filter to view my translation and vote if you agree

**Comment by AcK77** [comment]
As suggested, translations have to be done through https://crowdin.com/project/ryujinx and it will be merge to master once large changes were done.
In that way I close this PR, thanks for your contribution.

**Pull request closed without merging**
