### PR TITLE
(TESTING) Vulkan + Threaded GAL

### PR DESCRIPTION
**Pull request by riperiperi**
**Combines PRs:**
Vulkan: https://github.com/Ryujinx/Ryujinx/pull/2518
Threaded GAL: https://github.com/Ryujinx/Ryujinx/pull/2501

Please see each PR for a full description.

### Testing
**_If you encounter a bug with this PR - PLEASE test it with the base Vulkan PR before reporting it!_**

### Benefits
- Greatly improved speed on average. Multiplier depends on game, generally not as fast as OGL but a good bit closer.
- `shaderc` invocations and `vkCreateShaderModule` now run in parallel, similar to parallel shader compilation on OpenGL.
  - This is very fast.
  - Pipeline compilation is not yet multithreaded.
  
Example of shader compilations with empty driver cache:
https://www.youtube.com/watch?v=8jJOu_trrkg

Reminder that this is still GLSL, and it's much faster than even the GLSL threaded compile on OpenGL.

With a driver cache, all you are paying for is shaderc invocations (GLSL -> SPIR-V), so stutters are much reduced on second run even without the ryu cache.

### CODE REVIEW

**Comment by george-ravelly** [comment]
When I start any game with Vulkan Ryujinx closes by itself, I tested it with openGL and it opened, I'm using Linux and my processor is an i5 3570 and my Gpu is the RX 550. log
[Ryujinx_1.0.0+1106e72_2021-07-31_15-08-13.log](https://github.com/Ryujinx/Ryujinx/files/6911666/Ryujinx_1.0.0%2B1106e72_2021-07-31_15-08-13.log)

**Comment by riperiperi** [comment]
You should probably post Vulkan related issues on the Vulkan PR, so that gdkchan can see them.

https://github.com/Ryujinx/Ryujinx/pull/2518

Your error boils down to `Unable to load shared library 'libX11-xcb' or one of its dependencies.`. Not sure what specifically it is, but it's probably a missing package.

**Comment by cow-killer** [comment]
Not sure if y'all are taking issues with NVIDIA or not, but on Linux there is absolutely *no* performance difference running this PR versus the vanilla Vulkan PR. Tested both Smash Ultimate and Skyward Sword.
[Ryujinx_1.0.0+7b12a00_2021-07-31_17-36-37.log](https://github.com/Ryujinx/Ryujinx/files/6912070/Ryujinx_1.0.0%2B7b12a00_2021-07-31_17-36-37.log)

**Comment by riperiperi** [comment]
Skyward Sword will barely be affected by this PR at all, as there is no GPU backend bottleneck. Not sure why smash ultimate wouldn't improve.

**Comment by sowrobbonik** [comment]
My pc spec is Intel core i3 processor and amd readon 570 8gb and 16 gb ddr4 ram iam getting flickering problem in monster hunter rise in vulkan and in opengl the game crash piz help me.

**Comment by riperiperi** [comment]
PR updated with GDK's latest fixes and improvements, including the fix to AMD vertex attributes that stops a lot of things from imploding. I'll post a comment here whenever it is updated.

Note that the SPIR-V backend does not gain anything from multithreading on NVIDIA yet, as pipeline compilation is not yet multithreaded. (if you do find yourself trying it out)

**Comment by EvilAleron** [comment]
> When I start any game with vulkan the ryujinx closes alone tested with openGL and opened normally, I'm using Linux and my processor is an i5 3570 and my GPU is the RX 550 log
> [Ryujinx_1.0.0+1106e72_2021-07-31_15-08-13.log](https://github.com/Ryujinx/Ryujinx/files/6911666/Ryujinx_1.0.0%2B1106e72_2021-07-31_15-08-13.log)

Same here, just crashing after trying to start a game.

**Comment by henridoxy** [comment]
When loading Age of Calamity with Vulkan on this PR, the ground does not render, on the base PR it did, but characters were stretching to its origin. Other objects render just fine. No problem with resolution scale either.
My specs:
Ryzen 5 1600 
Rx 570 4GB
16GB ram 2666mhz
image
image

**Comment by RinMaru** [comment]
> When loading Age of Calamity with Vulkan on this PR, the ground does not render, on the base PR it did, but characters were stretching to its origin. Other objects render just fine. No problem with resolution scale either.
> My specs:
> Ryzen 5 1600
> Rx 570 4GB
> 16GB ram 2666mhz
> image
> image

This is a issue with GCN GPUs even Yuzu has it. I have the same issue in BOTW, and AOC.
RX 480 4GB, 5600x, 20GB DDR4

**Comment by skrevenge** [comment]
Marvel ultimate alliance 3 still with glitches, but it's a little bit if compared to only vulkan PR. 
But the game is crashing in the beginning of the green goblin stage
AMD Ryzen 2300 with Vega 8
8GB RAM(6 usable)


[Uploading Ryujinx_1.0.0+9d7fa61_2021-08-04_23-15-04.log…]()

**Comment by farendaibiao** [comment]
May I leave a message? Thank you for your wonderful project that makes AMD apu simulate NS games by Vulkan!
Here I wonder if FIFO would be low without always being 100% such that the game "mhr" almost be 10fps with the AMD apu?
image
I am very grateful for you!

**Comment by farendaibiao** [comment]
> This will gradually improve as time goes on. The FIFO% number is an indicator of both time spent in the host graphics backend (Vulkan), and processing the guest GPU command queue (shared). One known improvement for this game is the HLE macros PR, which is on the gpu emulation side of things rather than the backend. The Vulkan backend itself is currently a bit slower than OGL, though this is going to improve.
> 
> Note that here the CPU is the main limiting factor, as it is the primary driver of both of these things.

Thank you for your explain!

**Comment by codbugpatrol** [comment]
Not sure if it happens with everyone, but I got my save and then tried to run the first scenario in Hyrule Warriors AoC and man, it took ages to load. I've just thought that it had crashed, but no. It seems these were PPTC, but why it did not create at the start ?

image

After a long time:

image

**Comment by codbugpatrol** [comment]
> Not sure if it happens with everyone, but I got my save and then tried to run the first scenario in Hyrule Warriors AoC and man, it took ages to load. I've just thought that it had crashed, but no. It seems these were PPTC, but why it did not create at the start ?
> 
> image
> 
> After a long time:
> 
> image

Hyrule Warriors AoC runs great while in game, but the loading times not. I've exit the scenario and enter again. The loading time was the same, a big and long load time. 

HW Aoc do not run good in OpenGL, it have huge frame drops, sometimes it did not even playable anymore, but loads are great. In this PR, is the opposite. 

Not complaining thou, I've know is evolving and just want to help here.

**Comment by LennardF1989** [comment]
Tested both #2518 and this one, but MHR flickers in the main screen, faces are black when loading profile. In-game everything seems to render fine, but overal performance is 15-20 FPS slower than OpenGL (20-30FPS range usually) on either version (even when threaded GAL is forced on). Playing in docked mode, VSync off.

CPU: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz ; 8 logical
GPU: NVIDIA GeForce GTX 1060 6GB (Vulkan v1.2.175, Driver v471.41.0.0)
RAM: Total 16259 MB

**Comment by eskimododo** [comment]
Tested #2518 and #2520 on MHR (as it was the most demanding game), noted that #2520 yielded better fps results and playability when compared to just #2518. Artifacting and flickering textures do happen as well, and character faces are all black. MHR performs extremely badly with mainline (ie, 1-5fps in intro), and does not even boot on LDN2.3..

#2518: ~5-8fps in village, barely could play and make it to a quest
#2520: ~10-15fps in village, choppy but could still navigate the village and make it out to a quest. Questing ranges from 15fps to 20fps depending on the amount of visuals and draw range on screen.

CPU: Ryzen 5 2400G @ 3.6Ghz, 4C8T, no PBO
GPU: Vega 11 iGPU @ 1240mhz with 2Gb vram set in bios, no O/C applied to iGPU (when iGPU was OC, MHR wont even start). latest Adrenalin 21.7.2 drivers.
Ram: 16Gb total

Also tested Dynasty Warriors 8 on #2520 vs mainline, #2520 yielded playable fps of about 30, while mainline yielded about 15fps.. the only issue is that #2520 causes enemies to be missing or drawn as long lines into the void on second missions..

**Comment by fabiograssiotto** [comment]
Tested #2520 with Reshade 4.9.1 on Vulkan.

Got a crash with Zelda SS right on the file selection menu. Disabling reshade solves the problem.

Reshade logs for reference:
[ReShade64.log](https://github.com/Ryujinx/Ryujinx/files/6986271/ReShade64.log)

Ryujinx with Reshade (crashes when selecting the file, back to OS):
[Ryujinx_1.0.0+3a175b9_2021-08-14_07-04-24.log](https://github.com/Ryujinx/Ryujinx/files/6986273/Ryujinx_1.0.0%2B3a175b9_2021-08-14_07-04-24.log)

Ryujinx without Reshade (no crash, in game):
[Ryujinx_1.0.0+3a175b9_2021-08-14_07-11-59.log](https://github.com/Ryujinx/Ryujinx/files/6986277/Ryujinx_1.0.0%2B3a175b9_2021-08-14_07-11-59.log)

CPU: i7 10700
GPU: GTX 1070
Ram: 16Gb total

00:00:00.917 |N| Application LoadApplication: Using Firmware Version: 12.1.0
00:00:05.419 |N| GUI.RenderLoop Gpu PrintGpuInformation: NVIDIA NVIDIA GeForce GTX 1070 (Vulkan v1.2.175, Driver v471.68.0.0)
00:00:24.343 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorDeviceLost".
   at Ryujinx.Graphics.Vulkan.FenceHelper.WaitAllIndefinitely(Vk api, Device device, ReadOnlySpan`1 fences)
   at Ryujinx.Graphics.Vulkan.FenceHolder.Wait()
   at Ryujinx.Graphics.Vulkan.CommandBufferPool.WaitAndDecrementRef(Int32 cbIndex, Boolean refreshFence)
   at Ryujinx.Graphics.Vulkan.CommandBufferPool.Rent()
   at Ryujinx.Graphics.Vulkan.PipelineFull.FlushCommandsImpl(String caller)
   at Ryujinx.Graphics.Vulkan.Window.Present(ITexture texture, ImageCrop crop, Action swapBuffersCallback)
   at Ryujinx.Graphics.GAL.Multithreading.Commands.Window.WindowPresentCommand.Run(WindowPresentCommand& command, ThreadedRenderer threaded, IRenderer renderer)
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__4_31(Span`1 memory, ThreadedRenderer threaded, IRenderer renderer)
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
00:00:24.343 |E| HLE.GuestThread.18 Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorDeviceLost".
   at Ryujinx.Graphics.Vulkan.FenceHelper.WaitAllIndefinitely(Vk api, Device device, ReadOnlySpan`1 fences)
   at Ryujinx.Graphics.Vulkan.FenceHolder.Wait()
   at Ryujinx.Graphics.Vulkan.CommandBufferPool.WaitAndDecrementRef(Int32 cbIndex, Boolean refreshFence)
   at Ryujinx.Graphics.Vulkan.CommandBufferPool.Dispose()
   at Ryujinx.Graphics.Vulkan.TextureView.CopyTo(ITexture destination, Extents2D srcRegion, Extents2D dstRegion, Boolean linearFilter)
   at Ryujinx.Graphics.Gpu.Image.Texture.GetScaledHostTexture(Single scale, ITexture storage)
   at Ryujinx.Graphics.Gpu.Image.Texture.<ExternalFlush>b__105_0()
   at Ryujinx.Graphics.Gpu.Image.TextureGroup.FlushAction(TextureGroupHandle handle, UInt64 address, UInt64 size)
   at Ryujinx.Memory.Tracking.RegionHandle.Signal(UInt64 address, UInt64 size, Boolean write, IList`1& handleIterable)
   at Ryujinx.Memory.Tracking.VirtualRegion.Signal(UInt64 address, UInt64 size, Boolean write)
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write)
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address)
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by sowrobbonik** [comment]
Hmm iam getting this same problem on Amd readon rx570,intel Core i 3, 16gb
ram.In vulkan mhr2 start but screen got flickering.In opengl The game
doesn't start.

**Comment by sowrobbonik** [comment]
Hmm iam facing the same problem

**Comment by sowrobbonik** [comment]
You can delete all shader and try again if you want you can disable
Shader cache then reply

**Comment by henridoxy** [comment]
Astral Chain: white bloom covering a good portion of the screen
Specs: Ryzen 5 1600 - 16GB DDR4 - RX 570
image

[Ryujinx_1.0.0+3a175b9_2021-08-17_23-01-34.log](https://github.com/Ryujinx/Ryujinx/files/7004002/Ryujinx_1.0.0%2B3a175b9_2021-08-17_23-01-34.log)

**Comment by miyukikame** [comment]
> 
> 
> Astral Chain: white bloom covering a good portion of the screen
> Specs: Ryzen 5 1600 - 16GB DDR4 - RX 570
> image
> 
> [Ryujinx_1.0.0+3a175b9_2021-08-17_23-01-34.log](https://github.com/Ryujinx/Ryujinx/files/7004002/Ryujinx_1.0.0%2B3a175b9_2021-08-17_23-01-34.log)

Quote from the PR author:
> If you encounter a bug with this PR - PLEASE test it with the base Vulkan PR before reporting it!

This is a Vulkan specific bug not because of Threaded GAL

**Comment by henridoxy** [comment]
> > Astral Chain: white bloom covering a good portion of the screen
> Quote from the PR author:
> 
> > If you encounter a bug with this PR - PLEASE test it with the base Vulkan PR before reporting it!
> 
> This is a Vulkan specific bug not because of Threaded GAL

> I'm so sorry, I used the wrong pull, thank you

**Comment by ExE-Boss** [comment]
Now that <https://github.com/Ryujinx/Ryujinx/pull/2501> has been merged, this PR won’t be necessary once <https://github.com/Ryujinx/Ryujinx/pull/2518> is rebased.

**Comment by riperiperi** [comment]
> 
> 
> Now that #2501 has been merged, this PR won’t be necessary once #2518 is rebased.

Yes, though I'm not closing it until that PR is rebased.

**Comment by Lukas1860** [comment]
So I have a amd graphic card so opengl wont work out for me. I wanna play with my friends but i need to use this beta vulkan stuff otherwise theres blackscreen and i cannot start any game. So am I able to have both: Multiplayer and vulkan? I already tried some copy pasting but it didnt work pls help :)

**Comment by MutantAura** [comment]
LDN will be updated when Vulkan is fully complete and merged into the main build. LDN source code is not open source yet and so non-devs cannot merge anything. Copying and pasting is not how this works. It needs lots more specialist work for things to be merged together, adjustments must be made before building.

You'll need to be patient for the time being.

**Comment by riperiperi** [comment]
All parts of this PR are now available in the main PR over at #2518.

**Pull request closed without merging**
