### PR TITLE
Implement VRSRA, VRSHRN, VQSHRUN, VQMOVN, VQMOVUN, VQADD, VQSUB, VRHADD, VPADDL, VSUBL, VQDMULH and VMLAL Arm32 NEON instructions

### LINKED ISSUE #1811: Unimplemented vqmovun.s16 instruction
### What CPU instruction is missing?

vqmovun

```
The instruction at 0x00000000002ebaac (opcode 0xf3b20244) is undefined!
The instruction at 0x00000000005a44a0 (opcode 0xf3f22264) is undefined!
```

### Instruction name
```
vqmovun.s16 d0, q2
vqmovun.s16 d18, q10
```

### Required by: 

https://github.com/Ryujinx/Ryujinx-Games-List/issues/3506
https://github.com/Ryujinx/Ryujinx-Games-List/issues/2998
https://github.com/Ryujinx/Ryujinx-Games-List/issues/1951
https://github.com/Ryujinx/Ryujinx-Games-List/issues/1943

### PR DESCRIPTION
**Pull request by gdkchan**
This implements the instructions listed on the title, and fixes the encoding of some existing instructions that were a bit too permissive, when it should decode as "Undefined" instruction.

I modified the MRC/MCR implementation a little bit. I improved the exception messages by not including so many redundant 0s and including the actual instruction value, which is useful for debugging. Additionally, for invalid Opc1 values, it will emit a Undefined instruction rather than throwing at emit stage. This was required because on Star Wars Republic Commando, it seems that it was decoding data as if it was code, and throwing an exception early preventing the game from progressing.

Allows Dies irae -Amantes amentes- for Nintendo Switch to go ingame, it's playable as far I can tell.
image
image
image
(This game seems to use them due to a vectorized WEBP decoder or something like that).

Might also benefit other 32-bit games that uses those instructions, of course. Testing is welcome.

Fixes #1811.

### CODE REVIEW

**Comment by EmulationFanatic** [comment]
Resolves https://github.com/Ryujinx/Ryujinx/issues/1811?

**Comment by EmulationFanatic** [comment]
Baldur's Gate seems to be working fine (though the intro stutters quite a bit):
image

**Comment by EmulationFanatic** [comment]
Icewind Dale is also running fine.
image

**Comment by EmulationFanatic** [comment]
The latest commit fixes Star Wars: Republic Commando
image

**Review by riperiperi — APPROVED** [review]
LGTM, thanks for getting to these.

**Pull request merged**
