### PR TITLE
Load default config when an invalid config is found

### PR DESCRIPTION
**Pull request by Xpl0itR**
I've also changed the code that write the config to disk to use the `FileOptions.WriteThrough` flag to write to disk immediately to decrease the chances of corruption

### CODE REVIEW

**Comment by Xpl0itR** [comment]
> I also think it needs a very obvious log message indicating that the default config was used and not the users config, as I imagine people will pull their hair out if the emulator just blindly uses a different config file than the one they're expecting, and can't figure out why.

Added a log message
> I think in the case that the config file doesn't exist, or it can't be loaded, the default one should only be used temporarily, and should not overwrite the users existing config file.

I've changed my code so that after loading the default config, it is not saved on disk straight away. However it is still possible for users to trigger the config to be saved on disk by modifying and saving it in the GUI.

**Comment by Xpl0itR** [comment]
Rebased and partially rewritten

**Comment by Thog** [comment]
This is still needed today, could be nice to rebase @Xpl0itR

**Comment by Xpl0itR** [comment]
Rebased

**Review by riperiperi — APPROVED** [review]
LGTM.

**Comment by Thog** [comment]
Need a final rebase but lgtm

**Review by Thog — APPROVED** [review]

**Comment by Xpl0itR** [comment]
@Thog rebased again

**Review by AcK77 — APPROVED** [review]

**Pull request merged**
