### PR TITLE
Add supported languages to UI

### PR DESCRIPTION
**Pull request by liamharper2453**
Hi,

First contribution here.

I thought it would be useful if supported languages for games was visible in the UI so I have added that as part of this PR.

image

Background on this is #3287 where the user most likely selected Spanish instead of Latin American Spanish and because Spanish was unsupported the game defaulted back to English.

Sometimes the language shown in-game can be misleading to what is actually needed i.e. in Sword Art Online the select language screen specifies Canadian French. However, it is actually only specifically French that is supported.

### CODE REVIEW

**Comment by gdkchan** [comment]
Would be better if the bug fix and the UI changes were separate PRs imo.

**Comment by liamharper2453** [comment]
> Would be better if the bug fix and the UI changes were separate PRs imo.

It turns out the bug fix wasn't needed. In that issue raised I think they just selected Spanish instead of Latin American Spanish which the game supports. So taken that out. This is now a UI only change and hopefully this work will make distinctions like that clearer and prevent confusion about that in the future.

**Comment by gdkchan** [comment]
I was starting to wonder what exactly you fixed since `(x & (1 << y)) != (1 << y)` is the same as `(x & (1 << y)) == 0` (since only one bit is set, the result can only be either that bit or 0).

The way to fix this might be better language selection priority (like if Spanish is not available, it can prefer Latin American Spanish rather than English). Something like that would also address #3232, but it requires checking what the service does as we don't want to differ from the console here.

**Comment by liamharper2453** [comment]
> I was starting to wonder what exactly you fixed since `(x & (1 << y)) != (1 << y)` is the same as `(x & (1 << y)) == 0` (since only one bit is set, the result can only be either that bit or 0).
> 
> The way to fix this might be better language selection priority (like if Spanish is not available, it can prefer Latin American Spanish rather than English). Something like that would also address #3232, but it requires checking what the service does as we don't want to differ from the console here.

Yeah that's why I did undid it as I realised it was the same thing. When I was investigating I also got thrown off by the latin spanish/spanish difference and was trying to fix something that wasn't even an issue!

Good shout on language priorities.

**Comment by MarkLanders777** [comment]
> > I was starting to wonder what exactly you fixed since `(x & (1 << y)) != (1 << y)` is the same as `(x & (1 << y)) == 0` (since only one bit is set, the result can only be either that bit or 0).
> > The way to fix this might be better language selection priority (like if Spanish is not available, it can prefer Latin American Spanish rather than English). Something like that would also address #3232, but it requires checking what the service does as we don't want to differ from the console here.
> 
> Yeah that's why I did undid it as I realised it was the same thing. When I was investigating I also got thrown off by the latin spanish/spanish difference and was trying to fix something that wasn't even an issue!
> 
> Good shout on language priorities.

True, Latin American Spanish doesn't work if you select Spanish, Xenoblade 2 works selecting just Spanish and not Latin American but in real hardware does work

**Comment by Thog** [comment]
Need a rebase

**Comment by marysaka** [comment]
Closing as stale.

**Pull request closed without merging**
