### PR TITLE
CPU (A64): Add Fmaxp & Fminp Scalar Inst.s, Fast & Slow Paths; with Tests.

### PR DESCRIPTION
**Pull request by LDj3SNuD**
Contributes to https://github.com/Ryujinx/Ryujinx-Games-List/issues/2828.

Now the game eventually progresses but would then seem to crash due to a problem with the `SuatomB` shader instruction:
```
00:02:11.443 |E| GPU.MainThread Application : Unhandled exception caught: System.NullReferenceException: Object reference not set to an instance of an object.
   at Ryujinx.Graphics.Shader.Translation.EmitterContextInsts.Copy(EmitterContext context, Operand d, Operand a) in \src\Ryujinx.Graphics.Shader\Translation\EmitterContextInsts.cs:line 217
   at Ryujinx.Graphics.Shader.Instructions.InstEmit.EmitSuatom(EmitterContext context, SuDim dimensions, SuatomOp atomicOp, SuatomSize size, Int32 imm, Int32 srcA, Int32 srcB, Int32 srcC, Int32 dest, Boolean byteAddress, Boolean isBindless, Boolean compareAndSwap) in \src\Ryujinx.Graphics.Shader\Instructions\InstEmitSurface.cs:line 290
   at Ryujinx.Graphics.Shader.Instructions.InstEmit.SuatomB(EmitterContext context) in \src\Ryujinx.Graphics.Shader\Instructions\InstEmitSurface.cs:line 18
```

Nop-ing the instruction, the game goes ingame:
image

### CODE REVIEW

**Review by riperiperi — APPROVED** [review]
LGTM, nice work!

**Comment by gdkchan** [comment]
> Now the game eventually progresses but would then seem to crash due to a problem with the SuatomB shader instruction:

Can you check if:
```cs
if (d != null)
{
    context.Copy(d, res);
}
```
Fixes the issue? If so, please submit a separate PR with this fix. Also `EmitSuld` needs a similar fix. 
Just doing `Operand d = Register(dest, RegisterType.Gpr);` directly should also work since we have a special case on the copy method to ignore constant dests.

**Review by gdkchan — APPROVED** [review]
lgtm, thanks!

**Comment by gdkchan** [comment]
No need for PPTC version increment?

**Comment by LDj3SNuD** [comment]
you are right, I will correct as soon as I can

**Comment by LDj3SNuD** [comment]
Done.

**Pull request merged**
