### PR TITLE
update zh_CN.json

### PR DESCRIPTION
**Pull request by tldzyx**
- add shortcut for menu refer to "zh_TW.json"
  - "MenuBarFile": "文件(_F)"
  - "MenuBarFileOpenFromFile": "加载游戏文件(_L)"
  - "MenuBarFileOpenUnpacked": "加载解包后的游戏(_U)"
  - "MenuBarFileExit": "退出(_E)"
  - "MenuBarOptions": "选项(_O)"
  - "MenuBarOptionsSettings": "设置(_S)"
  - "MenuBarOptionsManageUserProfiles": "管理用户账户(_M)"
  - "MenuBarActions": "操作(_A)"
  - "MenuBarTools": "工具(_T)"
  - "MenuBarHelp": "帮助(_H)"
- translate with [Crowdin](https://crwd.in/ryujinx)
  - "MenuBarView": "视图(_V)"
  - "MenuBarViewWindow": "窗口大小"
  - "MenuBarViewWindow720": "720p"
  - "MenuBarViewWindow1080": "1080p"
  - "SettingsTabGeneralRememberWindowState": "记住窗口大小/位置"

### CODE REVIEW

**Comment by gdkchan** [comment]
Why was that not updated using Crowdin?

**Comment by wzsx150** [comment]
> * add shortcut for menu refer to "zh_TW.json"
>   
>   * "MenuBarFile": "文件(_F)"
>   * "MenuBarFileOpenFromFile": "加载游戏文件(_L)"
>   * "MenuBarFileOpenUnpacked": "加载解包后的游戏(_U)"
>   * "MenuBarFileExit": "退出(_E)"
>   * "MenuBarOptions": "选项(_O)"
>   * "MenuBarOptionsSettings": "设置(_S)"
>   * "MenuBarOptionsManageUserProfiles": "管理用户账户(_M)"
>   * "MenuBarActions": "操作(_A)"
>   * "MenuBarTools": "工具(_T)"
>   * "MenuBarHelp": "帮助(_H)"
> * translate with [Crowdin](https://crwd.in/ryujinx)
>   
>   * "MenuBarView": "视图(_V)"
>   * "MenuBarViewWindow": "窗口大小"
>   * "MenuBarViewWindow720": "720p"
>   * "MenuBarViewWindow1080": "1080p"
>   * "SettingsTabGeneralRememberWindowState": "记住窗口大小/位置"

I have already made the necessary changes on Crowdin. You can close this PR now.
大佬，我已经在Crowdin修改好了，可以关闭这个PR了。

**Comment by tldzyx** [comment]
> Why was that not updated using Crowdin?

I submit at Crowdin too, I don't know well about Crowdin workflow, and I build on my fork for myself, it's well done, so I submit this PR just for share, if I found this PR isn't necessary at sometime, I will close it.

**Comment by tldzyx** [comment]
> > * add shortcut for menu refer to "zh_TW.json"
> >   
> >   * "MenuBarFile": "文件(_F)"
> >   * "MenuBarFileOpenFromFile": "加载游戏文件(_L)"
> >   * "MenuBarFileOpenUnpacked": "加载解包后的游戏(_U)"
> >   * "MenuBarFileExit": "退出(_E)"
> >   * "MenuBarOptions": "选项(_O)"
> >   * "MenuBarOptionsSettings": "设置(_S)"
> >   * "MenuBarOptionsManageUserProfiles": "管理用户账户(_M)"
> >   * "MenuBarActions": "操作(_A)"
> >   * "MenuBarTools": "工具(_T)"
> >   * "MenuBarHelp": "帮助(_H)"
> > * translate with [Crowdin](https://crwd.in/ryujinx)
> >   
> >   * "MenuBarView": "视图(_V)"
> >   * "MenuBarViewWindow": "窗口大小"
> >   * "MenuBarViewWindow720": "720p"
> >   * "MenuBarViewWindow1080": "1080p"
> >   * "SettingsTabGeneralRememberWindowState": "记住窗口大小/位置"
> 
> I have already made the necessary changes on Crowdin. You can close this PR now. 大佬，我已经在Crowdin修改好了，可以关闭这个PR了。

if I found this PR isn't necessary at sometime, I will close it. maybe at next release
当我发现不再需要这个PR的时候, 我会关闭它. 也许就在下次发布之后

**Comment by AcK77** [comment]
You should do change using https://crowdin.com/project/ryujinx and not opening a PR for that.
Thanks!

**Pull request closed without merging**
