### PR TITLE
Fixing graphical issues in Ryujinx's Discord implementation

### PR DESCRIPTION
**Pull request by CoolBeansStudioOfficial**
(Addressing Issue #4916)
The Ryujinx logo is now grabbed from the official GitHub page which fixes the visuals. I believe introducing this dependency is appropriate because in the circumstance that the GitHub page was forced to be taken down, so would the Discord client currently hosting the broken image.

The old implementation using the assets uploaded to Discord
Screenshot (14)

The new implementation using assets from the official Ryujinx GitHub page
Screenshot (13)

I love feedback on improvement, so if there are any problems let me know. Thanks for reviewing my first contribution!

### CODE REVIEW

**Comment by CoolBeansStudioOfficial** [comment]
The old implementation using the assets uploaded to Discord
Screenshot (14)

The new implementation using assets from the official Ryujinx GitHub page
Screenshot (13)

**Comment by IsaacMarovitz** [comment]
Would a better solution here not just be updating the assets uploaded to Discord...

**Comment by CoolBeansStudioOfficial** [comment]
Technically yes, but the owner hasn't gotten around to it so far and its not looking like they will anytime soon. This would allow the issue to be fixed immediately and if the owner eventually does then it can always be changed.

**Comment by TSRBerry** [comment]
I'll do the change in a few days, thank you for bringing it up! I'll prefer to do it using the uploaded assets for now.

**Comment by CoolBeansStudioOfficial** [comment]
Should I close the request?

**Comment by CoolBeansStudioOfficial** [comment]
ok. Here's the image I used: [Image](https://avatars.githubusercontent.com/u/39036280?s=274&v=4)

**Comment by TSRBerry** [comment]
@CoolBeansStudioOfficial thank you for making me aware of this! :D

**Pull request closed without merging**
