### PR TITLE
Seeing if there are any other spelling errors to correct.

### PR DESCRIPTION
**Pull request by Mou-Ikkai**

### CODE REVIEW

**Comment by Mou-Ikkai** [comment]
Tell me if you want the Appveyor dialogue to be changed to something else. I see many people thinking this is an issue on their half, so I thought the dialogue could try to tell them what the main cause usually is.

**Comment by Mou-Ikkai** [comment]
Ah, broke something XD

**Review by gdkchan — APPROVED** [review]
Looks fine.

**Review by Thog — APPROVED** [review]

**Comment by Mou-Ikkai** [comment]
This can be committed, I couldn't find any other issues with the GUI text in the files.

**Pull request merged**
