### PR TITLE
Implement Arm32 Sha256 and MRS Rd, CPSR instructions

### LINKED ISSUE #3546: Mario Kart 8 Deluxe Wave 2 DLC Fails to Boot
## Bug Report

Update 2.1.0 with 2 new cups/ 8 tracks fails to boot in Ryujinx

### What's the issue you encountered?

Mario Kart 8 Deluxe 2.1.0 update fails to boot

### How can the issue be reproduced?

Add update 2.1.0 in title management. 

### Log file

00:00:18.128 |E| HLE.GuestThread.24 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.UndefinedInstructionException: The instruction at 0x0000000001614ba0 (opcode 0xf3140c6e) is undefined!

at Ryujinx.HLE.HOS.Kernel.Process.KProcess.UndefinedInstructionHandler(IExecutionContext context, UInt64 address, Int32 opCode) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Process\KProcess.cs:line 1105

at Ryujinx.Cpu.Jit.JitExecutionContext.UndefinedHandler(ExecutionContext context, UInt64 address, Int32 opCode) in D:\a\Ryujinx\Ryujinx\Ryujinx.Cpu\Jit\JitExecutionContext.cs:line 104

at ARMeilleure.State.ExecutionContext.OnUndefined(UInt64 address, Int32 opCode) in D:\a\Ryujinx\Ryujinx\ARMeilleure\State\ExecutionContext.cs:line 135

at ARMeilleure.Instructions.NativeInterface.Undefined(UInt64 address, Int32 opCode) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 61

at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Translation\Translator.cs:line 168

at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 32

at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 40

at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1265

### Environment?

Ryujinx 1.1.198
Windows 11
i7-9700k
32 MBs RAM
Nvidia 2070 Super
Samsung 970 Pro NVMe

### Additional context?

This game played great with update 2.0.0 & associated Booster Pack DLC which introduced the first 2 new cups / 8 tracks.

### PR DESCRIPTION
**Pull request by gdkchan**
Ported those instructions from the Arm64 implementation, those are required by Mario Kart 8 Deluxe with update 2.1.0.

I added tests for SHA256, but unfortunately Unicorn does not support those instructions on Arm32, so I had to run the Arm64 tests, and copy the inputs and outputs and use those to validate the Arm32 test results. It would be better if Unicorn supported the instructions.

Fixes #3546.

### CODE REVIEW

**Comment by Haronee** [comment]
Mario Kart 8 Deluxe with update 2.1.0 now boots and runs fine, good job!

image
image
image


(Thanks @MutantAura for the last screenshot)

**Comment by sakuka47** [comment]
You can run new track?

**Comment by remutro** [comment]
> You can run new track?

This definitely allows it to boot, but Ryujinx asks me to run some unknown update and restart and I get stuck in this loop. New tracks remain inaccessible, while older ones run OK.

**Comment by MutantAura** [comment]
> This definitely allows it to boot, but Ryujinx asks me to run some unknown update and restart and I get stuck in this loop. New tracks remain inaccessible, while older ones run OK.

New DLC needs to be redumped for the new tracks to work.

**Comment by sakuka47** [comment]
I rebump  my dlc booster ? Oki i get it,  thank for it 😀

**Review by riperiperi — APPROVED** [review]
LGTM, very fast response. 😎

**Comment by Megaloma** [comment]
I've redumped my booster pass (remove and add back again, right?) and it says I need to restart. 



After that, the next image pops up if I hit restart.

**Comment by Megaloma** [comment]
Doesnt seem the images are working, for me at least. The first part says "An update to the downloadable content is required. Please restart the software and perform a software update. If you restart the software, any unsaved data will be lost."
The top bar says "Error CodeL 2162-0101".

Once I press "Restart", it says "Details: 2162-0101" in the top bar and the window is blank, besides the pressable "OK."

**Comment by Megaloma** [comment]
(Just to clarify, the base-game works fine, but the booster pass fails to load. It tells me I gotta buy the pass.)

**Comment by gdkchan** [comment]
You need to wait for the image upload to complete before clicking on the post button..

**Review by Thog — APPROVED** [review]

**Comment by Megaloma** [comment]
Gotcha, thank yall.
And sorry lmao, I made a github acc just to ask this question

**Pull request merged**
