### PR TITLE
Replace Segoe Fluent Icons font with newer Fluent System Icons font

### PR DESCRIPTION
**Pull request by SamusAranX**
Mainly, this resolves a [license issue around the old font](https://learn.microsoft.com/en-us/windows/apps/design/style/segoe-fluent-icons-font#how-do-i-get-this-font), which was pulled into the project for one single icon. The new font was taken from this specific release of Microsoft's Fluent System Icons repository, with uses the MIT license: https://github.com/microsoft/fluentui-system-icons/releases/tag/1.1.232

I wasn't sure where to put the supporting xaml/cs files for the icon font, so I kept them in Assets/Fonts.

The way I implemented font icons differs from the way FluentAvalonia does it. 
They use a [big enum with integer codepoints](https://github.com/amwx/FluentAvalonia/blob/master/src/FluentAvalonia/UI/Controls/IconElement/Symbol.cs), I used a class with string constants that can be directly referenced in either code or XAML, along with a ResourceDictionary that holds a `FontIconSource` for every used icon. Their way requires an ugly workaround involving `char.ConvertFromUtf32()` to get the actual character, which makes no sense for an icon font, imo.
I generated the class containing all of the string constants with a script I wrote for that purpose: https://git.emmalyx.dev/emma/fontutils#iconfontglyphspy
There are probably other ways to do it, but this seemed sensible at the time. More importantly, this could easily be used to generate a proper icon overview for the new font, something Microsoft neglected to do.

I replaced all of the icons in the settings window sidebar with icons from the new icon font and increased the icon size from 16 to 20 points by overriding a value from that control in the settings window. This is *technically* a hack, but one without risk of fundamentally breaking the program if the underlying control ever changes in FluentAvalonia.
I also set the font antialiasing technique to grayscale to make the icons less blurry and enabled UseLayoutRounding on that window to make sure icons don't become blurry on weird DPI scale levels. Both of these are set at the window level, but they come with zero downsides.

The new icon font has all of the glyphs that were used before, with the exception of the "Memory" icon that I picked a different, more CPU-like replacement for.
The only real user-facing change in this PR is the new icon for the CPU section.

Here are before/after screenshots:

before after

### CODE REVIEW

**Comment by gdkchan** [comment]
The new font file seems much larger than the old one, almost a 1 MB difference. Not sure if that is a big deal, but it's something to take into account.

**Comment by TSRBerry** [comment]
Could we add the license for it to `distribution/legal/THIRDPARTY.md` as well?

**Comment by gdkchan** [comment]
> Could we add the license for it to `distribution/legal/THIRDPARTY.md` as well?

I wonder if its possible to split this file per project if this is done, since Headless does not use this font at all, so it's not necessary to include this license with headless builds. I guess this is already the case with `ShellLink`.

**Comment by TSRBerry** [comment]
> > Could we add the license for it to `distribution/legal/THIRDPARTY.md` as well?
> 
> I wonder if its possible to split this file per project if this is done, since Headless does not use this font at all, so it's not necessary to include this license with headless builds. I guess this is already the case with `ShellLink`.

Sounds like something we should do. Let me think about how we could do that.

**Review by TSRBerry — APPROVED** [review]
Make sure to add the license to `THIRDPARTY.md`, but otherwise lgtm!

**Comment by SamusAranX** [comment]
Done!

**Review by IsaacMarovitz — APPROVED** [review]

**Comment by SamusAranX** [comment]
Since Microsoft couldn't be bothered to make a preview page for their fancy glyph font, I made one myself: https://projects.emmalyx.dev/glyphpreview/

It's only provisionally hosted on my server for now, it should probably be copied over to a resource controlled by this project. If the font file is ever updated, the list HTML can easily be regenerated with the script mentioned in the initial post: https://git.emmalyx.dev/emma/fontutils#iconfontglyphspy

**Review by GamerzHell9137 — APPROVED** [review]

**Pull request closed without merging**
