### PR TITLE
JIT Cache Exhausted Temporary Fix.

### PR DESCRIPTION
**Pull request by LDj3SNuD**
Temporary increase of JIT cache size to 3 GiB.
When the extra size is no longer needed, just edit this single line:
`private const uint CacheSize = 3U * 1024 * 1024 * 1024; // Default cache size = 2047 * 1024 * 1024.`
(@ ARMeilleure/Translation/Cache/JitCache.cs#L17).

### CODE REVIEW

**Comment by FIocker** [comment]
Dozens of Smash matches at 4k. No crashes. 

Would usually crash after 3-4 matches.

Very nais.

**Review by gdkchan — COMMENTED** [review]
I think the int -> uint changes are valuable, but the fact that the 2GB limit still remains for the unwind table is unfortunate. Did you try passing a uint there? There's nothing on the documentation that says if the value is supposed to be signed or unsigned. It might be possible to simply call `RtlInstallFunctionTableCallback` twice, offseting the address the 2nd time (and limiting the size to min(2GB, remainingSize).

**Comment by manfred-exz** [comment]
Works well for me. Fix one 100% happening "JIT Cache exhausted" issue in Monster Hunter Rise.

**Comment by manfred-exz** [comment]
I was always getting `System.OutOfMemoryException: JIT Cache exhausted` while compiling `PPTC` in `Monster Hunter Rise 1.1.2`.
This pull request fixed it.

**Review by Thog — APPROVED** [review]

**Comment by FICTURE7** [comment]
Not sure where to post this but, we can implement some sort of garbage collector on top of the JIT cache and free memory only when we need to, e.g when the allocator fails to allocate memory. Here is a rough prototype FICTURE7@2e894ab9c727eb7f0d1411bad5c1c253ddc0a855. However the fragmentation in the code cache gets rough very quickly. Perhaps could be worked around with different allocation strategy? 🤔

**Comment by gdkchan** [comment]
> 
> 
> Not sure where to post this but, we can implement some sort of garbage collector on top of the JIT cache and free memory only when we need to, e.g when the allocator fails to allocate memory. Here is a rough prototype [FICTURE7/Ryujinx@2e894ab](https://github.com/FICTURE7/Ryujinx/commit/2e894ab9c727eb7f0d1411bad5c1c253ddc0a855). However the fragmentation in the code cache gets rough very quickly. Perhaps could be worked around with different allocation strategy? 🤔

Currently the only memory that can be deleted is the one used for redundant translations of the same function, which I assume is a rare occurrence and wouldn't be enough to make a difference on games where we get cache exhaustion. I think making it effective would require some way to remove LowCq functions from the cache (either because they have been replaced by HighCq or because they are no longer need, which should be the case for cold boot initialization functions for example).

**Review by Daniel-iel — APPROVED** [review]

**Comment by Benedani** [comment]
With #2286, this should no longer be needed.

**Comment by Daniel-iel** [comment]
So let's close the PR

**Comment by LDj3SNuD** [comment]
PR was opened, as a pre-POWER temporary solution, to help some users complete their most demanding games in terms of JitCache; it can now be closed.

**Pull request closed without merging**
