### PR TITLE
IPC refactor part 3: Kernel decoupling

### LINKED ISSUE #913: Decouple kernel from the HLE project
We should move the kernel to a separate project. This will make testing easier and also creates a more clear separation of concerns.

There are several steps required to do that:
- [ ] Move kernel state out of the Horizon class. Things like the scheduler, the allocators etc should not be part of the Horizon class, instead it should be part of a separate one for the kernel state.
- [ ] Following that change, we should stop using the Horizon type on the kernel code entirely.
- [ ] We should use the new IPC system that was implemented on the kernel.
Currently we use the old "SendSyncRequest" syscall implementation: https://github.com/Ryujinx/Ryujinx/blob/master/Ryujinx.HLE/HOS/Kernel/SupervisorCall/SvcIpc.cs#L109
We should use the new one instead: https://github.com/Ryujinx/Ryujinx/blob/master/Ryujinx.HLE/HOS/Kernel/SupervisorCall/SvcIpc.cs#L171
This is caused by a misunderstanding of where the IPC handling was made when this code was written. It was assumed that the kernel handles some things that are actually handled by the service. 
- [ ] After those changes, we should also stop using kernel objects on services. Instead we can use the proper syscalls. We'll need a dummy process and thread per service for that.

After all that is done, we can finally move the kernel to it's own project.

### PR DESCRIPTION
**Pull request by gdkchan**
Depends on #1458.

The main change here is the kernel decoupling (closes #913), it adds 3 new projects:
- Ryujinx.Horizon.Kernel: The kernel, which now only depends on `Ryujinx.Memory`, `Ryujinx.Common` and `Ryujinx.Horizon.Common` (see below).
- Ryujinx.Horizon: Contains reimplementation of SDK library code in C# (to be used by services implementation). Should also have the services implementation in the future.
- `Ryujinx.Horizon.Common`: Common code used by the above 2 projects. It was added to avoid a cyclic dependency between the above 2 projects if they had to reference each other. Contains the `Result` struct and a few other utilities.

Services also now register themselves on SM, instead of SM scanning for services. This allows for a cleaner implementation of SM. It is also possible to run initialization code on the service thread. This is used for creating things like shared memory and events that needs to be accessed by other services or other components of the emulator. The hacky allocation of shared memory was also removed, and the proper syscall is used instead. It also does proper mapping of transfer memory now, instead of directly reading it from the game process memory.

Most of the SDK OS APIs implementation, and some of the new kernel syscalls, used Atmosphere as reference. For now, only what was strictly required was implemented, it will be extended in the future.

KIP loading was disabled for now, as it is supposed to be entirely internal to the kernel, and I still need to come up with a good way to load KIPs without exposing the kernel internal implementation to other projects. It was not really available from the GUI anyway, it was only usable with manual code modification.

WIP until the other parts are reviewed/merged.

### CODE REVIEW

**Comment by Thog** [comment]
As Atmosphère was used as a reference we will need to add a reference to it in the THIRDPARTY.md file (https://github.com/Atmosphere-NX/Atmosphere/blob/master/docs/licensing_exemptions/MIT_LICENSE)

**Comment by gdkchan** [comment]
> 
> 
> As Atmosphère was used as a reference we will need to add a reference to it in the THIRDPARTY.md file (https://github.com/Atmosphere-NX/Atmosphere/blob/master/docs/licensing_exemptions/MIT_LICENSE)

Done, not sure if I did it right though...

**Comment by AcK77** [comment]
Needs a rebase since #1458 is merged now!

**Comment by Benedani** [comment]
So, does this do anything with #1769 merged 7 months ago?

**Comment by gdkchan** [comment]
Yes, it has a lot more changes, this was just one of them.
At this point though, I just plan to pull the changes and open individual PRs with them, rebasing this would be a nightmare as the code changed a lot over the past months.

**Pull request closed without merging**
