### PR TITLE
Remove invalid menu

### PR DESCRIPTION
**Pull request by Zhoneym**
Remove invalid menu

### CODE REVIEW

**Comment by Rafacasari** [comment]
Translations are made through **[crowdin](https://crowdin.com/project/ryujinx)**, I think if you wan't to make/fix translations you should use it instead, they will sync changes with crowdin at some point, just need to wait a bit

**Comment by Zhoneym** [comment]
> Translations are made through **[crowdin](https://crowdin.com/project/ryujinx)**, I think if you wan't to make/fix translations you should use it instead, they will sync changes with crowdin at some point, just need to wait a bit

This is an invalid project that has always existed and has no actual functionality

**Comment by GreemDev** [comment]
> > Translations are made through **[crowdin](https://crowdin.com/project/ryujinx)**, I think if you wan't to make/fix translations you should use it instead, they will sync changes with crowdin at some point, just need to wait a bit
> 
> 
> 
> This is an invalid project that has always existed and has no actual functionality

what? lol

**Comment by Zhoneym** [comment]
> > > Translations are made through **[crowdin](https://crowdin.com/project/ryujinx)**, I think if you wan't to make/fix translations you should use it instead, they will sync changes with crowdin at some point, just need to wait a bit
> > 
> > 
> > This is an invalid project that has always existed and has no actual functionality
> 
> what? lol


Yes. The system language settings `SettingsTabSystemSystemLanguageChinese` and `SettingsTabSystemSystemLanguageTaiwanese` have been deprecated in the Emulator and are no longer functional. The Chinese language switch is now handled by `SettingsTabSystemSystemLanguageSimplifiedChinese` (Simplified Chinese, used in mainland China) and `SettingsTabSystemSystemLanguageTraditionalChinese` (Traditional Chinese, used by users in Taiwan, Hong Kong SAR, and Macau SAR). I think I should resubmit the PR and hope the developers will evaluate it carefully.

**Comment by IsaacMarovitz** [comment]
> Yes. The system language settings `SettingsTabSystemSystemLanguageChinese` and `SettingsTabSystemSystemLanguageTaiwanese` have been deprecated in the Emulator and are no longer functional. The Chinese language switch is now handled by `SettingsTabSystemSystemLanguageSimplifiedChinese` (Simplified Chinese, used in mainland China) and `SettingsTabSystemSystemLanguageTraditionalChinese` (Traditional Chinese, used by users in Taiwan, Hong Kong SAR, and Macau SAR). I think I should resubmit the PR and hope the developers will evaluate it carefully.

You are confusing the Switch OS language settings and Ryujinx UI language settings.

**Comment by IsaacMarovitz** [comment]
Screenshot 2024-10-01 at 12 21 04

These values are determined from reverse engineering.

**Pull request closed without merging**
