### PR TITLE
Implement CSRNG (Cryptographically Secure Random Bytes)

### PR DESCRIPTION
**Pull request by Cyuubi**

### CODE REVIEW

**Comment by gdkchan** [comment]
Just a FYI, rng means "random number generator" and not "random bytes".

**Comment by AcK77** [comment]
It's not `cryptographically secure random number generator` ? Who could be get by `RandomNumberGenerator.Create()`

**Comment by greggameplayer** [comment]
@Cyuubi it's a buffer type-6 and not a buffer type 0x21

**Comment by Cyuubi** [comment]
IIRC, the others didn't work for me.

**Comment by gdkchan** [comment]
I suggest renaming `CspRnd` to `Rng` and using the correct buffer type.

**Comment by gdkchan** [comment]
I just checked the docs and `RNGCryptoServiceProvider` needs to be disposed, which doesn't happen on your code.

**Comment by AcK77** [comment]
Thanks!

**Pull request merged**
