### PR TITLE
Native Menu Bar on macOS

### PR DESCRIPTION
**Pull request by IsaacMarovitz**
Adds a `NativeMenu` to move menu bar items to system menu bar instead of including them in the window on macOS.

- [ ] Action menu available when game isn't running (Avalonia issue needs workaround)
- [ ] Pause/Resume visible at same time (Avalonia shortcoming no `IsVisible` https://github.com/AvaloniaUI/Avalonia/issues/7952)

Avalonia Issues:
- On language change, top-level menus i.e. `File` will not update, menu items will (Avalonia Issue)
- Action menu improperly enabled https://github.com/AvaloniaUI/Avalonia/issues/9552
- Accelerator key locales don't work with `NativeMenu` https://github.com/AvaloniaUI/Avalonia/issues/9550

### CODE REVIEW

**Comment by Steveice10** [comment]
Instead of having two copies of the menu with one disabled on macOS, you should be able to replace the in-window menu with NativeMenuBar which will handle it for you. See: https://github.com/AvaloniaUI/Avalonia/issues/898#issuecomment-1025460399

**Comment by IsaacMarovitz** [comment]
> Instead of having two copies of the menu with one disabled on macOS, you should be able to replace the in-window menu with NativeMenuBar which will handle it for you. See: [AvaloniaUI/Avalonia#898 (comment)](https://github.com/AvaloniaUI/Avalonia/issues/898#issuecomment-1025460399)

I don't have a Windows machine to test this

**Comment by IsaacMarovitz** [comment]
TBD later after the switch Ava 11

**Comment by ZeppLu** [comment]
> TBD later after the switch to Ava 11

Now that Avalonia 11 officially released, any updates?

**Comment by IsaacMarovitz** [comment]
> Now that Avalonia 11 officially released, any updates?

No. I’m still waiting on improvements to Avalonia’s API

**Comment by beginor** [comment]
Avalonia already has a NativeMenuBar example,  will you continue to work on this pr?
 https://github.com/AvaloniaUI/Avalonia/blob/ceb172f22790b74c56550889b02eb7e8f1dbf8d1/samples/IntegrationTestApp/MainWindow.axaml#L24

**Comment by IsaacMarovitz** [comment]
NativeMenuBar is still missing necessary features in the latest stable version of Avalonia.

**Review by Wiratudomsamut — COMMENTED** [review]
https://github.com/user-attachments/assets/9af3cb70-4bd4-4233-92a9-474f18f55e9e

**Pull request closed without merging**
