### PR TITLE
Simplify depth test state updates

### PR DESCRIPTION
**Pull request by gdkchan**
The OpenGL spec states:
> If there is no depth buffer, it is as if the depth buffer test always passes.

Currently, there is some code that disables depth test if there's no depth buffer. This is redundant as the host API will already do that. This change will just set depth test directly instead which reduces the number of API calls and simplifies the code a bit.

Should not cause any change on games.

### CODE REVIEW

**Review by Thog — APPROVED** [review]
lgtm

**Comment by Thog** [comment]
Rebase required because of https://github.com/Ryujinx/Ryujinx/commit/aa129fdbdfd424f73da2b187fc28855f8ae90059.

**Comment by gdkchan** [comment]
Rebased.

**Review by riperiperi — APPROVED** [review]
LGTM.

**Pull request merged**
