### PR TITLE
Implement code memory syscalls

### PR DESCRIPTION
**Pull request by gdkchan**
This implements code memory related syscalls, used by applications that generates and/or modifies code at runtime.
It is required by, for example, emulators that uses a JIT (NSO N64) and mods that patches for function hooking game code on-the-fly (skyline/ARCropolis). Neither will work with those changes alone, but its a step towards it.

Depends on #2954 because code modification requires mapping a RW view of the RX code region.

### CODE REVIEW

**Comment by MutantAura** [comment]
supercedes #2451 ?

**Comment by gdkchan** [comment]
> supercedes #2451 ?

Yes.

**Comment by xerpi** [comment]
Tested on Linux x64 and using a 32-bit Switch homebrew.

**Comment by gdkchan** [comment]
This has been rebased and is ready for review. It has already been largely tested with homebrews, mods and the official N64 emulator.

Here's a screenshot of PPSSPP running on it (also requires being launched from the hbmenu/homebrew launcher):
image

**Review by riperiperi — APPROVED** [review]
LGTM, glad to see this finally ready for merge.

MelonDS (fast memory disabled) and Citra are working, though due to some GPU issues (regressions?) they seem to have some visual issues right now. Here's some older screenshots from back in January:

image

image

**Review by Thog — APPROVED** [review]

**Comment by riperiperi** [comment]
Found out what was wrong with the graphics in those emulators. So here's some up to date screenshots.

- MelonDS: Needs #2237
- Citra: I was using an older version of the branch...

image

image

**Pull request merged**
