### PR TITLE
GPU: Don't create tracking handles for buffer textures

### PR DESCRIPTION
**Pull request by riperiperi**
Buffer texture memory is handled by the buffer cache - the texture shouldn't create any tracking handles as they aren't used. This change simply makes them create and iterate 0 tracking handles, while keeping the rest of the texture group around.

This prevents a possible issue where many buffer textures are created as views of overlapping buffer ranges, and virtual regions have many dependant textures that don't actually contribute anything to handle state.

Also included:
- Fix a longstanding issue where every texture returned from the interval tree lookup would resize the lookup array. (yes, every)
- Buffer textures now skip checking view compatibility with any other textures, since they are never compatible and don't remove each other due to overlap.
  - In MK1, more than 100 buffer textures would overlap at once, making this overlap check very expensive as well as pointless.

This PR is thanks to testing and profiling by @gdkchan. I don't have an affected game myself.

Should improve performance in Mortal Kombat 1, possibly certain UE4 games when FIFO raises to 100%. Needs testing in UE4 games and the 2 Mortal Kombat games.

### CODE REVIEW

**Comment by GamerzHell9137** [comment]
Fixes FPS during gameplay in R-TYPE FINAL 2 (Demo, most likely translates to full game). Pretty much goes from 0 to 60 FPS with the change. Game has still FIFO maxed at the opening sequence and other graphical issues not related to this PR.

Master: 
image-3

PR:
image-5

**Comment by gdkchan** [comment]
Performance seems much better on Mortal Kombat 1 here with this change.
Master:
image
image
PR:
image
image
The frame rate is also more stable with this PR, on master it was dropping quite a bit.
I'm probably not the best person test it though as I only have an integrated GPU on this PC right now.

**Review by gdkchan — APPROVED** [review]
lgtm, thanks! I think it could be better to create a separate `FindOrCreateTexture` method just for buffer textures, given that most of the code there does nothing when the overlaps count is 0. But maybe the amount of code that can still be shared makes that not worth it.

I was pretty surprised with the resize bug, but I guess something like that is easy to go unnoticed, as it does not create correctness issues, and only becomes apparent on games creating textures non-stop.

**Review by marysaka — APPROVED** [review]

**Comment by sakuka47** [comment]
Hi, great improvement in the MK1 game but the cinematics still bug.

Image tearing

**Comment by Niwu34** [comment]
Tried Mortal Kombat 11:
Max fifo can still reach 99% (60fps all the time) but is lower in general

`Master:`
Screenshot 2023-09-26 110610

`PR:`
Screenshot 2023-09-26 111037

**Comment by GamerzHell9137** [comment]
> Hi, great improvement in the MK1 game but the cinematics still bug.
> 
> Image tearing

Happens on Switch too, not emulator issue.

**Pull request merged**
