### PR TITLE
SettingsWindow: Add an Apply button

### PR DESCRIPTION
**Pull request by SeraUX**
Adds an apply button that doesnt close the settings window when saving
the changes.

### CODE REVIEW

**Review by Xpl0itR — APPROVED** [review]
LGTM

**Review by AcK77 — APPROVED** [review]

**Comment by AcK77** [comment]
Needs a rebase!

**Comment by SeraUX** [comment]
Rebased

**Comment by SeraUX** [comment]
Rebased

**Review by Thog — APPROVED** [review]
look good to me but one issue to fix before merging, the button stay pressed

image

**Pull request merged**
