### PR TITLE
Add mod enablement status in the log message

### PR DESCRIPTION
**Pull request by WilliamWsyHK**
As annoyed by not knowing the status of mod if it is enabled when investigating the log, I have decided to just add small update in the log message so that we all can see the status from the log itself.

That means it is also required to update the log parser. (https://github.com/Ryujinx/ryuko-ng/pull/93)
**! Merge the log parser first before this PR !**

### CODE REVIEW

**Review by riperiperi — APPROVED** [review]
Looks good. I don't think the round brackets around the ternary expression are required, though.

**Comment by WilliamWsyHK** [comment]
I hope I could remove it, but my VSCode complains it, and line 328 also has the same pair of round backets.

**Review by MutantAura — APPROVED** [review]

**Comment by IsaacMarovitz** [comment]
> Looks good. I don't think the round brackets around the ternary expression are required, though.

They are unfortunately for some reason when doing string interpolation

**Review by IsaacMarovitz — APPROVED** [review]

**Comment by WilliamWsyHK** [comment]
> > Looks good. I don't think the round brackets around the ternary expression are required, though.
> 
> They are unfortunately for some reason when doing string interpolation

Thanks, and just additional info on the brackets for ternary expression.
It is related to the format string in the original placeholder like `{0:X}` so they want to avoid syntax ambiguity. [Special characters in C# Lang ref.](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated#special-characters)

**Review by AcK77 — APPROVED** [review]

**Pull request merged**
