### PR TITLE
Ava UI: Mod Manager Fixes

### PR DESCRIPTION
**Pull request by IsaacMarovitz**
Changes:
- Fixes a crash when selecting an invalid mod directory
- Fixes a crash when trying to enumerate through a directory that Ryujinx doesn't have permissions to access
- Fixes deleting a mod not deleting at the parent directory, leaving invisible orphan files that would prevent re-importing of the same mod
- Better logging and user feedback

TODO: More robust testing of folders to see if they contain valid mods before copying them to the mod directory. This will still copy invalid folders to the mod directory if they have subdirectories, where they won't appear in the list.

Since copying is recursive, this is especially important. Selecting a top-level folder by accident could be very expensive.

### CODE REVIEW

**Review by AcK77 — APPROVED** [review]

**Comment by Littl3Guy** [comment]
An error makes it possible to duplicate the mod and have it load from both the mod source and the ryujinx mod folder:

https://github.com/Ryujinx/Ryujinx/assets/115218507/02deaf5c-d085-4650-832b-7f4197ba51d4

**Comment by IsaacMarovitz** [comment]
@Littl3Guy I can see why this bug is occurring. To me, it feels pretty niche, and I'm not sure how best to guard against it. The issue is the format of mods is quite flexible, so validating them isn't easy.

**Comment by Littl3Guy** [comment]
Yeah its pretty weird steps to trigger it so its probably safe to leave like that for now.

**Comment by Littl3Guy** [comment]
I suppose it wouldn't be possible to grey out the "Select Folder" option unless a folder is selected?

**Comment by IsaacMarovitz** [comment]
> I suppose it wouldn't be possible to grey out the "Select Folder" option unless a folder is selected?

That's up to Avalonia, not much to be done about it.

**Review by marysaka — APPROVED** [review]
lgtm

**Pull request merged**
