### PR TITLE
Rumble support

### PR DESCRIPTION
**Pull request by anirudhb**
Adds a rumble implementation.

The appropriate system calls are now un-stubbed. Rumble should work on most controllers that support it via SDL2.

SDL2 has been added as a new dependency for rumble. The code _should_ not crash if the library is not found.

Todo
- [x] multiple controller support
- [x] non-XInput support
- [x] Debugging xbox one controllers
- [ ] Slimming SDL2 to only include haptics functionality

### CODE REVIEW

**Comment by legend800** [comment]
Thanks for working on rumble implementation. Is it supposed to add rumble to xinput/xbox one pads? If so, not working for me.

2020-07-29 00_21_42-Ryujinx 1 0 5073 - Mario Kart 8 Deluxe v1 7 1 (0100152000022000) (32-bit)

2020-07-29 00_19_40-Ryujinx 1 0 5073 - Mario Kart 8 Deluxe v1 7 1 (0100152000022000) (32-bit)

**Comment by anirudhb** [comment]
@legend800 thanks for testing! Could you attach logs? Additionally, are you sure that your controller supports rumble (i.e. have you tested in other games)? Also maybe look up your controller and see if it physically contains two vibration motors (large and small), as that's the kind of vibration that I test for and use.

**Comment by legend800** [comment]
Here's the log. I'm not sure if it captured everything as Ryu always hangs on stopping emulation recently and maybe it doesn't flush everything to log?

[Ryujinx_2020-07-29_12-05-13.log](https://github.com/Ryujinx/Ryujinx/files/4996943/Ryujinx_2020-07-29_12-05-13.log)

I'm using an Xbox One wireless pad (via adapter not blutooth). Works fine in other emus, including yuzu.

**Comment by DartPower** [comment]
👍

**Comment by anirudhb** [comment]
@legend800 thanks for the logs! It doesn't seem like anything was wrong with your configuration, however I discovered I was scaling magnitude values incorrectly. I've also added a new menu to select the haptic device in the controller settings. Try with the new commit.

**Comment by legend800** [comment]
Thanks for trying, but no change - just a tiny rumble at beginning of race, but nothing else that I can feel. 

2020-07-29 16_15_51-Ryujinx - Controller Settings

**Comment by anirudhb** [comment]
Updated again. I know for a fact it should work, especially on the orange accelerators in MK8. Have you tested anything beyond that? I've also added a quadratic ease out curve since the low-range amplitudes are impossible to feel.

**Comment by legend800** [comment]
Sorry, no change. Tried some other games like Mario Tennis and didn't get any rumble there either.

**Comment by anirudhb** [comment]
Blocked on #1561, which will migrate all of Ryujinx to SDL (making this use of SDL not a problem.)

**Comment by EmulationFanatic** [comment]
@anirudhb Are you still interested in this PR?

**Comment by anirudhb** [comment]
Yes, but it's still blocked on the above PR. Ryujinx devs don't seem to be interested in having SDL as an additional dependency for now.

**Comment by EmulationFanatic** [comment]
> Yes, but it's still blocked on the above PR. Ryujinx devs don't seem to be interested in having SDL as an additional dependency for now.

@anirudhb This may have changed, as it turns out OpenTK 4 does not have SDL bindings.

**Comment by anirudhb** [comment]
Hmm, okay will take a look into rebasing soon then!

**Comment by jduncanator** [comment]
Just a heads up that I aim to tackle this as part of my HID overhaul that I'm currently working on.

**Comment by EmulationFanatic** [comment]
> Just a heads up that I aim to tackle this as part of my HID overhaul that I'm currently working on.

Sure thing @jduncanator but until that lands, work can continue on @anirudhb's PR to see how far we can get with it.

**Comment by anirudhb** [comment]
Updated (& rebased). @legend800 you seemed to have an issue with your controller, can you please try now? I believe I fixed it.

**Comment by EmulationFanatic** [comment]
Are XBOX 360 for Windows controllers supported?

**Comment by anirudhb** [comment]
They should be, if they support rumble. There seemed to be an issue with that previously but I believe it's fixed now.

**Comment by EmulationFanatic** [comment]
I've got one here and I can't get it to exhibit any signs of rumbling. I enabled the function in the controller input config options.

**Comment by anirudhb** [comment]
Can you upload logs?

**Comment by EmulationFanatic** [comment]
[Ryujinx_1.0.6571_2021-02-14_16-14-54.log](https://github.com/Ryujinx/Ryujinx/files/5978726/Ryujinx_1.0.6571_2021-02-14_16-14-54.log)

**Comment by anirudhb** [comment]
Can you upload a log with Debug level enabled?

**Comment by legend800** [comment]
Same here. Nothing on the latest build. 

If you need a log, can you screenshot the Logging tab so I'm clear exactly what settings need to be on and their values so I can capture what you need without one that's hundreds of mbs?

**Comment by EmulationFanatic** [comment]
[Ryujinx_1.0.6571_2021-02-14_16-39-11.log.zip](https://github.com/Ryujinx/Ryujinx/files/5978787/Ryujinx_1.0.6571_2021-02-14_16-39-11.log.zip)

**Comment by anirudhb** [comment]
Updated. Could you both try now? I don't believe debug logs are necessary, it turns out I was doing something wrong in the code.

**Comment by EmulationFanatic** [comment]
That did the trick! Tried in a few games and it's working well now on the XBOX360 for Windows controller.

**Comment by legend800** [comment]
Not for me. Using this build on an XSX pad, no rumble on Win10:
https://ci.appveyor.com/project/gdkchan/ryujinx/builds/37770317/artifacts

Double checked it's ticked in Settings and tested SMO and MK8.

**Comment by EmulationFanatic** [comment]
@anirudhb feel free to rejoin our Discord as there are a few users who have been actively testing and may have some valuable feedback there in the #development channel.

**Comment by EmulationFanatic** [comment]
As mentioned on Discord, the last commit makes the rumble feel appropriately intense on an XBOX 360 controller.

**Comment by Shahil-Ayato** [comment]
Needs rebase.

**Comment by Shahil-Ayato** [comment]
This could help with #1452

**Comment by Thog** [comment]
As we are dropping OpenTK 3 soon, this is going to need to be entirely remade.
I also have an issue with how this is handled.
The SDL2 haptic APIs are considered legacy and shouldn't be used (in fact it's not implemented on all game controller).
The game controller rumble API should be used.

For those reasons, I'm closing this PR.

**Comment by legend800** [comment]
Maybe that's why it never worked on my Xbox SX pad.

**Pull request closed without merging**
