### PR TITLE
chore: Update Ryujinx.SDL2-CS to 2.26.0

### PR DESCRIPTION
**Pull request by marysaka**
As title say.

Partially fix https://github.com/Ryujinx/Ryujinx/issues/3293

### CODE REVIEW

**Comment by sakuka47** [comment]
Is it possible to map the capture and home button to the dual joy-con and pro command?

**Comment by TSRBerry** [comment]
Has nothing to do with this PR.

**Comment by Soulize** [comment]
There are some problems with gyro. 
It is too sensitive in SMO that just touching joycon slightly can cause Mario throw his hat incessantly.
https://user-images.githubusercontent.com/63684394/204019840-30d55a63-1987-4154-b2a8-5f865dabbb60.mp4
In Skyward Sword HD, pointer of gyro would twitch when joycon is stationary. It also has a weird delay in this game.

The options Gyro Sensitivity and Gyro Deadzone seem not work as well.

**Comment by marysaka** [comment]
Closing for now, will reopen a new PR for 2.26.1 without the motion changes and work on it again after it's merged.

**Comment by Gr4v1t0** [comment]
Should this be reoppened since the other PR is merged?

**Comment by TSRBerry** [comment]
No since 2.26.1 is newer than 2.26.0.

**Comment by Gr4v1t0** [comment]
> Closing for now, will reopen a new PR for 2.26.1 without the motion changes and work on it again after it's merged.

what about the motion changes? Dual Joycon support needs this right?

**Comment by TSRBerry** [comment]
I'm not up-to-date on SDL things, so I'm not certain, but dual joycons should work even if motion doesn't work yet.

**Comment by Gr4v1t0** [comment]
not out of the box, only with third party apps and those are buggy / need workarounds
the screenshot above shows dual joycon (L/R) as a selectable option, but I guess this is only in the ryujinx-Release-1.1.0+0fef248 build mentioned above - it's not selectable in my 1.1.719 with two joycons connected via bluetooth
maybe I better ask in #3293 ?

**Comment by TSRBerry** [comment]
Yes!

**Comment by xorange90x** [comment]
Oh ok. Thanks. I'm new to GitHub so I don't really understand the threads to well. If Ryujinx were built like the n64 emulators of old, we could likely just pull the input plugin file from the working build and drop it into the latest 😩

**Pull request closed without merging**
