### PR TITLE
Update PPTC dialog text to match label and tooltip

### PR DESCRIPTION
**Pull request by RKennedy9064**
This update is to have the dialog text match the text changes from #3601.

Before:
image

After:
image

### CODE REVIEW

**Comment by EmulationFanatic** [comment]
Good catch - only thing I would maybe recommend is making it say "You are about to queue a PPTC rebuild on the next boot of:"

**Comment by RKennedy9064** [comment]
@EmulationFanatic Sounds good, just update the text. Looks like my IDE also automatically formatted out some empty spaces. Let me know if you want me to revert that.

**Comment by EmulationFanatic** [comment]
> @EmulationFanatic Sounds good, just update the text. Looks like my IDE also automatically formatted out some empty spaces. Let me know if you want me to revert that.

I would revert the extra space deletions, simply because they are outside the scope of this PR and could have unintended consequences.

**Comment by RKennedy9064** [comment]
Okay I think I got the formatting back to how it was before this change.

**Review by EmulationFanatic — APPROVED** [review]
LGTM

**Review by Thog — APPROVED** [review]

**Pull request merged**
