### PR TITLE
Infra: Capitalisation Consistency

### PR DESCRIPTION
**Pull request by IsaacMarovitz**
Ryujinx is very inconsistent about properly capitalising certain phrases, technologies etc. According to [.NET capitalization guidelines](https://learn.microsoft.com/en-us/previous-versions/dotnet/netframework-4.0/ms229043(v=vs.100)#capitalization-rules-for-acronyms):

>Do capitalize both characters of two-character acronyms, except the first word of a camel-cased identifier.

>A property named DBRate is an example of a short acronym (DB) used as the first word of a Pascal-cased identifier. A parameter named ioChannel is an example of a short acronym (IO) used as the first word of a camel-cased identifier.

This PR addresses one of those inconsistencies by replacing instances of `Ui` with `UI`. The `Ryujinx.Ava.UI` namespace was updated to follow this convention several months ago.

### CODE REVIEW

**Comment by gdkchan** [comment]
If you are looking for inconsistencies, another thing that is not consistent is the use of single quote and double quote in log messages. And also how they are added (with `.`, `!`, or nothing). If you want to address those in a separate PR, feel free too.Should not be too hard with some regex magic.

**Comment by gdkchan** [comment]
FWIW the .NET design guidelines says that only acronyms with up to 2 characters should be capitalised, otherwise only the first character should be capitalised. https://learn.microsoft.com/en-us/previous-versions/dotnet/netframework-4.0/ms229043(v=vs.100)#capitalization-rules-for-acronyms
This change does follow this rule since UI is only 2 characters long.

**Comment by IsaacMarovitz** [comment]
> FWIW the .NET design guidelines says that only acronyms with up to 2 characters should be capitalised, otherwise only the first character should be capitalised. https://learn.microsoft.com/en-us/previous-versions/dotnet/netframework-4.0/ms229043(v=vs.100)#capitalization-rules-for-acronyms This change does follow this rule since UI is only 2 characters long.

For PascaleCase instances (like namespaces) the guidelines say the following re: short acronyms

> Do capitalize both characters of two-character acronyms, except the first word of a camel-cased identifier.

**Review by AcK77 — APPROVED** [review]
I haven't tested PR's build yet but code wise it LGTM!

EDIT: Tested, no issues were found.

**Review by gdkchan — APPROVED** [review]
lgtm, thanks.

**Pull request merged**
