### PR TITLE
Implement Rumble In Ryujinx

### LINKED ISSUE #1659: Support for HD Rumble
#### Overview:
- Implement HD rumble for Switch controllers connected as xinput (eg. through BetterJoy)

#### Nature of Request:  

- Addition

### Why would this feature be useful?
Most games on the switch have HD rumble, so adding support for it would be ideal for playing those games.

### PR DESCRIPTION
**Pull request by shukenmg**
## Implement Rumble In Ryujinx
This PR aims to implement per-player rumble support in many games.

### Supported Controllers
- Switch Pro Controller: Works
- Joycons: Not Tested
- Xbox One Controller: Works
- Other Controllers: Not Tested
_Please let me know if other controllers work/don't work_

### Tested Games
- ARMS: Working
- Age Of Calamity: Working
- Mario Kart 8 Deluxe: Working

**Added:**
- Super Mario Tennis: Working
- Super Mario Odyssey: Working
_Please let me know if other games work/don't work_

### Changes
Appropriate system calls are now un-stubbed.
Use of SDL2 to send vibration data to the controller.
Added SDL2 dependencies to the project.
Added rumble configuration options.
image

### Other notes
If you are using BetterJoy to connect to Ryujinx please make sure to use a version greater that 6.4b
_At this time (2020/11/04--yyyy/mm/dd) there are no versions greater than 6.4b so please use this build instead._
[BetterJoy-PreviewBuild-x64.zip](https://github.com/Ryujinx/Ryujinx/files/5485694/BetterJoy-PreviewBuild-x64.zip)
This will close #1659 

### Credits
Thanks to @anirudhb for starting this work #1436 
Kudos to @Morph1984 for his wonderful amplitude scaling formula.
PS. Do I need to add some sort of license for using the formula?

### CODE REVIEW

**Comment by anirudhb** [comment]
First, I do not give consent for you to use my work in your PR (unfortunately) since it seems I wasn't even credited in the commit authoring.

Secondly, my pr was only stalled due to the developers not wanting to add sdl2 as another dependency and afaict this still has sdl2 as a dependency so it wouldn't be merged anyways.

Thanks!

**Comment by shukenmg** [comment]
@anirudhb 
Oh, i'm sorry, my bad, how do I add you as a co-author?

**Comment by Doctorwho1909** [comment]
This PR doesn’t work very well sure rumble goes off but it’s at random times and most times you can barley feel it Xbox one and 3rd party Xbox one

**Comment by shukenmg** [comment]
> This PR doesn’t work very well sure rumble goes off but it’s at random times and most times you can barley feel it Xbox one and 3rd party Xbox one

What game are you playing?

**Comment by shukenmg** [comment]
Closing this is favor of #1665

**Comment by Doctorwho1909** [comment]
Smo and hyrule warriors age of calamity

**Comment by shukenmg** [comment]
Official Xbox One controllers should work fine, third party controllers not so much.
This PR was mainly designed and tested with the Switch Pro Controller.

**Comment by shukenmg** [comment]
@anirudhb 
I have added you as co-author in #1665

**Comment by PytGamer** [comment]
Hi mate, thanks for your effort to make this possible for Ryujins, can you help me here i am trying to figure out how to implement this to my installed files of the Emulator, can you help me please thanks

**Comment by PytGamer** [comment]
@shukenmg Hi mate, thanks for your effort to make this possible for Ryujins, can you help me here i am trying to figure out how to implement this to my installed files of the Emulator, can you help me please thanks

**Pull request closed without merging**
