### PR TITLE
Implement remaining shader double-precision instructions

### PR DESCRIPTION
**Pull request by gdkchan**
Changes:
- Implements remaining double instructions: DMNMX, DSET and DSETP.
- Implements remaining double-precision operations on MUFU instruction: RCP64H and RSQ64H.
- Fix immediate operands on all double-precision instruction. Before it was being interpreted as a the higher 20-bits of a float value converted to double, when it should be the higher 20-bits of a double value.

I know that World War Z uses the DSET/DSETP instruction, but I don't know which impact those changes would have on this title, and I don't know many other games using them, as double-precision is rarely used on shaders for performance reasons.

### CODE REVIEW

**Comment by LukeWarnut** [comment]
Allows WWZ to proceed through menus with good frame rate and rendering with a new crash
```00:02:09.188 |E| HLE.OsThread.15 Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentException: IPv4 address 0.0.0.0 and IPv6 address ::0 are unspecified addresses that cannot be used as a target address.
   at System.Net.Dns.GetHostEntry(String hostNameOrAddress)
   at Ryujinx.HLE.HOS.Services.Sockets.Sfdnsres.IResolver.GetHostByNameRequestImpl(ServiceCtx context, UInt64 inputBufferPosition, UInt64 inputBufferSize, UInt64 outputBufferPosition, UInt64 outputBufferSize, UInt64 optionsBufferPosition, UInt64 optionsBufferSize)
   at Ryujinx.HLE.HOS.Services.Sockets.Sfdnsres.IResolver.GetHostByNameRequestWithOptions(ServiceCtx context)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ryujinx.HLE.HOS.Services.IpcService.CallHipcMethod(ServiceCtx context)
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr)
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop()
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

image
image

[WWZ-PR2845.log](https://github.com/Ryujinx/Ryujinx/files/7535212/WWZ-PR2845.log)

**Comment by LukeWarnut** [comment]
> Allows WWZ to proceed through menus with good frame rate and rendering, alongside a new crash upon entering gameplay.

Oh wait. These are the same results as #2831. Whoops. No noticeable changes then.

**Comment by MadDragon1846** [comment]
Yeah, it seems to run about the same graphics-wise. I get the same error as Luke on this version and the other version when starting the match.

I tried the game with no update and update 1.0.5. Update 1.0.5 has really bad audio. The audio works fine with no update though.

**Review by riperiperi — APPROVED** [review]
LGTM

**Review by Thog — APPROVED** [review]

**Pull request merged**
