### PR TITLE
Avalonia -- Per Game Settings [Part 1]

### LINKED ISSUE #1796: Game specific settings
#### Overview:
Add separate settings for each game to make it possible to use different configuration settings for each.

#### Smaller Details: 
Keep the main settings as a default setting for new and unconfigured games. Then add the ability to change PPTC, resolution scale, anisotropy, shader cache, [...] and all future settings separately for each game.

#### Nature of Request:  
- Addition
  - Right-click menu for each game entry allowing to configure game specific settings, which are initially taken from the Ryujinx default settings (from the main menu), to tailor them to a specific game.
  - The option to revert the game settings to "default" settings (those defined in Ryujinx, "forgetting" the game specific settings)

### Why would this feature be useful?
Adding this feature would allow some games to be treated with the workaround they need, while not having to change the emulation settings globally for all games.
One example: 
[Hyrule Warriors: Definitive Edition](https://github.com/Ryujinx/Ryujinx-Games-List/issues/168) still crashes/freezes ingame when the PPTC is enabled, but plays fine with it disabled. So every time I want to start that game, I have to disable the PPTC, then enable it after playing for other games to benefit from the PPTC.

### LINKED ISSUE #3232: Change Language for Individual Games in Ryujinx
Hello,

Just want to say that I love you guys' work on Ryujinx, awesome job!!!

So, my feature request is pretty much what it says in the title.

The issue that I found is probably very specific for my situation, but maybe more people can benefit from such Feature in Ryujinx;

-My first language is Brazilian Portuguese
-Some games are only in Portuguese
-if I select Brazilian Portuguese, games in Portuguese language only will be in English

Thank you so much! :)

## Feature Request

[ If any section does not apply, replace its contents with "N/A". ]</br>
[ If you do not have the information needed for a section, replace its contents with "Unknown". ]</br>
[ Lines between [ ] (square brackets) are to be removed before posting. ]</br>

[ Please search for existing [feature requests](https://github.com/Ryujinx/Ryujinx/issues) before you make your own request. ]</br>
[ Duplicate requests will be marked as such and you will be referred to the original request. ]

#### Overview:
- [ Include the basic, high-level concepts for this feature here. ]

#### Smaller Details: 
- [ These may include specific methods of implementation etc. ]

#### Nature of Request:  
[ Remove all that do not apply to your request. ]
- Addition
  - [ Ex: Addition of certain original features or features from other community projects. ]
  - [ If you are suggesting porting features or including features from other projects, include what license they are distributed under and what, if any libraries those project use. ]
- Change
- Removal
  - [Ex: Removal of certain features or implementation due to a specific issue/bug or because of low quality code, etc.]

### Why would this feature be useful?
[ If this is a feature for an end-user, how does it benefit the end-user? ]</br>
[ If this feature is for developers, what does it add to Ryujinx that did not already exist? ]

### PR DESCRIPTION
**Pull request by saldabain**
This is being split into two parts (one that supports a global state, and one that doesn't.)

Part 1 will not include support for a global state.

A highly requested feature, this PR adds the ability to create custom configurations for each game, saving you a lot of time for those that have many games that perform better with different configurations.

This PR is very much an early draft. Expect many bugs and potentially crashes.

Do make a backup of your existing configuration, there is a possibility that this PR may ruin your existing configuration settings

To Do:
 

 - [ ] Implement Support for Graphics [In Progress]
 - [ ] Implement Support for System
 - [ ] Implement Support for CPU
 - [ ] Implement Support for Hid
 - [ ] Implement Support for Audio
 - [ ] Implement Support for Logging
 - [ ] Implement Support for Network

Closes #1796, closes #3232

### CODE REVIEW

**Comment by GamerzHell9137** [comment]
Per game options are saved as global options.

**Comment by saldabain** [comment]
> Per game options are saved as global options.

Please check this again once the build completes, there was a bug where the title specific settings window would appear even if you clicked on the menu bar "Open Settings" when the game isn't running.

**Comment by Foul-Tarnished** [comment]
Any news on this ?
It looks way more painful to implement than what I would have thought, good luck

I guess the settings configuration were not designed with this in mind at all, sad

**Comment by MultiKoopa** [comment]
why was this closed?

**Comment by piplup55** [comment]
> why was this closed?

the author doesn't want to work on it anymore, that's why they closed it

**Pull request closed without merging**
