### PR TITLE
Mon hun rise

### PR DESCRIPTION
**Pull request by SuperShotgunLove**

### CODE REVIEW

**Comment by SuperShotgunLove** [comment]
sorry. i have no idea what im doing.

**Comment by riperiperi** [comment]
I can see that.

**Review by SuperShotgunLove — COMMENTED** [review]
yep

**Comment by Itamai** [comment]
> yep

i guess you just wanted to test the draft pr from gdk?
https://github.com/Ryujinx/Ryujinx/pull/2138#issuecomment-807441030
There are the binaries just download the release one for your system

**Pull request closed without merging**
