### PR TITLE
infra: Migrate to .NET 5

### PR DESCRIPTION
**Pull request by Thog**
This migrate projects and CI to .NET 5

### CODE REVIEW

**Review by LDj3SNuD — APPROVED** [review]

**Review by AcK77 — APPROVED** [review]

**Comment by Thog** [comment]
Waiting for AppVeyor to update their VS 2019 image with the .NET 5 release.

**Review by gdkchan — APPROVED** [review]
lgtm, thanks.

**Comment by LDj3SNuD** [comment]
It would be a good opportunity to evaluate the updating of all packages (where applicable).

**Comment by shukenmg** [comment]
@Thog 
https://www.appveyor.com/updates/2020/11/14/
They just updated the image :)

**Pull request merged**
