### PR TITLE
Update Config.json

### PR DESCRIPTION
**Pull request by Joshi234**
Changed deadzone becuase many people are experiencing drift because its to low

### CODE REVIEW

**Comment by B3astTech** [comment]
Out of many others that don't is also to conclude. If someone has a issue with drift they can change this them self's. Because every controller is diffrent and will need to fine tune it to there own controller

**Comment by Joshi234** [comment]
Ok I think it would be usefule if there is a setting in ryujnix for changing deadzone

**Comment by B3astTech** [comment]
There is already a pr doing so. But it's not ready so it will come avenchally

**Comment by AcK77** [comment]
This issue is already fixed in #849. You will be able to set the deadzone in the GUI.
I close this PR because of that. Thanks for your interest ;)!

**Pull request closed without merging**
