### PR TITLE
A64: Add fast path for Fcvtas_Gp/S/V, Fcvtau_Gp/S/V and Frinta_S/V in…

### PR DESCRIPTION
**Pull request by LDj3SNuD**
…structions; A32: Add fast path for Vcvta_RM, Vrinta_RM and Vrinta_V instructions aswell.
They use "Round to Nearest with Ties to Away" rounding mode not supported in x86.

```csharp
[Test]
public void RndF([Random(1000)] float f)
{
    float fC = BitConverter.Int32BitsToSingle(0x3EFFFFFF); // BitConverter.SingleToInt32Bits(0.5f) - 1

    float actual = MathF.Truncate(float.IsNegative(f) ? f - fC : f + fC);
    float expected = MathF.Round(f, MidpointRounding.AwayFromZero);

    Assert.That(actual, Is.EqualTo(expected));
}

[Test]
public void RndD([Random(1000)] double d)
{
    double dC = BitConverter.Int64BitsToDouble(0x3FDFFFFFFFFFFFFFL); // BitConverter.DoubleToInt64Bits(0.5d) - 1L

    double actual = Math.Truncate(double.IsNegative(d) ? d - dC : d + dC);
    double expected = Math.Round(d, MidpointRounding.AwayFromZero);

    Assert.That(actual, Is.EqualTo(expected));
}
```

All instructions involved (with test) have been tested locally in both release and debug modes, in both lowcq and highcq.

The titles Mario Strikers (1.0.0) and Super Smash Bros. U. (1.0.0) use these instructions intensively; to a lesser extent the title Mario Party Superstars (1.0.0).

### CODE REVIEW

**Comment by gdkchan** [comment]
Would be nice to apply this optimization to the Arm32 VCVT instructions aswell.

**Comment by LDj3SNuD** [comment]
> Would be nice to apply this optimization to the Arm32 VCVT instructions aswell.

Done.

**Review by gdkchan — APPROVED** [review]
LGTM, thanks! Great work.

**Comment by gdkchan** [comment]
Needs a rebase.

**Comment by LDj3SNuD** [comment]
> Needs a rebase.

Done.

**Review by AcK77 — APPROVED** [review]

**Pull request merged**
