### PR TITLE
Update Pro Controller Image + Trigger view

### PR DESCRIPTION
**Pull request by Shahil-Ayato**
This Updates the Pro controller Images to look more accurate to the original design, I've also added trigger views to help with assigning inputs. The Previous Design didn't fit well and I was not very happy with it, this new one looks much better in my opinion.

Before:
unkntytrown

After: 
unkgfhfghfghnown

### CODE REVIEW

**Review by ProFireDev — APPROVED** [review]
good idea, well implemented

**Comment by Ghostotakoi** [comment]
Would be great if somehow you could add visual feedback when you press a button or key.

**Review by ProFireDev — APPROVED** [review]
Automatically reapproved, but would you mind commenting what you changed

**Comment by Shahil-Ayato** [comment]
> Automatically reapproved, but would you mind commenting what you changed

I think before merging I’ll add a few things to make it more cosmetically appealing is all which I’ll try to commit tonight :)

**Comment by ProFireDev** [comment]
> > Automatically reapproved, but would you mind commenting what you changed
> 
> I think before merging I’ll add a few things to make it more cosmetically appealing is all which I’ll try to commit tonight :)

awesome, good work this makes things a lot nicer and a lot more user friendly.

**Comment by Shahil-Ayato** [comment]
Made the "-" and "+" along with the Home and Screenshot button more visible
Screenshot_20210330_134443

**Comment by Shahil-Ayato** [comment]
Ready for Review :)

**Review by Niwu34 — APPROVED** [review]
LGTM

**Review by Thog — APPROVED** [review]

**Review by AcK77 — APPROVED** [review]

**Pull request merged**
