### PR TITLE
New gamecard icons

### PR DESCRIPTION
**Pull request by SamusAranX**
I used photo references to draw up a more accurate gamecard icon. There's no wordmark for Ryujinx, so I just made a new one using the filetype font.

This commit contains all 5 filetype variants and one blank image, should other filetypes ever need an icon.
The fonts used are [Typold Bold](https://www.myfonts.com/products/bold-typold-255295) and [OCR B](https://fonts.adobe.com/fonts/ocr-b).

### CODE REVIEW

**Comment by gdkchan** [comment]
I don't tink it is necessary that it mentions "Ryujinx" on the game card icon.

**Review by IsaacMarovitz — APPROVED** [review]

**Comment by SamusAranX** [comment]
I just wanted to have *something* in that red top bar since the actual gamecards have the Nintendo Switch logo in there and the icon looks a little unbalanced with it blank. I can leave it blank though if there are no other suggestions.

**Comment by gdkchan** [comment]
I don't mind having "Ryujinx" written on it, I was just saying it is not necessary, in case you felt like it must have some branding somewhere.

**Comment by TSRBerry** [comment]
Do you have a 512x512 version for the blank one? If so we could also update the discord asset with that one!

**Review by TSRBerry — APPROVED** [review]

**Review by MutantAura — APPROVED** [review]

**Pull request merged**
