### PR TITLE
Correct type of executable sizes

### LINKED ISSUE #1792: Ryujinx's NSO Executable parser suffers integer overflow due to incorrectly treating sizes as INT
### What's the issue you encountered?

An NSO header contains a number of sections that specifies various sizes (TextSize, RoSize, BssSize , etc) which are stored as unsigned integers, a negative size does not make much sense after all.

Despite this Ryujinx's NSO Executable parser casts the sections to INT (See NsoExecutable.cs and other related files) this causes an integer overflow when any of the sections specifies a large size. The ProgramLoader.LoadNsos method has some UINT casts that seems to be designed to mitigate this issue somewhat but they don't seem to work.

The only documented case of this happening that I know of is with the game _Hatsune Miku Project DIVA Mega Mix_ and the DLC for the game _Hatsune Miku Project DIVA MEGA39_.

Specifically these games have a humongous BssSize like 3184323168 in the case of _Mega Mix_, which causes the BssSize to be interpreted as -1110644128.

This overflow ultimately ends up causing an InvalidMemRange crash, presumably due to the negative size causing havoc on the memory allocator.

Here is a screenshot showing the BssSize overflowing during debugging:

Integer_overflow

### How can the issue be reproduced?

Launch _Hatsune Miku Project DIVA Mega Mix_ with or without DLC or _Hatsune Miku Project DIVA MEGA39_ with DLC.

### Log file

Logs are not very relevant since they just report the InvalidMemRange error, but here is a log from _Hatsune Miku Project DIVA Mega Mix_ for completion's sake:
[Ryujinx_1.0.5995_2020-12-09_06-24-41.log](https://github.com/Ryujinx/Ryujinx/files/5663888/Ryujinx_1.0.5995_2020-12-09_06-24-41.log)

### Environment?

- Ryujinx version: 1.0.5995
- System Specs:
  - OS: Windows 10
  - CPU: I7-9700K
  - GPU: NVIDIA GTX 1080
  - RAM:  32GB
- Applied Mods : No

### Additional context?

It's worth noting that I looked into the NSO parsers for both LibHac and Yuzu to check if Ryujinx really was doing things incorrectly, and found that both of them treat the NSO sizes as UINT.

### PR DESCRIPTION
**Pull request by gdkchan**
Sizes can't be negative, so change the type to uint. Fixes #1792.

Affected titles:
https://github.com/Ryujinx/Ryujinx-Games-List/issues/237 (only non-JAP version)
https://github.com/Ryujinx/Ryujinx-Games-List/issues/338
https://github.com/Ryujinx/Ryujinx-Games-List/issues/469
https://github.com/Ryujinx/Ryujinx-Games-List/issues/1304
https://github.com/Ryujinx/Ryujinx-Games-List/issues/2540
https://github.com/Ryujinx/Ryujinx-Games-List/issues/2618
https://github.com/Ryujinx/Ryujinx-Games-List/issues/2901

### CODE REVIEW

**Comment by EmulationFanatic** [comment]
Fixes Death Mark 
image

**Comment by EmulationFanatic** [comment]
Super Chariot now boots and shows splash screens, though it only renders a black screen after that (separate issue).

**Comment by EmulationFanatic** [comment]
Fixes Darkest Dungeon 
image

**Comment by EmulationFanatic** [comment]
Fixes Hatsune Miku: Project DIVAMega Mix (US version)
image

**Comment by EmulationFanatic** [comment]
- CHAOS CODE - NEW SIGN OF CATASTROPHE now boots (though crashes with an audren error shortly thereafter)
image

**Comment by GamerzHell9137** [comment]
No more invalid mem range for Project Diva!
Base Profile Screenshot 2020 12 11 - 19 54 03 69

**Review by Thog — APPROVED** [review]

**Comment by EmulationFanatic** [comment]
Found another fixed game with this PR: Air Missions_HIND
2020-12-12 16_15_42-Ryujinx 1 0 6028 - Air Missions_ HIND v1 0 0 (01003D8011948000) (64-bit)

**Review by AcK77 — APPROVED** [review]

**Pull request merged**
