### PR TITLE
Implement R32_G32 TextureFormat

### PR DESCRIPTION
**Pull request by greggameplayer**

### CODE REVIEW

**Comment by SexyBabes** [comment]
FREE SEXY CAM GIRLS
**18+ ONLY**
GO TO http://sexygirls.com/

**Comment by greggameplayer** [comment]
@gdkchan Ban SexyBabes please

**Comment by ReinUsesLisp** [comment]
This needs a rebase since image management has changed.

**Comment by HorrorTroll** [comment]
Was rebase and merged on #383, need close this

**Pull request closed without merging**
