### PR TITLE
Build: Add R2R

### PR DESCRIPTION
**Pull request by imba-tjd**
This option will decrease startup time but increase build time.

### CODE REVIEW

**Review by Thog — CHANGES_REQUESTED** [review]
This should be done on the GitHub Action too

I'm also against this change as this explicitly need tiered compilation and we explicitly disable

**Comment by imba-tjd** [comment]
🆗

**Comment by Thog** [comment]
It might be worth revisiting the NVIDIA shutter first by enabling tiered compilation again and removing the thread pool hack we added in #1760 as I believe some stuffs have changed with .NET 6

**Comment by tyler274** [comment]
> It might be worth revisiting the NVIDIA shutter first by enabling tiered compilation again and removing the thread pool hack we added in #1760 as I believe some stuffs have changed with .NET 6

I don't have a Nvidia GPU on hand but I tested with tiered compilation disabled as is, and the [.NET 6 PublishReadyToRunComposite feature ](https://docs.microsoft.com/en-us/dotnet/core/deploying/ready-to-run#composite-readytorun) which is aimed at applications that explicitly need tiered compilation disabled. On AMD with the latest Vulkan branch rebase (as of this comment) things seem to run fine in SMT V with the following configuration 

```xml
   <PublishReadyToRunComposite>true</PublishReadyToRunComposite>
    <PublishReadyToRunEmitSymbols>false</PublishReadyToRunEmitSymbols>
    <PublishTrimmed>false</PublishTrimmed>
    <TieredCompilation>false</TieredCompilation>
    <TieredCompilationQuickJit>false</TieredCompilationQuickJit>
```

There were trim warnings with or without trim enabled in the `Ryujinx` project, but many of them were coming in from dependencies. 

Of course composite doesn't give a neatly packed executable either, but I thought it to be worth mentioning.

**Comment by Thog** [comment]
> > It might be worth revisiting the NVIDIA shutter first by enabling tiered compilation again and removing the thread pool hack we added in #1760 as I believe some stuffs have changed with .NET 6
> 
> I don't have a Nvidia GPU on hand but I tested with tiered compilation disabled as is, and the [.NET 6 PublishReadyToRunComposite feature ](https://docs.microsoft.com/en-us/dotnet/core/deploying/ready-to-run#composite-readytorun) which is aimed at applications that explicitly need tiered compilation disabled. On AMD with the latest Vulkan branch rebase (as of this comment) things seem to run fine in SMT V with the following configuration
> 
> ```
>    <PublishReadyToRunComposite>true</PublishReadyToRunComposite>
>     <PublishReadyToRunEmitSymbols>false</PublishReadyToRunEmitSymbols>
>     <TieredCompilation>false</TieredCompilation>
>     <TieredCompilationQuickJit>false</TieredCompilationQuickJit>
> ```
> 
> Of course composite doesn't give a neatly packed executable either, but I thought it to be worth mentioning.

I see I did inverted stuffs (again) about R2R.

imo for now it would be nice to reattempt to enable tiered compilation and do some bench around

**Comment by imba-tjd** [comment]
Feel free to proceed any change without merging this PR. :joy:
I'm a passer-by and made this trivial change only from my C# knowledge. I don't have experience on tiered compilation or GPU programming.
Since it's not simple to turn on R2R, the credit belongs to you maintainers.

**Pull request closed without merging**
