### PR TITLE
Add the stub applet instead of not implemented exception.

### PR DESCRIPTION
**Pull request by Chenj168**
This is a similar implementation of yuzu, 
the Diablo III Eternal Collection can be played.
hc

### CODE REVIEW

**Comment by B3astTech** [comment]
Iirc it was already implemented by someone within a project. It has not been pr'd yet or anything. But a stub of it isnt the best way to go

**Comment by gdkchan** [comment]
Which applet Diablo III requires?

**Comment by ReaperOfSouls1909** [comment]
> Which applet Diablo III requires?

controller applet

**Comment by gdkchan** [comment]
Controller applet is already implemented on #1003, so the only value added here is for other applets (not as frequently used).

**Comment by jduncanator** [comment]
I think as a project overall, we've made a concerted effort going forward to merging as minimal amount of stubs as possible, and avoiding large "catch-all" stubs at all costs (which this sort of is). As @gdkchan mentioned, the last commonly used applet is the controller applet which already has a PR open for it, so I'll close this one.

Thanks for the interest in the project, hope to see more PRs in the future :)

**Pull request closed without merging**
