### PR TITLE
Implement FCVTNS (Scalar GP)

### LINKED ISSUE #1570: Unimplemented FCVTNS instruction
### What CPU instruction is missing?

Requires the *FCVTNS* instruction.</br>

```
The instruction at 0x000000000aa6d684 (opcode 0x1e200148) is undefined!
```

### Instruction name
```
fcvtns w8, s10
```

### Required by: 

https://github.com/Ryujinx/Ryujinx-Games-List/issues/2549

### PR DESCRIPTION
**Pull request by saldabain**
Fixes #1570

### CODE REVIEW

**Comment by saldabain** [comment]
@Thog / @gdkchan can either of you restart the build process here?

**Comment by saldabain** [comment]
Reminder: Still needs review <3

**Review by gdkchan — APPROVED** [review]
lgtm, thanks.
I believe the PPTC version bump is not needed? The unimplemented instructions are usually not "cached" from what I recall, as they usually causes a crash right away.

**Review by Thog — APPROVED** [review]

**Comment by saldabain** [comment]
Every new cpu inst always had one in previous prs, if you’d prefer it to
not be there i can remove.

**Comment by gdkchan** [comment]
> Every new cpu inst always had one in previous prs, if you’d prefer it to not be there i can remove.

Your previous implementation (https://github.com/Ryujinx/Ryujinx/pull/2937) did not have it.

**Pull request merged**
