### PR TITLE
Prevent display sleep on macOS

### LINKED ISSUE #5616: Stop Screensaver from being activated when emulating a game [Bug] [macOS]
### Description of the issue

During cinematic exhibitions, macOS will start the system's screensaver due to the lack of user input.
This behavior shouldn't be allowed to happen, because the player is supposedly paying  attention to it.
One workaround  is the user to increase the time that takes for the screensaver to kick in, but it's not a proper solution.

Mortal Kombat 11 is a great example for this situation. 
Many times I had to stop everything and move the cursor to solve this.

### Reproduction steps

Choose a game with many long cinematics
Set the systems screensaver to kick in with 3 - 5 minutes or even less
Play the game and try to watch the cinematic, it will be interrupted many times.

### Log file

[Ryujinx_1.1.1000_2023-08-26_00-45-07.log.zip](https://github.com/Ryujinx/Ryujinx/files/12446138/Ryujinx_1.1.1000_2023-08-26_00-45-07.log.zip)

### OS

macOS 14 Beta 6

### Ryujinx version

1.1.1000

### Game version

1.0.26

### CPU

M1

### GPU

M1

### RAM

8GB

### List of applied mods

No mods applied

### Additional context?

_No response_

### PR DESCRIPTION
**Pull request by IsaacMarovitz**
Currently causes a BAD_ACCESS

Fixes #5616

### CODE REVIEW

**Comment by snotyak** [comment]
@IsaacMarovitz does this just need formatting fixed, or is there more to it?

**Comment by IsaacMarovitz** [comment]
> @IsaacMarovitz does this just need formatting fixed, or is there more to it?

Right now this implementation is broken and just runs into a crash. I haven't gotten around to fixing it.

**Comment by iMonZ** [comment]
Same issue on Linux

**Comment by AcK77** [comment]
The author said the PR implementation is currently broken and the PR hasn’t been update since 4 months, so I close it. Feel free to update it with a working solution and we could reopen the PR, or open a new one is fine too. Thanks.

**Pull request closed without merging**
