### PR TITLE
Implement R32B24G8, A4B4G4R4, Z16 texture formats

### PR DESCRIPTION
**Pull request by yourmothergay**
this fixes issue #317

### CODE REVIEW

**Comment by greggameplayer** [comment]
have you tested these on some games ?

**Comment by yourmothergay** [comment]
no

**Comment by HorrorTroll** [comment]
Oceanhorn: Monster of Uncharted Seas need Z16, and it's work perfectly nothing corrupt

**Comment by greggameplayer** [comment]
ok i think other games need Z16 but i don't remember what games

**Comment by ReaperOfSouls1909** [comment]
Confirmed fixes my issues thanks 
unknown

**Comment by ReinUsesLisp** [comment]
This needs a rebase since image management has changed.

**Comment by HorrorTroll** [comment]
i think we should close this

**Pull request closed without merging**
