### PR TITLE
Imgbot wanted to do this while I was adding changes to the GtkDialog for my current PR.

### PR DESCRIPTION
**Pull request by Mou-Ikkai**
<details>
<summary>
Details
</summary>

| File | Before | After | Percent reduction |
|:--|:--|:--|:--|
| /Ryujinx/Ui/Resources/Logo_GitHub.png | 26.25kb | 15.48kb | 41.04% |
| /Ryujinx/Ui/Resources/Logo_Discord.png | 13.29kb | 7.89kb | 40.63% |
| /Ryujinx/Ui/Resources/Logo_Patreon.png | 15.12kb | 9.79kb | 35.27% |
| /Ryujinx/Ui/Resources/Icon_NRO.png | 13.58kb | 11.06kb | 18.50% |
| /Ryujinx/Ui/Resources/Icon_NCA.png | 13.35kb | 10.96kb | 17.92% |
| /Ryujinx/Ui/Resources/Icon_NSO.png | 13.62kb | 11.20kb | 17.76% |
| /Ryujinx/Ui/Resources/Icon_XCI.png | 12.79kb | 10.53kb | 17.61% |
| /Ryujinx/Ui/Resources/Icon_NSP.png | 12.89kb | 10.66kb | 17.32% |
| /Ryujinx/Ui/Resources/Logo_Twitter.png | 16.54kb | 14.40kb | 12.93% |
| /Ryujinx/Ui/Resources/Controller_JoyConPair.svg | 74.83kb | 65.64kb | 12.28% |
| /Ryujinx/Ui/Resources/Controller_ProCon.svg | 115.17kb | 105.49kb | 8.41% |
| /Ryujinx/Ui/Resources/Controller_JoyConRight.svg | 87.82kb | 80.99kb | 7.77% |
| /Ryujinx.HLE/RyujinxProfileImage.jpg | 51.73kb | 47.85kb | 7.49% |
| /Ryujinx/Ui/Resources/Controller_JoyConLeft.svg | 73.68kb | 68.34kb | 7.25% |
| /Ryujinx/Ui/Resources/Logo_Ryujinx.png | 52.52kb | 51.76kb | 1.45% |
| | | | |
| **Total :** | **593.19kb** | **522.06kb** | **11.99%** |
</details>

### CODE REVIEW

**Comment by AcK77** [comment]
I don’t see the advantage to reduce the images size of 70kb when our build package is around 70mb.
I’ll close this PR because of that, if anyone have a good reason to think it could be useful, we could reopened it!

**Comment by gdkchan** [comment]
I think the change is valid, if we can reduce the image binary size without any loss, then why not?

**Comment by jduncanator** [comment]
I'm happy to accept this change so long as the compression was lossless and not lossy. Can you confirm @Mou-Ikkai?

**Comment by Mou-Ikkai** [comment]
Imgbot uses lossless compression, have fun.

**Comment by Mou-Ikkai** [comment]
> I'm happy to accept this change so long as the compression was lossless and not lossy. Can you confirm @Mou-Ikkai?
> 
> Also, why were a bunch of .svg files removed? Are they not used anymore?

Though also, what do you mean by your edited part about "removed .svg files"?

**Comment by jms-c** [comment]
It seems that it shrinks svgs by putting it all on one line.
That confused me when I looked.

**Review by ProFireDev — APPROVED** [review]

**Comment by AcK77** [comment]
Needs a rebase

**Comment by Mou-Ikkai** [comment]
Rebasing.

**Pull request closed without merging**
