### PR TITLE
Use RGBA16 vertex format if RGB16 is not supported on Vulkan

### PR DESCRIPTION
**Pull request by gdkchan**
This is an alternative to #3529. It solves the same problem, but using a different approach. Rather than using a format that has the same size but different type, this uses a format that has the same type but different size. The fact that it has the same type means that no conversion on the shader is required, but it brings other potential issues which is why I didn't want to use this approach before:
- The fact that this format is larger means that its size may be greater than offset + stride, which is invalid according to the spec.
- If the shader attempts to access the last component which should not exist, it will read garbage (the whatever is next in the vertex buffer) rather than 0.
- This can cause out of bounds access of the vertex buffer (by 2 bytes).

Puting this here for testing since we had a issue reported with the other approach.

### CODE REVIEW

**Comment by rabidcopy** [comment]
Appears to work as an alternative. No perceivable difference between #3529 and #3552 for my GPU. Two observed issues that affect both are as follows.

Clouds on the title screen disappear briefly

https://user-images.githubusercontent.com/8052832/183205431-c06255e8-810c-4ced-bf23-2947bdb0cddb.mp4

Particular foliage renders like this, more noticeable in an earlier area of the game, foliage at a reasonable distance seems unaffected but the closer you get the more prone it is to happening.

ryujinx_capture_2022-08-05_16-11-44

**Comment by gdkchan** [comment]
Is that on Linux or Windows?

**Comment by rabidcopy** [comment]
> Is that on Linux or Windows?

Windows but I'm fairly confident I experienced the same on Linux. I will double-check shortly.

**Comment by rabidcopy** [comment]
I can't reproduce the cloud issue on Linux. However the foliage issue remains. Unexpectedly there was a much worse issue that cropped up. As soon as I loaded into my save which is currently at the first desert area you encounter in the game, the emulator begins to freeze up and eventually does this to the display manager. Only way to recover is to turn off the computer or bring up a virtual terminal and kill the xfce4-session.




[Ryujinx_1.1.0+d517234_2022-08-05_17-11-10.log](https://github.com/Ryujinx/Ryujinx/files/9273828/Ryujinx_1.1.0%2Bd517234_2022-08-05_17-11-10.log)
[Ryujinx_1.1.0+d517234_2022-08-05_17-03-18.log](https://github.com/Ryujinx/Ryujinx/files/9273829/Ryujinx_1.1.0%2Bd517234_2022-08-05_17-03-18.log)
(Will provide a log for #3552 with debug logging and backend logging enabled shortly)

**Comment by CloneIX** [comment]
Donot knowif this helps, but the "Device lost" error is still there with this version:

00:05:26.241 |E| GPU.MainThread Gpu : VK Sync Object 541021 failed to signal within 1000ms. Continuing...
00:05:27.241 |E| GPU.MainThread Gpu : VK Sync Object 541022 failed to signal within 1000ms. Continuing...
00:05:28.056 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorDeviceLost".
   at Ryujinx.Graphics.Vulkan.CommandBufferPool.Return(CommandBufferScoped cbs, ReadOnlySpan`1 waitSemaphores, ReadOnlySpan`1 waitDstStageMask, ReadOnlySpan`1 signalSemaphores) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\CommandBufferPool.cs:line 299
   at Ryujinx.Graphics.Vulkan.PipelineFull.FlushCommandsImpl() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\PipelineFull.cs:line 215
   at Ryujinx.Graphics.Vulkan.SyncManager.Create(UInt64 id) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\SyncManager.cs:line 46
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_4(Span`1 memory, ThreadedRenderer threaded, IRenderer renderer) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\CommandHelper.cs:line 62
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 130
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RunLoop(Action gpuLoop) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 107
   at Ryujinx.Ui.RendererWidgetBase.Render() in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\RendererWidgetBase.cs:line 399
   at System.Threading.Thread.StartCallback()

**Comment by MutantAura** [comment]
> Donot knowif this helps, but the "Device lost" error is still there with this version:

This PR attempts to fix the AMD crash on boot. It does not attempt to solve the random device loss crashes on Vulkan in general.

**Comment by scol1951** [comment]
1.1.0+0f264c0
Game version:1.1.0

System Specs:

OS: Windows 10
CPU: Ryzen 5 5800X
GPU: AMD 5700
GPU Driver: AMD Software: Adrenalin Edition 22.7.1
RAM: 16GB

purge pptc cache
purge shader cache
The title screen error is gone.
The grass problem is still there.
The graphics driver hangs seems to be gone.
It seems that xc3 is more stuttering than other games.
[Ryujinx_1.1.0+0f264c0_2022-08-07_09-14-44.log]
ryujinx_capture_2022-08-07_09-16-14
ryujinx_capture_2022-08-07_09-17-14
(https://github.com/Ryujinx/Ryujinx/files/9275959/Ryujinx_1.1.0%2B0f264c0_2022-08-07_09-14-44.log)

**Comment by GenericMeow** [comment]
Thought I'd help with the testing a bit. Tested both #3529 and #3552 - game no longer crashes on boot but they are both hit hard by vertex explosions/flickering most obvious starting with chapter 4 which makes it a lot less playable from that point. Also both versions show black grass and second version - 3552 - seems to exhibit (more) stutter compared to the other version.

Win 10, 6700XT, 22.7.1 driver, 1.1.0 game version, Vulkan

Vulkan issue RyujinX

**Review by riperiperi — APPROVED** [review]
LGTM.

**Review by CloneDeath — APPROVED** [review]

**Comment by KawaiiDinosaur** [comment]
Arch Linux
AMD RX 5700 XT (mesa 22.1.6)

With this PR, Xenoblade Chronicles 3 finally reaches the title screen, but my whole system hangs while doing so. The log outputs:

```
00:03:34.976 |I| .NET ThreadPool Worker Ptc Save: Saved Profiling Info (size: 65668 bytes, profiled functions: 19928).
00:03:38.435 |E| HLE.GuestThread.19 Gpu : VK Sync Object 3138 failed to signal within 1000ms. Continuing...
00:03:39.449 |E| HLE.GuestThread.19 Gpu : VK Sync Object 3138 failed to signal within 1000ms. Continuing...
00:03:43.748 |E| Gpu AwaitResult: Error: Query result SamplesPassed timed out. Took more than 5000 tries.
00:03:48.435 |E| HLE.GuestThread.19 Gpu : VK Sync Object 3142 failed to signal within 1000ms. Continuing...
00:03:49.449 |E| Gpu : VK Sync Object 3142 failed to signal within 1000ms. Continuing...
00:03:58.489 |E| HLE.GuestThread.19 Gpu : VK Sync Object 3146 failed to signal within 1000ms. Continuing...
00:03:59.502 |E| HLE.GuestThread.19 Gpu : VK Sync Object 3146 failed to signal within 1000ms. Continuing...
00:04:03.803 |E| Gpu AwaitResult: Error: Query result SamplesPassed timed out. Took more than 5000 tries.
00:04:04.975 |I| .NET ThreadPool Worker Ptc Save: Saved Profiling Info (size: 65794 bytes, profiled functions: 19965).
00:04:08.489 |E| HLE.GuestThread.19 Gpu : VK Sync Object 3150 failed to signal within 1000ms. Continuing...
00:04:09.502 |E| Gpu : VK Sync Object 3150 failed to signal within 1000ms. Continuing...
00:04:18.542 |E| HLE.GuestThread.19 Gpu : VK Sync Object 3153 failed to signal within 1000ms. Continuing...
00:04:19.555 |E| Gpu : VK Sync Object 3154 failed to signal within 1000ms. Continuing...
00:04:20.569 |E| HLE.GuestThread.19 Gpu : VK Sync Object 3154 failed to signal within 1000ms. Continuing...
00:04:28.542 |E| Gpu : VK Sync Object 3157 failed to signal within 1000ms. Continuing...
00:04:29.559 |E| Gpu : VK Sync Object 3158 failed to signal within 1000ms. Continuing...
00:04:38.572 |E| HLE.GuestThread.19 Gpu : VK Sync Object 3161 failed to signal within 1000ms. Continuing...
00:04:39.585 |E| Gpu : VK Sync Object 3162 failed to signal within 1000ms. Continuing...
00:04:40.595 |E| HLE.GuestThread.19 Gpu : VK Sync Object 3162 failed to signal within 1000ms. Continuing...
00:04:48.595 |E| Gpu : VK Sync Object 3165 failed to signal within 1000ms. Continuing...
00:04:49.609 |E| Gpu : VK Sync Object 3166 failed to signal within 1000ms. Continuing...
00:04:58.622 |E| Gpu : VK Sync Object 3170 failed to signal within 1000ms. Continuing...
00:04:59.635 |E| HLE.GuestThread.19 Gpu : VK Sync Object 3170 failed to signal within 1000ms. Continuing...
00:05:08.649 |E| Gpu : VK Sync Object 3173 failed to signal within 1000ms. Continuing...
00:05:09.662 |E| Gpu : VK Sync Object 3174 failed to signal within 1000ms. Continuing...
00:05:18.675 |E| Gpu : VK Sync Object 3177 failed to signal within 1000ms. Continuing...
00:05:19.689 |E| Gpu : VK Sync Object 3178 failed to signal within 1000ms. Continuing...
00:05:20.702 |E| HLE.GuestThread.19 Gpu : VK Sync Object 3178 failed to signal within 1000ms. Continuing...
00:05:28.702 |E| Gpu : VK Sync Object 3181 failed to signal within 1000ms. Continuing...
00:05:29.715 |E| Gpu : VK Sync Object 3182 failed to signal within 1000ms. Continuing...
00:05:38.729 |E| HLE.GuestThread.19 Gpu : VK Sync Object 3185 failed to signal within 1000ms. Continuing...
00:05:39.742 |E| Gpu : VK Sync Object 3186 failed to signal within 1000ms. Continuing...
00:05:40.755 |E| HLE.GuestThread.19 Gpu : VK Sync Object 3186 failed to signal within 1000ms. Continuing...
00:05:48.755 |E| Gpu : VK Sync Object 3189 failed to signal within 1000ms. Continuing...
00:05:49.769 |E| Gpu : VK Sync Object 3190 failed to signal within 1000ms. Continuing...
00:05:58.835 |E| HLE.GuestThread.19 Gpu : VK Sync Object 3194 failed to signal within 1000ms. Continuing...
00:06:03.124 |E| Gpu AwaitResult: Error: Query result SamplesPassed timed out. Took more than 5000 tries.
00:06:08.809 |E| HLE.GuestThread.19 Gpu : VK Sync Object 3198 failed to signal within 1000ms. Continuing...
00:06:09.822 |E| Gpu : VK Sync Object 3198 failed to signal within 1000ms. Continuing...
00:06:18.865 |E| HLE.GuestThread.19 Gpu : VK Sync Object 3202 failed to signal within 1000ms. Continuing...
00:06:19.875 |E| HLE.GuestThread.19 Gpu : VK Sync Object 3202 failed to signal within 1000ms. Continuing...
00:06:24.169 |E| Gpu AwaitResult: Error: Query result SamplesPassed timed out. Took more than 5000 tries.
```

**Review by Thog — APPROVED** [review]

**Pull request merged**
