### PR TITLE
Match texture if the physical range is the same

### PR DESCRIPTION
**Pull request by gdkchan**
#1905 changed the behavior of exact texture matches a little bit. Instead of comparing the physical address (CPU VA) and assuming it is contiguous, it was changed to compare the GPU VA instead (as physical regions might not be contiguous). This change makes it closer to the previous behavior, it now compares the physical regions if the virtual address is not the same (see the new `CompareRange` method), and allows a match if the virtual addresses are different, but mapped to the same physical region.

This seems to fix (or at least greatly improve) a regression on Rune Factory 4 Special caused by the aforementioned PR.

NOTE: This has the potential to slow things down if the slow path that calls `CompareRange` is hit frequently, which is the reason I was only compared the GPU virtual addresses.

### CODE REVIEW

**Comment by GamerzHell9137** [comment]
Kinda 
image

**Review by AcK77 — APPROVED** [review]

**Review by riperiperi — APPROVED** [review]
LGTM

**Comment by GamerzHell9137** [comment]
There was a regression in NSMBUD too which is being fixed with the pr

Before:
image

After: 
image

Way of triggering: Getting into a stage and choosing another one after it, textures from the older stage are being applied to the new one.

**Review by Thog — APPROVED** [review]
lgtm

**Pull request merged**
