### PR TITLE
Fix calls passing V128 values on Linux

### LINKED ISSUE #2805: [Regression][Linux] Pokemon Sw/Sh cannot load saves anymore
### What's the issue you encountered?

The game shows a "your data is corrupted" message.
My savefile has been imported with success on real hardware, meaning this is a ryujinx regression.

### How can the issue be reproduced?

valid pokemon sword v1.3.2 save
[pkmsw132.zip](https://github.com/Ryujinx/Ryujinx/files/7461956/pkmsw132.zip)

### Log file
[Ryujinx_1.0.7096_2021-11-02_15-53-40.log.zip](https://github.com/Ryujinx/Ryujinx/files/7461870/Ryujinx_1.0.7096_2021-11-02_15-53-40.log.zip)

### Environment?

- Ryujinx version: 1.0.7096
- Game version: 1.3.2</br>
- System Specs:
  - OS: *ArchLinux*
  - CPU: *i5-1035g7*
  - GPU: *iris plus 940*
  - RAM: *16gb*
- Applied Mods : no

### LINKED ISSUE #2864: Splatoon 2 crashes with "***Stack Smashing Detected***: Terminated" with the 5.5.0 Update
### What's the issue you encountered?

If I attempt to boot up Splatoon 2 with the 5.5.0 update on any Linux distro, I would get the error "Stack Smashing Detected," which causes Ryujinx to crash. I have tried this with both Arch Linux and Ubuntu. Regular Ryujinx Logs don't show any apparent errors since it seems to be glibc throwing errors (debug log provided)
If this helps, I do have the 60fps lobby and Disable Dynamic Resolution mods there, both of which function on non-Multithreading Master builds and LDN 2.3.

### How can the issue be reproduced?

1. On Linux, boot up Ryujinx
2. Apply Splatoon 2's 5.5.0 Update
3. Attempt to boot said game

### Log file

[gdbTerm_Splatoon2_5.5.0.txt](https://github.com/Ryujinx/Ryujinx-Games-List/files/7574870/gdbTerm_Splatoon2_5.5.0.txt)
This was generated from the Terminal. I used gdb to debug the game.

### Environment?

- Ryujinx version: 1.0-7106
- Game version: 5.5.0
- System Specs:
  - OS: Arch Linux
  - CPU: Ryzen 7 3800X
  - GPU: AMD Radeon RX 5700 (with RX 5700 XT BIOS)
  - RAM: 32GB DDR4-3733
- Applied Mods : Yes (60fps Lobby, Disable Dynamic Resolution)*

*to be honest, I can remove those mods and get the same error.

### Additional context?

If I remove the 5.5.0 update, the game will boot.
[Ryujinx_1.0.7106_2021-11-20_11-36-12.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/7574874/Ryujinx_1.0.7106_2021-11-20_11-36-12.log)

### LINKED ISSUE #3024: Save file corruption in Pokemon Sword (Linux)
### What's the issue you encountered?
If there's a save file present in Pokemon Sword's save  directory, launching the game always results in the screen seen below.

Pkmn Sword Save Corruption

### How can the issue be reproduced?

1. Launch the game without a save
2. Save in game
3. Close the emulator
4. Launch the game again

**Alternatively:**

1. Copy a save file to the game's user save directory
2. Launch the game.

### Log file

[Ryujinx_1.0.0+9e1316e_2022-01-22_09-15-13.log](https://github.com/Ryujinx/Ryujinx/files/7918417/Ryujinx_1.0.0%2B9e1316e_2022-01-22_09-15-13.log)

### Environment?

- Ryujinx version: 1.0.7181.</br>
- Game version: 1.3.2</br>
- System Specs:
  - OS: Arch Linux
  - CPU: i5 10400F
  - GPU: RX 480 4GB
  - RAM: 16GB
- Applied Mods : No
### Additional context?
I'm not sure, but it seems to only happen while running the emulator under linux. Windows doesn't seem to have this issue.

### LINKED ISSUE #3028: Crash on Feature "Memory Manager Mode" on "Software" in Linux
### What's the issue you encountered?

The Setting "Memory Manager Mode" "Software" Does not seem to be working on Linux. 
I am not to sure if its distro dependent or not, So if any Linux users out there could test their distro on this front please do!

This is what it reports back on the end of the lines of the Log:
`00:00:06.106 |E| HLE.GuestThread.14 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: va=0x000055E6D1BA1E64, size=0x0000000000000008
   at Ryujinx.Cpu.MemoryManager.AssertValidAddressAndSize(UInt64 va, UInt64 size) in D:\a\Ryujinx\Ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 479
   at Ryujinx.Cpu.MemoryManager.SignalMemoryTracking(UInt64 va, UInt64 size, Boolean write, Boolean precise) in D:\a\Ryujinx\Ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 572
   at Ryujinx.Cpu.MemoryManager.ReadTracked[T](UInt64 va) in D:\a\Ryujinx\Ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 126`

### How can the issue be reproduced?

Starting Ryujinx Open "System" Tab in The Settings menu find Memory Manager Mode and select Software, Apply the settings and go into a 64bit game and it should crash no matter the game.

image

### Log file

[Ryujinx_1.1.4_2022-01-22_17-25-15.log](https://github.com/Ryujinx/Ryujinx/files/7919408/Ryujinx_1.1.4_2022-01-22_17-25-15.log)

### Environment?

- Ryujinx version: 1.1.4</br>
- Game version: N/A</br>

- System Specs:
  - OS: *Fedora 35*
  - CPU: *i7-2600k*
  - GPU: *1050ti*
  - RAM: *16GB*
- Applied Mods : [N/A]

### Additional context?

Additional info about your environment:</br>

I have tired this on multiple devices with The same distro and it seems to be same all around.
Ryujinx ends up crashing at the end of this, I have tested 32bit games and did not seem to effect them. This error only occurs on All 64bit game's I tried 4 different games about 2 to 3 times before making a issue on this.

I have troubleshooted on my end I also went to windows tried it worked and copied entire Ryujinx config and used it on my distro and crashed.

I did try the other mem manager mode's and the other two did not seem to have issues from what I had seen.

### PR DESCRIPTION
**Pull request by gdkchan**
This fixes a regression introduced on #2515 where in some cases, during the pre-allocation stage, the new register operations would not be added to the call operation node. This would cause the register allocator to not keep track of the fixed registers (possibly overwriting the register values), and also to do register allocation for the operands passed on the call (which it should not, calls are supposed to be entirely handled by the pre-allocator, as the ABI requires each argument to be passed on a specific register or stack offset).

This only affects Linux, and mostly calls that passes V128 values (those are passed on a pair of 2 general purpose registers on Linux).

Fixes #2805, fixes #2864, fixes #3024 and fixes #3028.
Yes, that fixes the save file corrupted error on Pokémon Sword/Shield.
Testing is welcome.

Note for people testing this: Existing saves created on any version after the linked PR was merged are most likely actually corrupted, so you'll need to delete them. Saves created before the bug was introduced (or created on Windows) should be fine.

### CODE REVIEW

**Comment by riperiperi** [comment]
May also fix #2864.

**Comment by B3astTech** [comment]
Pkm Sword is working as it should

Using Windows save and works perfectly. I went in-game re-saved and rebooted ryujinx and it worked as it should.

image

image

**Comment by B3astTech** [comment]
#### (Splatoon 2 crashes with "***Stack Smashing Detected***: Terminated" with the 5.5.0 Update)
I had splatoons on hand and tried it

image

image

**Review by riperiperi — APPROVED** [review]

**Comment by gdkchan** [comment]
Note for people testing this: Existing saves created on any version after the linked PR was merged are most likely actually corrupted, so you'll need to delete them. Saves created before the bug was introduced (or created on Windows) should be fine.

**Comment by B3astTech** [comment]
This may also fix #2350 it seems to have a simular crash. But don't quote me on this. Because I'm fairly unsure myself

**Pull request merged**
