### PR TITLE
misc: Sync Config.json default debug config

### PR DESCRIPTION
**Pull request by Thog**
As title say.

### CODE REVIEW

**Review by AcK77 — APPROVED** [review]

**Review by gdkchan — APPROVED** [review]
Can't we just delete this file? Since the emulator can generate it anyway. Seems like it would be one thing less to worry about.

**Comment by Thog** [comment]
> Can't we just delete this file? Since the emulator can generate it anyway. Seems like it would be one thing less to worry about.

I guess I could do a follow up removing that file and the schema tbh yeah

**Comment by jduncanator** [comment]
Why remove the schema, the schema is there so IDEs (and eventually Ryujinx) can verify the .json file is valid, and can provide type hinting and "Intellisense" when editing the JSON file directly.

**Comment by Thog** [comment]
> Why remove the schema? The schema is there so IDEs (and eventually Ryujinx) can verify the .json file is valid, and can provide type hinting and "Intellisense" when editing the JSON file directly.

Considering that no one update it (or miss to do so), I do not think it's too useful as it.

**Pull request merged**
