### PR TITLE
HLE: Deal with empty title names properly

### PR DESCRIPTION
**Pull request by TSRBerry**
This restores the behavior we had before #4480 to read title names in case the name of the desired language is empty.

### CODE REVIEW

**Comment by TSRBerry** [comment]
I thought it wouldn't even have array entries if they are empty, that's why I added these checks:
https://github.com/Ryujinx/Ryujinx/blob/63dedbda862533342fd8fac148f0c1d6427c9d84/Ryujinx.HLE/Loaders/Processes/ProcessResult.cs#L55-L57

But clearly they weren't enough.

**Comment by gdkchan** [comment]
Actually I think they are since some languages were only added later, so on older games they probably don't exist and the array is smaller.

**Comment by gdkchan** [comment]
> The array should always have the same size, not sure how it behaves with languages which were added later. https://github.com/Thealexbarney/LibHac/blob/6f6836c302aace7b37d4957746b17c2152aaa7b5/src/LibHac/Ns/ApplicationControlProperty.cs#L10
> 
> Do I keep the checks, or should I remove them?

Yea, I just checked and it seems that this size was always fixed to 16 entries (so they were smart enough to keep some "reserved" entries from the beginning that they used later). So I believe you can remove the bounds check.

**Review by marysaka — APPROVED** [review]

**Review by gdkchan — APPROVED** [review]
lgtm, thanks.

**Pull request merged**
