### PR TITLE
Some minor formal wording for the updater.

### PR DESCRIPTION
**Pull request by Mou-Ikkai**
This makes the updater use a bit more formal wording. Easier for people to understand in one try. Especially with changing "most updated version" to "latest version".

### CODE REVIEW

**Comment by jms-c** [comment]
In my opinion, this looks good.
Note for developers : This is a string modification, no chance of issues other than unedited strings.

**Comment by Mou-Ikkai** [comment]
[Download Ryujinx](https://w.ryujinx.org/dl/2060)
*Thanks jms-c*

**Review by jduncanator — APPROVED** [review]
Looks good, thanks!

**Comment by jms-c** [comment]
Appveyor ci seemed to build incorrectly. Manual build returns different results.

**Comment by jms-c** [comment]
Mistake found:
Line 142 not updated.

**Comment by Mou-Ikkai** [comment]
Got it... Wonder why my text editor didn't show it.

**Comment by Mou-Ikkai** [comment]
Poke.

**Review by Thog — APPROVED** [review]
lgtm, thanks 👍

**Pull request merged**
