### PR TITLE
Rename Hipc to Cmif where appropriate

### PR DESCRIPTION
**Pull request by Thealexbarney**

### CODE REVIEW

**Review by marysaka — APPROVED** [review]
lgtm, I do believe we should probably someday rename `Ipc` to `IPC` everywhere

**Comment by Thealexbarney** [comment]
> lgtm, I do believe we should probably someday rename `Ipc` to `IPC` everywhere

`Ipc` already follows the standard naming style while `IPC` doesn't

**Comment by TSRBerry** [comment]
I rebased this PR, hope this was okay. (Still have the original here, so I can revert if it wasn't.)

When this was created we didn't have the Ryujinx.Horizon projects, so these aren't adjusted here.
I wasn't 100% sure if they need to be adjusted, so I didn't do it.

@Thealexbarney let me know if you can take a look again or if you want me to do this.

**Comment by Thealexbarney** [comment]
I thought this was fixed in the recent IPC PRs. Is that not the case?

**Comment by TSRBerry** [comment]
Uhm, at least not that I know of :sweat_smile:

**Comment by Thealexbarney** [comment]
Apparently I was thinking of `CmifCommandAttribute` which is only used in a few places

**Comment by TSRBerry** [comment]
@Thealexbarney Could you answer this question I asked a few comments above?

> let me know if you can take a look again or if you want me to do this.

**Comment by Thealexbarney** [comment]
The rebase looks fine to me. Looking at Ryujinx.Horizon, it appears that naming between HIPC/CMIF was done properly there. I don't have an IDE open right now, and GitHub won't let you search PRs, so I can't easily check if there were any other incorrectly named HIPC symbols that were added recently. If there weren't, then the rebase looks fine

**Review by gdkchan — APPROVED** [review]
This is already correct on the new IPC system, but I guess it doesn't hurt to rename it on the old implementation too.

**Pull request merged**
