### PR TITLE
gpu: Implement missing texture formats

### PR DESCRIPTION
**Pull request by AcK77**
This PR implement some missing texture formats:

- D24UnormS8Uint
- Etc2RgbaUnorm
- Etc2RgbaSrgb

Needed by:
https://github.com/Ryujinx/Ryujinx-Games-List/issues/1528
https://github.com/Ryujinx/Ryujinx-Games-List/issues/2348
https://github.com/Ryujinx/Ryujinx-Games-List/issues/2331
(and maybe more...)

image
image

### CODE REVIEW

**Review by gdkchan — APPROVED** [review]
lgtm, thanks for fixing this 👍

**Comment by EmulationFanatic** [comment]
Sky Gamblers - Afterburner might've improved but it's hard to tell, as the screen is still mostly gobbledygook rendering at less than 1FPS.
2021-01-04 15_43_45-Ryujinx 1 0 6228 - Sky Gamblers - Afterburner v1 0 0 (010003F00CC98000) (64-bit)

**Comment by EmulationFanatic** [comment]
After your latest commits, Sky Gamblers - Afterburner has seen some improvement.
image
image
image

**Review by Thog — APPROVED** [review]

**Comment by GamerzHell9137** [comment]
Dragon Quest Builders is not showing
```000056.539 E GUI.RenderLoop Gpu GetInfo Invalid texture format 0x48A29 (sRGB False).```

in the command window anymore with this PR. There's no graphical changes with the change.

**Pull request merged**
