### PR TITLE
OpenGL: Limit vertex buffer range for non-indexed draws

### PR DESCRIPTION
**Pull request by gdkchan**
OpenGL does not allow the vertex buffer size to be specified, which means that out of bounds fetches from draws might be able to access regions of the buffer that it shouldn't. In order to make the behavior consistent with the Switch GPU here, this change makes a copy of the vertex buffer data into a temporary buffer if the draw might do a out of bounds access. The temporary buffer is then bound as vertex buffer and used on the draw.

This fixes the triangle glitch on fog/smoke on Super Mario Odyssey.
Before:
image
After:
image
Only affects OpenGL, Vulkan *sort of* doesn't have this isssue since it does allow the vertex buffer size to be specified with an extension, but some drivers ignores it so we might still need a similar solution there.

Captain Toad: Treasure Tracker had a similar issue, I did not test this one but from what I recall, it should be fixed too.

Testing is welcome, also to ensure that there's no performance regressions with this change.

### CODE REVIEW

**Comment by MetrosexualGarbodor** [comment]
Apparently fixes #3530.

https://user-images.githubusercontent.com/79612681/182729166-af52b01c-cbd9-4828-a4c4-88d196b01938.mp4

**Comment by jduncanator** [comment]
> Apparently fixes #3530.
> 
>  2022-08-04.00-16-58.mp4

This change only includes updates to the OpenGL backend, in your video you're using the Vulkan backend. It's not possible for this PR to have changed the behaviour of XB3 in Vulkan. What you're seeing is a placebo.

**Comment by MetrosexualGarbodor** [comment]
Well, I forgot I was recording Vulkan, my bad. But everyone else is reporting no more TDRs on OpenGL. Since I can't use my PC right now, I'll leave it to someone else to post a video.

**Comment by OldManKain** [comment]
**Confirmed** OpenGL is fixed.

https://user-images.githubusercontent.com/47503099/182733848-c8783c3f-b525-494d-af1e-d90a65eb915b.mp4

**Comment by PhiZero** [comment]
Another success story here.

https://user-images.githubusercontent.com/7350221/182735932-fafbb235-970d-4ee2-8e1f-635166ebda07.mp4

I was consistently crashing since Friday, without fail. Been testing Xenoblade Chronicles 3 daily. Now I cannot crash anymore, and I've tried everything that previously gave me a guaranteed crash. Cleared my shader cache as well to get a fresh test case.

**Comment by S0gnat0re** [comment]
> Apparently fixes #3530.
> 
>  2022-08-04.00-16-58.mp4

Not on my end

> 01:58:57.140 |E| HLE.GuestThread.19 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000003F6F264000.
01:58:57.191 |E| HLE.GuestThread.19 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise) in D:\a\Ryujinx\Ryujinx\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 252
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Translation\Translator.cs:line 168
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 32
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 40
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1265

[Ryujinx_1.1.0+b6f2014_2022-08-04_06-17-25.log](https://github.com/Ryujinx/Ryujinx/files/9257167/Ryujinx_1.1.0%2Bb6f2014_2022-08-04_06-17-25.log)

**Comment by riperiperi** [comment]
This is not the same crash. The crash this PR supposedly fixes is a shader causing a TDR, which logs as "GL Sync Point timed out" then silently closes the emulator.

**Comment by PhiZero** [comment]
> > Apparently fixes #3530.
> > 2022-08-04.00-16-58.mp4
> 
> Not on my end
> 
> > 01:58:57.191 |E| HLE.GuestThread.19 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.

Please refrain from running any cheats/mods when testing PRs. In this case, your 60 FPS cheat is causing these issues. This has been confirmed by myself and the creator of said cheat.

**Comment by S0gnat0re** [comment]
> This is not the same crash. The crash this PR supposedly fixes is a shader causing a TDR, which logs as "GL Sync Point timed out" then silently closes the emulator.

I see

> Please refrain from running any cheats/mods when testing PRs. In this case, your 60 FPS cheat is causing these issues. This has been confirmed by myself and the creator of said cheat.

I have, it was not your mod causing it as it was disabled, it also happened while closing the menu after deleting it entirely

**Comment by MetrosexualGarbodor** [comment]
After playing for about 6 hours today with no crashes, I think it's safe to say the OpenGL TDR is fixed by this PR.

**Comment by riperiperi** [comment]
Some more tests on other games would be good to make sure nothing broke & nothing else got slower.

**Review by Thog — APPROVED** [review]

**Comment by MutantAura** [comment]
> Some more tests on other games would be good to make sure nothing broke & nothing else got slower.

Went through my usual test suite:
BoTW, PLA, RTDX, SMO, SSHD, MHR and a few others and didn't notice any regressions to rendering or performance in OpenGL 👍

**Review by riperiperi — APPROVED** [review]

**Pull request merged**
