### PR TITLE
Truncate vertex attribute format if it exceeds stride on MoltenVK

### PR DESCRIPTION
**Pull request by gdkchan**
Zelda Tears of the Kingdom has a few cases where it uses a 4 components format instead of a 3 components format, but everything (offset, buffer stride) are calculated for a 3 components format, and the vertex shader also only accesses 3. The fact that it uses 4 causes the vertex attribute to exceed the stride in some cases. This is invalid and causes weird bugs on Metal.

It seems MoltenVK already has some code to work around this issue:
https://github.com/KhronosGroup/MoltenVK/blob/b3ae0f48d0170570e46c7b3a8bcd8278bb71f40e/MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm#L1311

However it does not take offset into account, only the format size, so it will only kick in for attributes with a offset of zero. This PR implements the same change on the emulator, but it also adds the offset to the size, so it applies to all cases where the attribute exceeds the stride, not just cases where the offset is 0 and there's no other attribute after.

Fixes vertex explosions on The Legend of Zelda: Tears of the Kingdom.
Before:
Captura de Tela 2023-05-24 às 22 25 10
Captura de Tela 2023-05-24 às 22 25 16
After:
Captura de Tela 2023-05-24 às 22 18 40
Captura de Tela 2023-05-24 às 22 18 49

Fixes vertex explosions reported on #4949.

### CODE REVIEW

**Comment by vesper8** [comment]
The hero we all need but don't deserve <3

**Review by marysaka — APPROVED** [review]

**Comment by noahgg12** [comment]
Are we merging this to the nightly builds?

**Comment by JustinSUF** [comment]
hi im dumb

**Review by riperiperi — APPROVED** [review]
Nice catch, this makes sense.

**Comment by gdkchan** [comment]
> Nice catch, this makes sense. Maybe the format size method should be in FormatExtensions?

They work with the Vulkan `VkFormat` enum, not the `Format` enum in the GAL project. So it wouldn't make sense to add it there, but I can move it to the Vulkan `FormatTable` class.

**Comment by khalidahusain** [comment]
Hey, i'm tyring to download it, but I'm not able to using the MacOS link or any other.

**Pull request merged**
