### PR TITLE
Don't dispose of renderer until after tex / program destroy commands have finished

### LINKED ISSUE #2850: Shin Megami Tensei V: Crash on exit after indeterminate time period
## Bug Report

</br>

### What's the issue you encountered?
Running Shin Megami Tensei V; did not stop emulation prior to exiting application from task bar (right-click, close all windows). Ryujinx became unresponsive, but the console is still responding. Had to end task from Task Manager. Confirmed issue re-occurred the next two days, but does not immediately occur if I load the game, then exit. 

### How can the issue be reproduced?

1. Open Ryujinx
2. Load Shin Megami Tensei V
3. Play for an undetermined period of time
4. Close application from Task Bar

### Log file
All three log files show a last modified date of today, so I included all three. Two of them are only 70 or so KB. 
[Ryujinx_1.0.7106_2021-11-17_18-12-18.log](https://github.com/Ryujinx/Ryujinx/files/7558579/Ryujinx_1.0.7106_2021-11-17_18-12-18.log)
[Ryujinx_1.0.7106_2021-11-17_18-12-58.log](https://github.com/Ryujinx/Ryujinx/files/7558580/Ryujinx_1.0.7106_2021-11-17_18-12-58.log)
[Ryujinx_1.0.7106_2021-11-17_16-39-16.log](https://github.com/Ryujinx/Ryujinx/files/7558581/Ryujinx_1.0.7106_2021-11-17_16-39-16.log)

### Environment?

- Ryujinx version: 1.0.7106</br>
- Game version: 1.0.1 (</br>
- System Specs:
  - OS: *Windows 10 Home v10.0.19042
  - CPU: *AMD Ryzen 5 3600 6-Core Processor, 3950 Mhz, 6 Core(s), 12 Logical Processor(s)
  - GPU: *NVIDIA GeForce RTX 3070
  - RAM: *32GB DDR4
- Applied Mods : N/A

### Additional context?
Issue does not immediately re-occur upon re-launching the game and exiting, but has occurred all 3 times I've played for an extended period. 
Additional info about your environment:</br>

### LINKED ISSUE #2863: Texture disposal hangs Ryujinx with stop emulation on certain games after playing for some time (including Xenoblade, SMTV, Pokemon)
### What's the issue you encountered?

Clicking on "Stop emulation" makes Ryujinx hang without closing any of its windows.

### How can the issue be reproduced?

It happens sometimes when you do the above when playing a game (I did it with Pokemon Brillant Diamond).

### Stack trace (logs don't show anything)

> Ryujinx.Graphics.GAL.dll!Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.New<Ryujinx.Graphics.GAL.Multithreading.Commands.Texture.TextureReleaseCommand>() Line 162   C#
> Ryujinx.Graphics.GAL.dll!Ryujinx.Graphics.GAL.Multithreading.Resources.ThreadedTexture.Release() Line 112   C#
> Ryujinx.Graphics.Gpu.dll!Ryujinx.Graphics.Gpu.Image.Texture.DisposeTextures() Line 1486   C#
> Ryujinx.Graphics.Gpu.dll!Ryujinx.Graphics.Gpu.Image.Texture.Dispose() Line 1516  C#
> Ryujinx.Graphics.Gpu.dll!Ryujinx.Graphics.Gpu.Image.TextureCache.Dispose() Line 1093   C#
> Ryujinx.Graphics.Gpu.dll!Ryujinx.Graphics.Gpu.Memory.PhysicalMemory.Destroy() Line 325 C#
> Ryujinx.Graphics.Gpu.dll!Ryujinx.Graphics.Gpu.GpuContext.RunDeferredActions() Line 246 C#
> Ryujinx.Graphics.Gpu.dll!Ryujinx.Graphics.Gpu.GpuContext.Dispose() Line 270   C#
> Ryujinx.HLE.dll!Ryujinx.HLE.Switch.DisposeGpu() Line 151 C#
> Ryujinx.dll!Ryujinx.Ui.GlRenderer.Dispose(bool disposing) Line 124   C#
> [External Code]   
> Ryujinx.dll!Ryujinx.Ui.MainWindow.SwitchToGameTable() Line 910 C#
> Ryujinx.dll!Ryujinx.Ui.MainWindow.CreateGameWindow.AnonymousMethod__89_0(object <p0>, System.EventArgs <p1>) Line 966   C#
> [External Code]   
> Ryujinx.dll!Ryujinx.Program.Main(string[] args) Line 177 C#

Ryujinx gets stuck in this loop during the texture disposal : 
```
while (_producerPtr == (_consumerPtr + QueueCount - 1) % QueueCount)
{
    // If incrementing the producer pointer would overflow, we need to wait.
    // _consumerPtr can only move forward, so there's no race to worry about here.

    Thread.Sleep(1);
}
```

### Environment?

- Ryujinx version: commit 02d786a0861b957fbd927553ac974dff473e1f4f </br>
- Game version: 1.1.1</br>
- System Specs:
  - OS: Windows 10
  - CPU: Ryzen 3900x
  - GPU: GTX 1060
  - RAM: 32GB
- Applied Mods : No

### PR DESCRIPTION
**Pull request by lostromb**
Should fix hangs on shutdown. Closes #2863 Closes #2850

### CODE REVIEW

**Comment by gdkchan** [comment]
Should fix #2850 and #2863, please add it on the PR description (as `Closes #2850` or `Fixes #2850` for example) to auto-close it when the PR is merged.

**Comment by lostromb** [comment]
Quick validation on Metroid, THPS, Xenoblade, ACNH, all of them shutdown and return to the rom list just fine.

**Comment by lostromb** [comment]
I don't have SMT5 to specifically validate the fix for #2850, but I have experienced the same issue in Xenoblade 2 and it seems to be fixed there.

**Review by gdkchan — APPROVED** [review]
I have tested SMT V myself, played it 5 times (playing for about 40 minutes on each of them). Out of those, it froze when I closed the window 2 times, and the other 3 times it closed properly. So I guess it hanging on exit is still an issue, but it's probably being caused by something else now.

**Comment by GamerzHell9137** [comment]
Can still get the issue in SMT V. You gotta play it a bit longer than 40 mins. 
image

**Comment by gdkchan** [comment]
So I finally had a chance to attach a debugger after the emulator locked up exiting SMT V.
Unfortunately just moving `Renderer.Dispose` is not enough as there is another case where the Render thread that is supposed to consume the command can exit early. If you look at `RendererWidgetBase`, you can find the main loop of the GPU thread inside the `Render` function, and it starts with:
```cs
                while (_isActive)
                {
                    if (_isStopped)
                    {
                        return;
                    }
 ```
 So just by setting `_isActive` to false would make the thread exit. And if we look at the `Exit` function, we can find:
 ```cs
             _isStopped = true;
            _isActive = false;
 ```
 Then if we look at the `End` function on `MainWindow`...
 ```cs
                     // We tell the widget that we are exiting.
                    RendererWidget.Exit();

                    // Wait for the other thread to dispose the HLE context before exiting.
                    _deviceExitStatus.WaitOne();
                    RendererWidget.Dispose();
 ```
The first call to `Exit` will set `_isActive` to false, making the GPU thread eventually exit. Now, this is not the problem, as the commands are supposed to be processed by the Render thread, not the GPU thread. But then, if we look at the GPU thread start function...
 ```cs
             _gpuThread = new Thread(() => {
                gpuLoop();
                _running = false;
```
And on the Render thread...
```cs
        public void RenderLoop()
        {
            // Power through the render queue until the Gpu thread work is done.

            while (_running && !_disposed)
            {
```
So the GPU thread exiting will make the Render thread exit aswell. And if the Render thread exits, then the dispose commands can't be processed and it gets stuck.

I'm not sure what's the best way to fix this. I think ultimately this code needs some large refactoring, as it seems pretty hard to reason about right now (and pretty easy to break).
 
Then later, we have the dispose call:
```cs
RendererWidget.Dispose();
```
This eventually calls `GpuContext.Dispose`, which will create more commands that needs to be processed, and this is when it will freeze (or not, if by luck the thread still hasn't checked the `_isActive` field).

BTW, there is another issue, command submission is not thread safe (the `New` function is not using interlocked increments for `_producerPtr`, and maybe other issues), I'm not sure if this is a problem right now, it would only be an issue if there are 2 or more threads submiting commands at the same time, and I don't know if this scenario is possible right now (presumably, when dispose is called, the GPU thread has already stopped submiting commands?).

**Comment by lostromb** [comment]
I was kind of thinking that since `Dispose()` is pretty overloaded, it would probably be better to split disposal into 2 phases for some classes, step 1 being a `Shutdown()` or equivalent function to trigger destroy of guest resources, and then follow that with regular disposal to handle host and C# resources.

**Comment by lostromb** [comment]
Since this doesn't actually fix the issue it's meant to, closing until we can revisit a proper solution

**Pull request closed without merging**
