### PR TITLE
Fix audio error on Linux when playing Paper Mario: Origami King

### PR DESCRIPTION
**Pull request by SirBlobman**
Whenever I was trying to get through the spa area with Kamek, Bowser Jr, and the multiple folded enemies battling the normal paper minions, Ryujinx would crash.

By enabling log files and compiling a debug version of Ryujinx, I traced the issue to the audio render.
Here are the relevant audio logs with me trying multiple audio systems.
```
SDL2:
https://cdn.discordapp.com/attachments/410208610455519243/1014263116273569842/Ryujinx_1.1.243_2022-08-30_15-54-20.log

SoundIO:
https://cdn.discordapp.com/attachments/410208610455519243/1014265886267428904/Ryujinx_1.1.243_2022-08-30_16-09-07.log

OpenAL:
https://cdn.discordapp.com/attachments/410208610455519243/1014266172151173202/Ryujinx_1.1.243_2022-08-30_16-04-52.log
```

So far I've been able to catch the exception, but I'm not sure how to fix the actual problem. At the minimum, I've made it so that the emulator no longer crashes.

Here is an example log of the caught exceptions:
```
00:01:43.331 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:02:23.927 |I| AudioProcessor.Worker AudioRenderer Decode: Coefficients Length: 16
00:02:23.927 |I| AudioProcessor.Worker AudioRenderer Decode: Coefficients Index: 8
00:02:23.927 |I| AudioProcessor.Worker AudioRenderer Decode: Coefficients Multiply Two: 16
00:02:23.927 |I| AudioProcessor.Worker AudioRenderer Decode: Coefficients Multiply Two Add One: 17
00:02:23.979 |E| AudioProcessor.Worker AudioRenderer Decode: Index error in audio decode System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Ryujinx.Audio.Renderer.Dsp.AdpcmHelper.Decode(Span`1 output, ReadOnlySpan`1 input, Int32 startSampleOffset, Int32 endSampleOffset, Int32 offset, Int32 count, ReadOnlySpan`1 coefficients, AdpcmLoopContext& loopContext) in C:\Users\SirBlobman\source\repos\Ryujinx\Ryujinx.Audio\Renderer\Dsp\AdpcmHelper.cs:line 117
00:02:23.982 |I| AudioProcessor.Worker AudioRenderer Decode: Coefficients Length: 16
00:02:23.982 |I| AudioProcessor.Worker AudioRenderer Decode: Coefficients Index: 10
00:02:23.982 |I| AudioProcessor.Worker AudioRenderer Decode: Coefficients Multiply Two: 20
00:02:23.982 |I| AudioProcessor.Worker AudioRenderer Decode: Coefficients Multiply Two Add One: 21
00:02:23.982 |E| AudioProcessor.Worker AudioRenderer Decode: Index error in audio decode System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Ryujinx.Audio.Renderer.Dsp.AdpcmHelper.Decode(Span`1 output, ReadOnlySpan`1 input, Int32 startSampleOffset, Int32 endSampleOffset, Int32 offset, Int32 count, ReadOnlySpan`1 coefficients, AdpcmLoopContext& loopContext) in C:\Users\SirBlobman\source\repos\Ryujinx\Ryujinx.Audio\Renderer\Dsp\AdpcmHelper.cs:line 117
00:02:26.305 |I| AudioProcessor.Worker AudioRenderer Decode: Coefficients Length: 16
00:02:26.305 |I| AudioProcessor.Worker AudioRenderer Decode: Coefficients Index: 11
00:02:26.305 |I| AudioProcessor.Worker AudioRenderer Decode: Coefficients Multiply Two: 22
00:02:26.305 |I| AudioProcessor.Worker AudioRenderer Decode: Coefficients Multiply Two Add One: 23
00:02:26.305 |E| AudioProcessor.Worker AudioRenderer Decode: Index error in audio decode System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Ryujinx.Audio.Renderer.Dsp.AdpcmHelper.Decode(Span`1 output, ReadOnlySpan`1 input, Int32 startSampleOffset, Int32 endSampleOffset, Int32 offset, Int32 count, ReadOnlySpan`1 coefficients, AdpcmLoopContext& loopContext) in C:\Users\SirBlobman\source\repos\Ryujinx\Ryujinx.Audio\Renderer\Dsp\AdpcmHelper.cs:line 117
```

Hopefully someone can help out with fixing this. Normally I'm a Java developer, so C# and audio systems are out of my scope.

### CODE REVIEW

**Comment by gdkchan** [comment]
I think that value is not supposed to be higher than 7, which might indicate that the stream is corrupted. On the Switch this code most likely doesn't have any bounds check, so it would just read garbage. Assuming that the stream is not corrupted and that is actually triggering OOB read on the Switch, we could probably change `& 0xF` to `& 7` to avoid the exception.

**Comment by SirBlobman** [comment]
I have just tested a debug build and release build on my computer and the problem is fixed. I'll mark this as ready now.

**Comment by gdkchan** [comment]
Can you attach a save next to the place where the crash happens? Would make reproducing it easier.

**Comment by SirBlobman** [comment]
> Can you attach a save next to the place where the crash happens? Would make reproducing it easier.

Here is the save file. You need to walk down to where all the enemies are and try to exit the door. Kamek will tell you that you can't leave and then the game will crash with the audio error.


[PM-OK-save-data.zip](https://github.com/Ryujinx/Ryujinx/files/9465820/PM-OK-save-data.zip)

**Comment by Thog** [comment]
I will try to reproduce it to see if there isn't something wrong with the logic

**Comment by LukeWarnut** [comment]
This crash also seems to happen in https://github.com/Ryujinx/Ryujinx-Games-List/issues/4141

**Pull request closed without merging**
