### PR TITLE
Unscale textureSize when resolution scaling is used

### PR DESCRIPTION
**Pull request by gdkchan**
Monster Hunter Rise has a shader that divides `gl_FragCoord` by screen size, then multiplies it by the texture size and uses the result on `texelFetch`. This doesn't work because while `gl_FragCoord` is unscaled, the `textureSize` isn't. This change also unscales the size which fixes the issue.
Before:
image
After:
image
Might also fix a similar issue on Monster Hunter Stories 2 (#2436). Needs testing.

### CODE REVIEW

**Comment by zombie167** [comment]
This PR cannot be completed fix the problem that the image of Monster Hunter Stories 2 in the battle under high resolution.It has been improved.Unfortunately, the problem also occurs at the native resolution now.

s1
s2
s3
s4

**Comment by gdkchan** [comment]
This build is outdated, this issue was already fixed on the latest one.

**Comment by zombie167** [comment]
> This build is outdated, this issue was already fixed on the latest one.

Thank you very much! The problem has been fixed
s5
s6

**Review by riperiperi — APPROVED** [review]
Looks good here.

**Review by Thog — APPROVED** [review]

**Comment by Linear524** [comment]
This commit broke The Touryst graphics:


Before it was fine and rendered image was like this:

**Pull request merged**
