### PR TITLE
Replacing ZbcColorArray with Array4<uint>

### PR DESCRIPTION
**Pull request by marco-carvalho**

### CODE REVIEW

**Comment by gdkchan** [comment]
Nice catch. This code can be improved further:
- Private fields names should start with underscore, so it would be `_element0` for example, not `element0`.
- This could use a switch expression which would be more compact than the `if`/`else if`/`else` chain.

**Comment by gdkchan** [comment]
Actually, I'd just delete the `ZbcColorArray` type and replace it with `Array4<uint>` from `Ryujinx.Common.Memory`.

**Comment by marco-carvalho** [comment]
I'm sorry, but I'm not really familiar with the code base for me to make those changes.

**Comment by gdkchan** [comment]
You just need to replace `ZbcColorArray` with `Array4<uint>` and then delete the `ZbcColorArray` struct.

**Comment by marco-carvalho** [comment]
@gdkchan I just did what you said

**Comment by gdkchan** [comment]
Can you adjust the struct alignment? After that I will approve.

**Comment by marco-carvalho** [comment]
@gdkchan Could you check again?

**Review by gdkchan — APPROVED** [review]
lgtm, thanks.

**Review by AcK77 — APPROVED** [review]

**Comment by Littl3Guy** [comment]
This PR broke grass/tree/bush animations in Pocket Monsters S/V.

**Comment by gdkchan** [comment]
> This PR broke grass/tree/bush animations in Pocket Monsters S/V.
> 
> Edit: The animations start, but don't loop for whatever reason.

It was not caused by this change, it was the one merged right before this one, #5220.

**Comment by Littl3Guy** [comment]
Yup sorry about that, the changelog on github looks a little confusing:
image

 I thought the version number was at the bottom of the changelog, not the top.

**Comment by gdkchan** [comment]
It's fine, you helped narrow it down, I didn't expect this change would cause it so I knew it was probably the one before or after it.

**Pull request merged**
