### PR TITLE
Remove Appveyor from Readme and SLN

### PR DESCRIPTION
**Pull request by Mou-Ikkai**
I replaced the Appveyor badge in the Readme with a Github Actions alternative. Along with this, I removed appveyor.yml and removed it from the SLN.

### CODE REVIEW

**Comment by Shahil-Ayato** [comment]
Was just about to do this, nice work.

**Review by Thog — APPROVED** [review]

**Review by Shahil-Ayato — APPROVED** [review]

**Comment by jduncanator** [comment]
It would probably be best to have an alternative setup first before you remove the only CI tool that does a release build.

Actions only builds PR's at the moment, and only generates "dirty" Git tagged builds. We'd need to set it up to generate versioned builds from master.

GitHub actions also isn't a good solution to this as you need to have a GitHub account _and_ be logged in to download artifacts. It's going to be a pretty poor user experience for most users who want to download the build off the website directly.

**Comment by riperiperi** [comment]
Are people still using the appveyor config to run their own builds? Might cause issues just removing the config outright.

**Comment by yell0wsuit** [comment]
Agree with the badge change, but probably should keep appveyor config for the time being like riperiperi said

**Comment by Thog** [comment]
> Are people still using the appveyor config to run their own builds? Might cause issues just removing the config outright.

I mean people could just readd it if they want, it's not like they are going to migrate if we don't make any move here...

**Review by AcK77 — APPROVED** [review]

**Pull request merged**
