### PR TITLE
Defer address space mirror mapping and use it only if strictly needed

### PR DESCRIPTION
**Pull request by gdkchan**
This is an attempt to reduce the number of active mappings that the emulator has in general, in order to try addressing the weird Windows 11 issue with mapping and some games reaching the default mappings limit on Linux.

The approach taken here is that if the range of memory being accessed is contiguous, we just access the backing memory block directly. Doing this avoids the need to map the range on the address space mirror. If it's not contiguous, then it maps on the mirror and uses that. There's now a tree to keep track of the mappings, where each mapping can have 3 states: Unmapped, Mapped, and MappedWithMirror. If an attempt is made to access a "Mapped" range that is not contiguous, then it maps it on the mirror and changes it to "MappedWithMirror". 

The old page table that was used on the memory manager was removed. It was only being used for `GetPhysicalRegions`. This can also be done with the tree, and it's more efficient for large ranges, so I just implemented it using the tree.

The downside of this change is that methods that returns memory ranges from the address space mirror or writes to it might be slightly slower (due to the additional cost of checking the mapping). Hopefully it does not have a noticeable performance impact.

Depends on #3410 as I have used the intrusive red-black tree implementation from there.

I'm mainly interested on testing here to decide what to do from here.
This is what needs to be tested:
- Games in general on Windows 11. I want to know if the heavy stuttering and the issues closing the emulator still persists.
- UE4 games on Windows 11. Same as above, but UE4 games are more problematic as they do several small mappings.
- UE4 games on Linux. Mainly want to know if it's still causing out of memory errors/crash due to hiting the mappings limit.

I don't expect the last two to be completely fixed with this change, but it should at least be better as the number of mappings is drastically reduced in some cases.

### CODE REVIEW

**Comment by jeliebig** [comment]
I don't know if Yoshi's Crafted World is a good candidate for this test, but I just played the first level of it. (I don't really know what other games use UE4, so I just used that) If you would like me to test this with another game just tell me a few other games that use UE4 and I'll see what I have.

I didn't notice any issues nor experienced crashes while playing, which is why I'm assuming that this game also had no issues before.

This is the log file:
[Ryujinx_1.1.0+95979f2_2022-06-23_00-34-05.log](https://github.com/Ryujinx/Ryujinx/files/8962266/Ryujinx_1.1.0%2B95979f2_2022-06-23_00-34-05.log)

Command line used to run Ryujinx: `__GL_THREADED_OPTIMIZATIONS=0 __GL_SYNC_TO_VBLANK=0 gamemoderun GDK_BACKEND=x11 ./Ryujinx -r <custom dir>`

<details>
  <summary>pc specs in case these matter</summary>
  
  ```
  julian:ryujinx-Release-1.1.0+95979f2-linux_x64/ $ screenfetch                                                                                                                                                                    
                   -`
                  .o+`                 julian@Julian-PC
                 `ooo/                 OS: Arch Linux
                `+oooo:                Kernel: x86_64 Linux 5.15.48-1-lts
               `+oooooo:               Uptime: 3h 19m
               -+oooooo+:              Packages: 2058
             `/:-:++oooo+:             Shell: zsh 5.9
            `/++++/+++++++:            Resolution: 3200x1080
           `/++++++++++++++:           DE: KDE 5.95.0 / Plasma 5.25.1
          `/+++ooooooooooooo/`         WM: KWin
         ./ooosssso++osssssso+`        GTK Theme: Breeze [GTK2/3]
        .oossssso-````/ossssss+`       Icon Theme: BeautyLine
       -osssssso.      :ssssssso.      Disk: 17T / 30T (57%)
      :osssssss/        osssso+++.     CPU: Intel Core i5-8600K @ 6x 4.3GHz [68.0°C]
     /ossssssss/        +ssssooo/-     GPU: NVIDIA GeForce RTX 2060
   `/ossssso+/:-        -:/+osssso+-   RAM: 7185MiB / 32017MiB
  `+sso+:-`                 `.-/+oso:
 `++:.                           `-/+/
 .`                                 `/
  ```
</details>

**Comment by Ackliez** [comment]
Games [Unreal Engine 4]

Link for more : 

https://en.Wikipedia.org/wiki/List_of_Unreal_Engine_games#Unreal_Engine_4

Bravely default 2
The last remnant ( remaster )
Ocean horn 2
Samurai showdown
Samurai jack battle through time 
Wee 2k battlegrounds 
Stela
Ruined
Redout 2
Ark survival evolved
Kholat
Moro racer 4
The flame in flood
Getsu Fūma Den: Undying moon
Fuga: Melodies of steel
Azur lane crossware 
Brigantine : The legend of Runersia
The Caligula: Overdose
Postal redux 
Backbone
Graven
Hot wheels unleashed
Moto GP
GTA trilogy
Little nightmares 2

**Comment by MutantAura** [comment]
Causing a crash in SSBU that does not occur in master:
[Ryujinx_1.0.0-dirty_2022-06-23_11-38-18.log](https://github.com/Ryujinx/Ryujinx/files/8966456/Ryujinx_1.0.0-dirty_2022-06-23_11-38-18.log)

Tested #3410 separately and didn't see this behaviour so it is something caused by these specific changes.

Steps to reproduce are simply attempting to start any match, be it in training mode or standard smash modes. After character select and pressing START ryujinx will crash.

**Comment by gdkchan** [comment]
> Causing a crash in SSBU that does not occur in master: [Ryujinx_1.0.0-dirty_2022-06-23_11-38-18.log](https://github.com/Ryujinx/Ryujinx/files/8966456/Ryujinx_1.0.0-dirty_2022-06-23_11-38-18.log)
> 
> ```
> 00:00:45.950 |E| HLE.GuestThread.19 Application : Unhandled exception caught: Ryujinx.Memory.WindowsShared.WindowsApiException: VirtualProtect returned error code 0x57.
>    at Ryujinx.Memory.WindowsShared.PlaceholderManager.ReprotectViewInternal(IntPtr address, IntPtr size, MemoryPermission permission, Boolean throwOnError) in C:\Users\domw0\Documents\GitHub\Ryujinx\Ryujinx.Memory\WindowsShared\PlaceholderManager.cs:line 469
>    at Ryujinx.Memory.WindowsShared.PlaceholderManager.RestoreRangeProtection(UInt64 address, UInt64 size) in C:\Users\domw0\Documents\GitHub\Ryujinx\Ryujinx.Memory\WindowsShared\PlaceholderManager.cs:line 665
>    at Ryujinx.Memory.WindowsShared.PlaceholderManager.UnmapViewInternal(IntPtr sharedMemory, IntPtr location, IntPtr size, MemoryBlock owner) in C:\Users\domw0\Documents\GitHub\Ryujinx\Ryujinx.Memory\WindowsShared\PlaceholderManager.cs:line 303
>    at Ryujinx.Memory.WindowsShared.PlaceholderManager.UnmapView(IntPtr sharedMemory, IntPtr location, IntPtr size, MemoryBlock owner) in C:\Users\domw0\Documents\GitHub\Ryujinx\Ryujinx.Memory\WindowsShared\PlaceholderManager.cs:line 228
>    at Ryujinx.Memory.MemoryManagement.UnmapView(IntPtr sharedMemory, IntPtr address, UInt64 size, MemoryBlock owner) in C:\Users\domw0\Documents\GitHub\Ryujinx\Ryujinx.Memory\MemoryManagement.cs:line 104
>    at Ryujinx.Cpu.Jit.MemoryManagerHostMapped.Unmap(UInt64 va, UInt64 size) in C:\Users\domw0\Documents\GitHub\Ryujinx\Ryujinx.Cpu\Jit\MemoryManagerHostMapped.cs:line 170
>    at Ryujinx.HLE.HOS.Kernel.Memory.KPageTable.Unmap(UInt64 address, UInt64 pagesCount) in C:\Users\domw0\Documents\GitHub\Ryujinx\Ryujinx.HLE\HOS\Kernel\Memory\KPageTable.cs:line 158
>    at Ryujinx.HLE.HOS.Kernel.Memory.KPageTableBase.UnmapPhysicalMemory(UInt64 address, UInt64 size) in C:\Users\domw0\Documents\GitHub\Ryujinx\Ryujinx.HLE\HOS\Kernel\Memory\KPageTableBase.cs:line 1414
>    at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.UnmapPhysicalMemory64(Syscall syscall, IExecutionContext context) in C:\Users\domw0\Documents\GitHub\Ryujinx\Ryujinx.HLE\Ryujinx.Horizon.Generators\Ryujinx.Horizon.Generators.Kernel.SyscallGenerator\SyscallDispatch.g.cs:line 1172
>    at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.Dispatch64(Syscall syscall, IExecutionContext context, Int32 id) in C:\Users\domw0\Documents\GitHub\Ryujinx\Ryujinx.HLE\Ryujinx.Horizon.Generators\Ryujinx.Horizon.Generators.Kernel.SyscallGenerator\SyscallDispatch.g.cs:line 3472
>    at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(IExecutionContext context, UInt64 address, Int32 id) in C:\Users\domw0\Documents\GitHub\Ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SyscallHandler.cs:line 38
>    at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm) in C:\Users\domw0\Documents\GitHub\Ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 50
>    at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\Users\domw0\Documents\GitHub\Ryujinx\ARMeilleure\Translation\Translator.cs:line 168
>    at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in C:\Users\domw0\Documents\GitHub\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1261
>    at System.Threading.Thread.StartCallback()
> ```
> 
> Tested #3410 separately and didn't see this behaviour so it is something caused by these specific changes.
> 
> Steps to reproduce are simply attempting to start any match, be it in training mode or standard smash modes. After character select and pressing START ryujinx will crash.

Can you try again with latest changes? It should be fixed now.

**Comment by MutantAura** [comment]
> Can you try again with latest changes? It should be fixed now.

Ayup that's fixed it 👍

**Comment by piplup55** [comment]
spongebob bfbb no longer crashes with a "out of memory" error on linux
image

**Comment by donkey2020** [comment]
this build has helped me alot.

While playing FF 3 hopes w/ stable release or any earlier versions of Ryujinx on Windows 11, I had _audio stuttering, random fps drop, game frozen at 0-1 fps during prep-for-battle screen, & random crashes_.

My machine specs:

```
General Info
Version: 1.1.148 | Firmware: 14.1.1 | CPU: AMD Ryzen 7 3700X 8-Core Processor | 
GPU: NVIDIA Corporation NVIDIA GeForce GTX 1660 SUPER/PCIe/SSE2 (4.6.0 NVIDIA 516.59) | 
RAM: 16296 MB | OS: Microsoft Windows 10.0.22000 (X64)
```

This build fixed nearly all of the above-mentioned issued except the low FPS during combat, but that's the common issues on plenty of Warriors game, not necessarily the fault of Ryujinx.

**Comment by PhiZero** [comment]
I can also confirm that this build _drastically_ improves performance across the board for me. Especially with games that do not have a shader cache yet, as expected. 

All of the following games had the following results:

_WITHOUT_ this PR:
- Shaders taking anywhere up to 3-5 minutes to compile, without moving camera or the "viewport" in any way.
- Any extra movement or menuing would slow down everything again.
- Random stutters even going through the same areas.
- Extremely long load times between zones, sometimes even soft locking.
- Moving shaders back into place, long load times and stutters still occurred sporadically.

_WITH_ this PR:
- None of the aforementioned issues occur.
- Shader compilation is just usual speed
- No random stutters.
- Load times significantly reduced, varying based on the game.

Games tested:
Astral Chain
FE Warriors Three Hopes
Xenoblade 1
Xenoblade 2

Specs: Win 11, 5900X, 3080 Ti, 32GB.

**Comment by 2Tsk2** [comment]
PR seems to have fixed my issues with Demon Slayer: Kimetsu no Yaiba – The Hinokami Chronicles which had unbearable stutters on the stable build which took mins to unfreeze.

specs: windows 11, 12100f, 1650 ,8gb

**Comment by PhiZero** [comment]
Even though #3437 is now merged, it seems I am still getting incredibly slow shader load/compiles. As a result, there's also frequent hitches and freezes even with shaders already in place.

Right now on master, loading around 10k shaders takes me 10 minutes and 27 seconds. I don't think this is how it's supposed to be.
image

Reverting peri's changes and merging this (to work around the merge conflict) results in a massive speed up.
image

Times are: Loading/Rebuilding/Rebuilt.

It would be greatly appreciated if this PR is considered again, since I think it's immensely beneficial to performance on Windows 11. The performance improvements in my earlier comment still stand.

**Comment by gdkchan** [comment]
Superseded by #3648 (but it does not include all the changes).

**Pull request closed without merging**
