### PR TITLE
Add Patch/Bktr Nca support

### PR DESCRIPTION
**Pull request by simontime**
This'll allow patch/update Ncas to be loaded as a second input argument

### CODE REVIEW

**Comment by simonmkwii-dev** [comment]
> I don't exactly know how LibHac works, bit I think you got Nca and BaseNca swaped

yep 
megafacepalm

**Comment by simontime** [comment]
Bumping this

**Comment by emmauss** [comment]
rebase it first

**Comment by BaronKiko** [comment]
Can this be merged with a rebase or should it be closed?

**Comment by emmauss** [comment]
Closing this due to inactivity

**Pull request closed without merging**
