### PR TITLE
WIP: Avoid errors due to non implemented services on execution

### PR DESCRIPTION
**Pull request by albfan**
Initial solution to avoid services marked as unimplemented make a game to crash

relates with #1472

### CODE REVIEW

**Comment by albfan** [comment]
@AcK77 I suppose a log message in execution to trace unimplemented services would be enough. Maybe if debug mode will be a thing, throw an exception on that case.

**Comment by AcK77** [comment]
Throw a `ServiceNotImplementedException` is an expected behavior, since we don’t want to stub service calls, at least not without checking by RE what the call do! Ignore missing service setting is just an hack who shouldn’t be used. And `try/catch` the exception to ignore it is the same. It’s  not the way we want to go.

**Comment by Thog** [comment]
I agree with @AcK77, the ignore missing service setting is only here to be able to "collect" what call need to be implemented.
Crashing is an expected behaviour and we don't want to rely on any hacks for releases
However, in the future we should try to make the emulator stop emulation and generate an error report to the user to improve the user experience.

**Comment by albfan** [comment]
As feedback, no crashes with this PR. Not sure what those commands represents and what I'm missing, but looks like developers first, ending in a real bad user experience (unneeded crash).

Agreed that keep the codebase maintanable is a goal. Count on me to implement these services. Will continue providing feedback on related issue.

**Comment by Thog** [comment]
@albfan Problem is that if you ignore those services call instead of crashing, the game will receive unexpected data and that would totally cause undefined behaviours as a result. (you could end up corrupting a save in a non recoverable way for example)

That's why, it's safer to crash here.

**Comment by albfan** [comment]
@Thog I see. Will keep in mind. By now is a big improvement for my use case. But not sure how to collect info to understand what the game is trying to do, and what it needs to implement.

Then this report is enough or you need something else? (I can add more traces and collect more info if you find it useful

**Pull request closed without merging**
