### PR TITLE
[NV] Fix NvHostCtrlGetConfig

### PR DESCRIPTION
**Pull request by Cyuubi**

### CODE REVIEW

**Comment by AcK77** [comment]
You read a struct with a size of 0x183 bytes, who looks... A little strange for me!
And you don't trim the readed values so the comparaison is probably always `false`.

**Comment by AcK77** [comment]
According to switchbrew your struct seems to be good:
```
NVHOST_IOCTL_CTRL_GET_CONFIG
Gets configured settings. Not available in production mode.

 struct {
   __in char domain_str[0x41];       // "nv"
   __in char param_str[0x41];
   __out char config_str[0x101];
 };
```

But those values are already present in `Ryujinx.HLE/OsHle/Services/Set/NxSettings.cs` and seems to be not used since the content of this file is generated automatically from a switch.

**Comment by Cyuubi** [comment]
GetConfig is mostly used in launch games.

**Comment by Cyuubi** [comment]
Also, I just checked and the if's are working fine so...

**Comment by AcK77** [comment]
As I said on Discord:

The result need to be wrote in `ConfigString` instead of `ParameterString` and you wrote the whole struct in memory who is not what the call need... Plus, you don't use the NxSetting.cs values, how are set to null because it's not used in production mode.

**Comment by AcK77** [comment]
Closed in favor of better implementation in #243

**Pull request closed without merging**
