### PR TITLE
Optimized memory modified check

### PR DESCRIPTION
**Pull request by RyadaProductions**
This was initially in some cases more expensive than plainly sending the data. Now it should have way better performance.

First step in splitting up the massive PR #533  from gdkchan
Refactors in the big PR will be added as a seperate PR after all functional changes have been implemented.

### CODE REVIEW

**Comment by RyadaProductions** [comment]
I have added these refactors in a seperate commit instead of rebasing them together to keep the history as clean as possible.

**Comment by jduncanator** [comment]
I assume it's building (I didn't check), but so long as the changes are the same as in the other PR, this looks good to me,

**Comment by gdkchan** [comment]
I believe that with those changes `ValueRange` and `ValueRangeSet` can be removed aswell (at `Ryujinx.Graphics`).

**Comment by RyadaProductions** [comment]
ValueRange and ValueRangeSet are currently still in use because in this PR the Cache changes have not been added yet. Those will be in a seperate PR.

**Comment by gdkchan** [comment]
Are you sure? Because they are only used on `NvGpuVmmCache`.

**Comment by RyadaProductions** [comment]
Yes. As far as I gathered the changes in `NvGpuVmmCache` need the new Cache part to properly be able to merge. As it seems like a direct result of the change in Cache implementation.
With this PR I tried to only commit the logic that was related to the change in the memory modified check.

**Comment by gdkchan** [comment]
The changes on NvGpuVmmCache are completely independent from the other changes, and should work fine on they own.

**Comment by RyadaProductions** [comment]
Removed `ValueRange` and `ValueRangeSet` in this commit as they were not used anymore.

**Pull request merged**
