### PR TITLE
Implemented EnsureIdTokenSync

### LINKED ISSUE #629: acc:u0 IManagerForApplication: 2 (EnsureIdTokenCacheAsync) not implemented
IManagerForApplication EnsureIdTokenCacheAsync is not implemented.

## Service description:
[Switchbrew](https://switchbrew.org/wiki/Account_services#IManagerForSystemService) | [Reswitched](https://reswitched.github.io/SwIPC/ifaces.html#nn::account::baas::IManagerForApplication(2))

```
EnsureIdTokenCacheAsync() -> object<nn::account::detail::IAsyncContext>
```

> Returns an #IAsyncContext.

## Required by:
- https://github.com/Ryujinx/Ryujinx-Games-List/issues/128
- https://github.com/Ryujinx/Ryujinx-Games-List/issues/173
- https://github.com/Ryujinx/Ryujinx-Games-List/issues/76

### PR DESCRIPTION
**Pull request by ertherod**
Added an implementation of EnsureIdTokenSync + IAsyncContext needed by this function
Fixes #629

### CODE REVIEW

**Comment by Chenj168** [comment]
The _event have not set signal, game maybe wait it for infinite.

After set signal for _event, the IManagerForApplication: 3 (LoadIdTokenCache) needs to be implemented.

**Comment by ertherod** [comment]
How should I add a signal to an event ? I don't understand what you think it is meant to

**Comment by jduncanator** [comment]
`IAsyncContext` is a bit more complex than what it seems.

It wraps an async job, that has an event that is called once some job is complete in the background. HasDone should return the status of the job, GetResults should return the result of the job once its complete (or return an error result if the job is still running), Cancel should request a background job cancellation.

Luckily, .NET has a lot of classes surrounding this behaviour built in thanks to it's async Task implementation. I think most of this could probably be implemented using a TaskCompletetionSource and a CancellationToken.

**Comment by Chenj168** [comment]
> How should I add a signal to an event ? I don't understand what you think it is meant to
>
I guess the game might use it like this.

MainThread
```
IAsyncContext context;
EnsureIdTokenCacheAsync(out context);

Event systemEvent;
context.GetSystemEvent(out systemEvent);
```

WorkThread
```
systemEvent.WaitOne();  <- wait for signal

bool hasDone;
context.HasDone(out hasDone);

if(hasDone)
{
    if(context.GetResult() == Success)
    {
         LoadIdTokenCache(??);
    }
    else
    {
         //Error
    }
}
else
{
    //Error
}
```

**Comment by jduncanator** [comment]
Closing for now, if you wish to update the PR, feel free to reopen.

**Pull request closed without merging**
