### PR TITLE
Stop using glTransformFeedbackVaryings and use explicit layout on the shader

### PR DESCRIPTION
**Pull request by gdkchan**
There are two ways to specify what should be written to the transform feedback buffers when the feature is enabled on OpenGL. The first and the one that we use is passing the name of the shader outputs to be written using the `glTransformFeedbackVaryings` function. The newer method is specifying it directly on the shader using layout qualifiers. This PR implements the latter. The reason for that is that Vulkan only supports the latter, theres no "TransformFeedbackVaryings" function on Vulkan to specify that information outside of the shader. In fact, this code was mostly pulled from the Vulkan branch. So, the main advantage here is reducing diffs with this branch, which will make review easier, and will allow us to use the same method on both APIs.

One limitation of this new approach is that it's not possible to, for example, write the same output into multiple buffers (although, it might be possible to create multiple outputs and copy the value). But since games also have to specify the transform feedback layout, they should also be bound by the same limitations.

Testing is appreciated to ensure nothing regressed. The following games are known to use transform feedback:
- Xenoblade Chronicles: Definitive Edition (grass).
- Xenoblade Chronicles 2 (grass).
- SNK Heroines: Tag Team Frenzy (all animated ingame characters).

Main benefit here is reducing the diff with the Vulkan branch and making review easier. Should not cause any changes on games.

### CODE REVIEW

**Review by Thog — APPROVED** [review]

**Comment by saldabain** [comment]
> Pokémon Shiny Diamond doesn't even work in this version
> 
> imagem
> 
> [Ryujinx_1.0.0+a9532cb_2022-01-20_13-54-51.log](https://github.com/Ryujinx/Ryujinx/files/7907123/Ryujinx_1.0.0%2Ba9532cb_2022-01-20_13-54-51.log)
> 
> [Ryujinx_1.0.0+a9532cb_2022-01-20_14-00-22.log](https://github.com/Ryujinx/Ryujinx/files/7907147/Ryujinx_1.0.0%2Ba9532cb_2022-01-20_14-00-22.log)
> 
> 
> 
> 

Pokemon "Shiny Diamond" does not exist, and the screenshot is of Link's Awakening.

Please clarify which game you are having issues with:

Pokemon Shining Pearl
Pokemon Brilliant Diamond
Link's Awakening

**Comment by MarkLanders777** [comment]
Pokemon Shining Pearl is working fine here

**Comment by AlfredoDore** [comment]
> Please clarify which game you are having issues with:
> 
> Pokemon Shining Pearl Pokemon Brilliant Diamond Link's Awakening
I don't speak English, I use google translator hahahahaha

**Comment by AlfredoDore** [comment]
> Pokemon Shining Pearl is working fine here

funny that not even in the Vulkan test it works, it just doesn't start

**Comment by AlfredoDore** [comment]
> Pokemon Shining Pearl is working fine here
Gives this error, not even in the main version it starts 
imagem

**Comment by MarkLanders777** [comment]
Working fine here, you just have to wait until the game boots

**Comment by AlfredoDore** [comment]
> Working fine here, you just have to wait until the game boots
> 
>  

maybe because I'm an AMD user 
imagem

**Comment by emu1989** [comment]
Wow! This PR fixes missing models in Pokemon Legends Arceus!!!! Thanks @gdkchan for the quick fix!

pla_before

pla_after

**Comment by lostromb** [comment]
This appears to fix shaders that were previously logging "Ryu:31: error: 'transform feedback qualifier' : not supported in this stage: fragment"

**Review by riperiperi — APPROVED** [review]
LGTM. Tried Xenoblade DE and everything is working fine with my existing shader cache.

**Comment by lostromb** [comment]
Xenoblade 2 looks fine
image

**Comment by AlfredoDore** [comment]
Haven got grass trouble, she keep blinking 
graphically Crash is fine but has a lot of latency (including in FMVs) 
imagem
imagem
imagem
imagem
imagem
[Ryujinx_1.0.0+a9532cb_2022-01-21_12-48-06.log](https://github.com/Ryujinx/Ryujinx/files/7914963/Ryujinx_1.0.0%2Ba9532cb_2022-01-21_12-48-06.log)
[Ryujinx_1.0.0+a9532cb_2022-01-21_12-55-21.log](https://github.com/Ryujinx/Ryujinx/files/7915032/Ryujinx_1.0.0%2Ba9532cb_2022-01-21_12-55-21.log)

**Comment by riperiperi** [comment]
Was this issue caused by this PR? Does it also happen on master?

**Comment by AlfredoDore** [comment]
> Was this issue caused by this PR? Does it also happen on master?
yes, also in master, however it doesn't happen in Vulkan

**Comment by jduncanator** [comment]
> > Was this issue caused by this PR? Does it also happen on master?
> 
> 
> 
> yes, also in master, however it doesn't happen in Vulkan 
> 
> 

This PR isn't intended to fix anything, so it's expected for something that's broken in master to still be broken after this PR.

**Pull request merged**
