### PR TITLE
Enable updates in portable mode. (related to #1885)

### LINKED ISSUE #2125: Auto-updater disabled for portable mode users
### What's the issue you encountered?

The auto-updater was disabled in the recent "[Implement friendlier portable mode](https://github.com/Ryujinx/Ryujinx/pull/1885)" PR because, while it was being developed, the auto-updater was purging everything in the Ryujing program folder. 
Once https://github.com/Ryujinx/Ryujinx/pull/1899 was merged, this functionality inside https://github.com/Ryujinx/Ryujinx/pull/1885 was supposed to be re-enabled as it is now safe and the updater preserves subfolders within the Ryujinx program directory..

As it stands, portable mode users can no longer auto-update unless disabling portable mode.

### How can the issue be reproduced?

Enable portable mode using the method of your choice, and try to use the updater.

### Log file

N/A

### Environment?

N/A

### Additional context?

### PR DESCRIPTION
**Pull request by jms-c**
This should fixes #2125!
This works as the update system has been pacified (#1899).

Suggestions requested!

### CODE REVIEW

**Comment by jms-c** [comment]
Temporarily added a debugging commit to this PR.

**Comment by jms-c** [comment]
Feel free to test, it will instantly show an update! (please test in portable mode ofc)

**Comment by AcK77** [comment]
You should just remove the check and nothing more.
It seems you have hardcoded the version field to trigger the update.
Until you change things back to a mergeable state, I turn this PR as a draft.

**Comment by jms-c** [comment]
Debugging code removed.
CI builds therefore are untestable atm.

**Review by AcK77 — APPROVED** [review]

**Comment by jms-c** [comment]
Thanks AcK77!

**Review by riperiperi — APPROVED** [review]
LGTM, haven't personally tested a portable update though.

**Comment by jms-c** [comment]
Only real thing problem that could exist is the following, afaik:
1. Someone scattering their ryujinx folder with files (not in a seperate folder)

**Pull request merged**
